### ISSUE TITLE
Import will not resolve

### ISSUE THREAD

**Issue by JonathanDailey** [sillsdev/web-languageforge#10]
Trying to import zipped LIFT file. (11MB) It never resolves after 12 hours of waiting.  Next time I open project "Server Status Code 500" 
![capture](https://cloud.githubusercontent.com/assets/11212987/6393476/f67268be-bd8f-11e4-9435-e753b75699ce.JPG)

**Comment by cambell-prince** [comment]
Please let us also know the url in the address bar of your browser, and
also a copy of the zipped lift project would be helpful also.  Perhaps via
a dropbox link would be best.

**Comment by irahopkinson** [comment]
Hi Jonathan

I see you are using the development site rather than the live site. The
development site will get broken regularly as we develop it. Please use the
live site here https://languageforge.org/

If you are still having issues please send me a copy of your zipped
exported FLEx project that tried to upload.

Blessings, Ira

-- 
Ira Hopkinson

SIL International Language Software Development, PaLaSo <http://palaso.org/>

On Thu, Feb 26, 2015 at 9:18 PM, JonathanDailey <notifications@github.com>
wrote:

> Trying to import zipped LIFT file. (11MB) It never resolves after 12 hours
> of waiting. Next time I open project "Server Status Code 500"
> [image: capture]
> <https://cloud.githubusercontent.com/assets/11212987/6393476/f67268be-bd8f-11e4-9435-e753b75699ce.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sillsdev/web-languageforge/issues/10>.
>



-- 
Ira Hopkinson

SIL International Language Software Development, PaLaSo <http://palaso.org/>

**Comment by JonathanDailey** [comment]
I have switched to the other site.  I don't know if this is the same
problem but new error. [image: Inline image 1]
DB link Here> https://dl.dropboxusercontent.com/u/255739/part%203.zip

**Comment by irahopkinson** [comment]
Hi Jonathan

Thanks for sending your LIFT zip. We have not come across a lift file this
large before so it will great to test with. It should be able to import in
around 5 minutes so don't wait hours.

The lift file in the zip appears to be 64MB with around 43,000 entries. Can
you confirm this and the actual number of entries?

Blessings, Ira

On Fri, Feb 27, 2015 at 12:19 AM, JonathanDailey <notifications@github.com>
wrote:

> I have switched to the other site. I don't know if this is the same
> problem but new error. [image: Inline image 1]
> DB link Here> https://dl.dropboxusercontent.com/u/255739/part%203.zip
>
> On Thu, Feb 26, 2015 at 8:55 AM, irahopkinson <notifications@github.com>
> wrote:
>
> > Hi Jonathan
> >
> > I see you are using the development site rather than the live site. The
> > development site will get broken regularly as we develop it. Please use
> the
> > live site here https://languageforge.org/
> >
> > If you are still having issues please send me a copy of your zipped
> > exported FLEx project that tried to upload.
> >
> > Blessings, Ira
> >
> > --
> > Ira Hopkinson
> >
> > SIL International Language Software Development, PaLaSo <
> > http://palaso.org/>
> >
> > On Thu, Feb 26, 2015 at 9:18 PM, JonathanDailey <
> notifications@github.com>
> > wrote:
> >
> > > Trying to import zipped LIFT file. (11MB) It never resolves after 12
> > hours
> > > of waiting. Next time I open project "Server Status Code 500"
> > > [image: capture]
> > > <
> >
> https://cloud.githubusercontent.com/assets/11212987/6393476/f67268be-bd8f-11e4-9435-e753b75699ce.JPG
> > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sillsdev/web-languageforge/issues/10>.
> > >
> >
> >
> >
> > --
> > Ira Hopkinson
> >
> > SIL International Language Software Development, PaLaSo <
> > http://palaso.org/>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sillsdev/web-languageforge/issues/10#issuecomment-76191507
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sillsdev/web-languageforge/issues/10#issuecomment-76221800>
> .
>



-- 
Ira Hopkinson

SIL International Language Software Development, PaLaSo <http://palaso.org/>

**Comment by JonathanDailey** [comment]
That sounds about right.  It is only a subset of my full data base which is closer to 53,000 entries.

**Comment by JonathanDailey** [comment]
BTW, Is the limit on the zip file going to increase eventually?  With
pictures and audio files it gets beyond your limit pretty easily.

**Comment by irahopkinson** [comment]
Hi Jonathan

Yes. Thanks to your file we are working on fixing this at the moment.

Blessings, Ira

On Tue, Mar 3, 2015 at 12:29 AM, JonathanDailey <notifications@github.com>
wrote:

> BTW, Is the limit on the zip file going to increase eventually? With
> pictures and audio files it gets beyond your limit pretty easily.
>
> On Fri, Feb 27, 2015 at 9:50 PM, irahopkinson <notifications@github.com>
>
> wrote:
>
> > Hi Jonathan
> >
> > Thanks for sending your LIFT zip. We have not come across a lift file
> this
> > large before so it will great to test with. It should be able to import
> in
> > around 5 minutes so don't wait hours.
> >
> > The lift file in the zip appears to be 64MB with around 43,000 entries.
> Can
> > you confirm this and the actual number of entries?
> >
> > Blessings, Ira
> >
> > On Fri, Feb 27, 2015 at 12:19 AM, JonathanDailey <
> notifications@github.com
> > >
> > wrote:
> >
> >
> > > I have switched to the other site. I don't know if this is the same
> > > problem but new error. [image: Inline image 1]
> > > DB link Here> https://dl.dropboxusercontent.com/u/255739/part%203.zip
> > >
> > > On Thu, Feb 26, 2015 at 8:55 AM, irahopkinson <
> notifications@github.com>
> > > wrote:
> > >
> > > > Hi Jonathan
> > > >
> > > > I see you are using the development site rather than the live site.
> The
> > > > development site will get broken regularly as we develop it. Please
> use
> > > the
> > > > live site here https://languageforge.org/
> > > >
> > > > If you are still having issues please send me a copy of your zipped
> > > > exported FLEx project that tried to upload.
> > > >
> > > > Blessings, Ira
> > > >
> > > > --
> > > > Ira Hopkinson
> > > >
> > > > SIL International Language Software Development, PaLaSo <
> > > > http://palaso.org/>
> > > >
> > > > On Thu, Feb 26, 2015 at 9:18 PM, JonathanDailey <
> > > notifications@github.com>
> > > > wrote:
> > > >
> > > > > Trying to import zipped LIFT file. (11MB) It never resolves after
> 12
> > > > hours
> > > > > of waiting. Next time I open project "Server Status Code 500"
> > > > > [image: capture]
> > > > > <
> > > >
> > >
> >
> https://cloud.githubusercontent.com/assets/11212987/6393476/f67268be-bd8f-11e4-9435-e753b75699ce.JPG
> > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/sillsdev/web-languageforge/issues/10>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Ira Hopkinson
> > > >
> > > > SIL International Language Software Development, PaLaSo <
> > > > http://palaso.org/>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/sillsdev/web-languageforge/issues/10#issuecomment-76191507
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/sillsdev/web-languageforge/issues/10#issuecomment-76221800
> > >
> >
> > > .
> > >
> >
> >
> >
> > --
> > Ira Hopkinson
> >
> > SIL International Language Software Development, PaLaSo <
> > http://palaso.org/>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/sillsdev/web-languageforge/issues/10#issuecomment-76508735
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sillsdev/web-languageforge/issues/10#issuecomment-76757210>
> .
>



-- 
Ira Hopkinson

SIL International Language Software Development, PaLaSo <http://palaso.org/>

**Comment by cambell-prince** [comment]
Also, in the future we want to be able to sync via send / receive which
will remove the need for import / export.

**Comment by JonathanDailey** [comment]
That sounds preferable.   Maybe I should wait for that.  I was mainly 
wanting to use it in that way anyway.

**Comment by megahirt** [comment]
Closing because this is really old
