### ISSUE TITLE
languagedepot login doesn't work

### ISSUE THREAD

**Issue by laurentiuionescu** [sillsdev/web-languageforge#100]
I'm trying to import a project from landuagedepot, buy it doesn't work. The credential are correct, but is says: The username or password isn't valid on LanguageDepot.org. I've tryed with languagedepot and it works there.

**Comment by megahirt** [comment]
Hi Lauren,

I'm sorry syncing with FLEx isn't working for you.  Can you reply with your project code on language depot and also your username on language forge and I'll investigate.

Thanks,

Chris

**Comment by laurentiuionescu** [comment]
Hi Chris. 

My project in language depot is hbo-spa-flex

Username: laurentiui 
Password: lestat6017

Thanks

Laurentiu

**Comment by irahopkinson** [comment]
Hi Lauren

I can see the same problem you are. We are diagnosing the problem at the moment.

As a work-around I've created another username **laurentiui2** (same password) and added this to the project as a *Manager*. You can use this username in the interim on Language Forge.

Thanks for you patience as we diagnose the problem.

Blessings, Ira

**Comment by irahopkinson** [comment]
Hi Laurentiu

We have now fixed the problem so I have removed the work-around username **laurentiui2** from the project.

Since you posted your password here, please change your password as soon as possible.

Blessings, Ira

**Comment by laurentiuionescu** [comment]
Hi Ira,

Thank you for your help. I tried and now is working. 

Have a nice day, 

Laurenţiu
