### ISSUE TITLE
convert .htaccess files (mod_rewrite) to apache config and remove all .htaccess files from the repo

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1000]

**Comment by longrunningprocess** [comment]
this also includes removing all the `index.html` that represent "no access" files

**Comment by longrunningprocess** [comment]
`https://localhost/Site/views/` already results in an error page, not the contents of the underlying `index.html` so I'll remove these for now and get some additional thoughts during the PR review.

![image](https://user-images.githubusercontent.com/4412848/125510304-659328d0-820c-4f1e-8925-7af0732dc4bf.png)

**Comment by megahirt** [comment]
WOOHOO issue #1000 created!  We should celebrate!...err...
