### ISSUE TITLE
Toolbar surface is scrollable and is not visible as as the user scrolls down the entry

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1004]
I observed a LF user have trouble with navigation between entries because the navigation control surface scrolled off the screen as they browsed the entry information.

For example:

![image](https://user-images.githubusercontent.com/3444521/125810649-b1e142a9-4bd4-450a-913d-6d8db44d8c9e.png)

The above image shows the toolbar outlined in red, which scrolls off the screen as the user scrolls down the entry.

Additionally, the side navigation list (blue marker) and the "rendered entry" (yellow highlight) also scroll off the screen.

Interim solution:

1) Fix the toolbar (red marker) to the top of the application space in a separate non scrollable div

2) Move the left navigation down so that it is in line with the top of the entry editor space.

3) add the rendered entry (yellow highlight) to the fixed toolbar space in 1) above

Important considerations: LF is a responsive UI with 4 (I think) break points.  The changes above must not break existing UI in other viewport sizes.

Our project uses Bootstrap v4 for UI components and viewport size (responsive breakpoints) definitions.

A proper solution will demonstrate that the fixed toolbar works across all viewport sizes.

**Mockup 1**
![image](https://user-images.githubusercontent.com/3444521/125812185-f4ed0608-d950-48f1-a592-0d220faf2b2e.png)

**Mockup 2**
![image](https://user-images.githubusercontent.com/3444521/125812410-4672ab0f-c96a-46bd-9435-a139068c4393.png)

**Comment by longrunningprocess** [comment]
here's a quick approach
![image](https://user-images.githubusercontent.com/4412848/125851906-45100168-ff9f-40b8-a23a-fa940d190144.png)
![image](https://user-images.githubusercontent.com/4412848/125852037-80c6b98b-03e4-43ed-8714-1be3b5d6aa8c.png)

that needs a little more work to hide the content between the `container` and the `lexAppContainer`
![image](https://user-images.githubusercontent.com/4412848/125852097-ecedfe2b-b5ad-4fca-bba6-ea068679cfc3.png)

I think simply expanding the `container` to hit the header, i.e., removing the padding between the two would be a quick way to address that particular issue but then of course we also need to relocate the `div.word-definition-title` up into the `container` as well.

**Comment by megahirt** [comment]
This is great -

I didn't know about position: sticky;

>
>

**Comment by longrunningprocess** [comment]
It's relatively new, https://caniuse.com/css-sticky
