### ISSUE TITLE
Should we allow more image file types?

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1005]
While testing the Language Forge picture upload, I tried uploading a .gif file, and got the error "(filename).gif is not an allowed image file. Ensure the file is one of the following types: .jpg, .jpeg, .png."

Should we allow .gif files? What about .svg files? There may be other common image types that people might want to upload, but .gif and .svg are both going to be small files (unless it's an animated .gif), so those two file types, at least, seem like good candidates to allow people to upload.

**Comment by megahirt** [comment]
Yes, we should allow uploading gif and svg types.  If this is a small fix
that can be done quickly - just get it done.


>

**Comment by rmunn** [comment]
As a test, I renamed the file to (filename).png and uploaded it, and got the same error with the new filename: "(filename).png is not an allowed image file. Ensure the file is one of the following types: .jpg, .jpeg, .png." So it's going by MIME type instead of by extension. I'll add svg and gif to the list of allowable MIME types.

**Comment by rmunn** [comment]
Note that [.svg images *can* contain embedded Javascript](https://github.com/w3c/svgwg/issues/266), which *can* be malicious. I think I'll hold off on allowing .svg uploads for now, because that's not a 5-minute fix. The proper fix for SVG images, to be totally safe, would be to add code that scans any SVG uploads for embedded Javascript, and either strips it out (if that's possible) or disallows the upload (if stripping out the embedded Javascript isn't possible).

Adding .gif files is a 5-minute fix, though; I've already done that, and I'm going to push a PR soon.
