### ISSUE TITLE
prevent navigation to "list view" except on mobile

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1015]
The editor list view (see screenshot below) serves almost no purpose.  The design was to grow the list view into a project dashboard, however there are many other features we hope to build before a dashboard becomes priority.  Because of this, the list view doesn't really achieve anything and serves only to add an extra click to get to the editor where real work can be done.

![image](https://user-images.githubusercontent.com/3444521/126753806-6719238c-79bf-4b21-b0b5-ff54d3ea1597.png)

There is no reason to remove the list view code, however, we can do the following to prevent users navigation to the list view:
- make the "entry" view the default route
- remove the "back to list" button for all viewports except mobile
- mobile viewport is the only viewport that should be able to navigate to the list, because it does not use the compact list display

By removing this view, users will have one less click to get to working on their dictionary.

**Comment by rmunn** [comment]
I don't know about removing the "Back to list" button for desktop. The list view does serve one useful purpose on the desktop: it doesn't contain the editor view so it's much wider and you can see more of each entry's definition, example sentences, etc.

I agree with making the editor view the default, though.

**Comment by megahirt** [comment]
good point.  A minimal helpful change would be to simply make the editor the default route and leave the list alone.  Who knows, someone may want to use it (but I would be surprised)

**Comment by alex-larkin** [comment]
Looks like the list view would be handy for "seeing the data." reading, skimming, in a more compact way.

**Comment by megahirt** [comment]
We decide to make the editor the default view and that was achieved in a recent PR
