### ISSUE TITLE
Display View of entry doesn't show several fields

### ISSUE THREAD

**Issue by makerling** [sillsdev/web-languageforge#102]
I noticed that if an entry has an example sentence and translation of the example sentence, only the  example is displayed, not the translation of the example sentence in the "List View". 

Also it seems other fields such as Grammar Note, Anthropology Note, Summary Definition among others are ones that I noticed the same behavior (not displaying in the List View). Is there an ability to configure the "List View" of the lexicon, or is this a bug? It would help the user to view the data much easier if the List View is configurable or at least displays everything entered. 

Thanks,

![screenshot from 2017-04-27 15 54 09](https://cloud.githubusercontent.com/assets/12460083/25484213/ca725804-2b61-11e7-909f-d6f1eb5ee3d9.png)

**Comment by megahirt** [comment]
Hi,

Thanks for reporting this.  It's not a bug per-se, but a limitation.  We don't have a way to "configure the dictionary" like FLEx does, and We've hard coded the fields that are shown in the list view.  I'm open to suggestions on what fields we should show.  I would say that the translation of the example sentence should be showing, so I'll go in and have that added.  Are there other fields you think should be shown?  I agree it would be nice to have a "configure dictionary" but at this time it's not planned.

**Comment by irahopkinson** [comment]
Hi,

We've updated **Language Forge** to include the **Example Translation** in the **List View**. Can you have a look to confirm it is working for you.

Thanks for letting us know about this issue. Are there other fields you think should be shown?

**Comment by makerling** [comment]
Thanks for the fix and info! This is the response I received from the project administrator:

> You asked if there is another field that should display, yes, there is. In the same entry “nochmals” I added text in the **summary definition**. We use that for some additional explanation about grammar issues. It is not displayed either. So it would be nice to have it displayed by covering the entry into square brackets.

So, the field **summary definition** is one that is desired to be added. Thanks!

![screenshot from 2017-05-02 14 37 35](https://cloud.githubusercontent.com/assets/12460083/25616390/ee384456-2f44-11e7-97c2-3571064498a4.png)
