### ISSUE TITLE
Keyman Integration with Input systems and multi-text fields

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1022]
One of the core functions of minority language technology is keyboarding.  Minority language keyboards are often not available through operating system keyboards.  Fortunately, there's [Keyman](https://keyman.com/).  Keyman has a first-class API, [documentation and javascript keyboard engine](https://keyman.com/developer/keymanweb/) that we can implement in Language Forge.

A MVP for Keyman integration would:

- [ ] manager can type in the Keyman Keyboard ID of the desired keyboard for use in that input field
- [ ] user sees button next to input field when input is focused, which will display on-screen keyboard (default off?)
- [ ] automatic keyboard switching between fields based upon defined keyboard for that field

Configuration mockup:
![image](https://user-images.githubusercontent.com/3444521/126762354-ed9cd77e-fa3d-4911-8a9e-d5246bfa53e5.png)

Keyman button in field mockup:
![image](https://user-images.githubusercontent.com/3444521/126763887-00d8641a-760c-419d-bca6-2f645d05c4b1.png)

Configuration wish list:
- [ ] manager can search and pick keyboard from a list of available keyboards for that language in input systems config

**Comment by rmunn** [comment]
This is definitely a needed feature, though it's not low-hanging fruit. This fruit is way up at the top of the tree, and is going to need specialized equipment to go up and pick it. :smiley:

**Comment by megahirt** [comment]
We'll see how high or low the fruit is.  My understanding is that KeymanWeb is pretty easy to integrate.  Was going to ask @darcywong00 for a consultation.

**Comment by darcywong00** [comment]
The "Add KeymanWeb to a Website" section from the documentation link above has the couple lines of code to get started (initializing KeymanWeb and adding keyboards).

Then use [`setActiveKeyboard`](https://help.keyman.com/developer/engine/web/14.0/reference/core/setActiveKeyboard) to switch.
