### ISSUE TITLE
undo / redo buttons

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1023]
Possibly use `document.execCommand('undo)`, although this probably only works in Chrome/Edge and not Firefox.

**Comment by alex-larkin** [comment]
I second this idea 😀. If implemented, I suggest communicating to users when the undo history is dumped. Close tab or refresh? Last 20 actions always undoable? I imagine edits by other users could affect this too.

**Comment by megahirt** [comment]
@alex-larkin this is a poor man's undo implementation which utilizes the browser's edit undo stack.  Most applications would implement their own application undo stack, which is unfortunately not what this card is about (a lot more work).  So, the undo stack is dependent on what the browser provides (unlimited capacity presumably) and most certainly goes away when the browser is closed/refreshed.

**Comment by alex-larkin** [comment]
Ah okay. Sounds good.

What if the first time someone undos, LF shows a little message saying, "undo history is dependent on your browser, and is erased when this tab is closed or refreshed."?

Or maybe this is a little enough of a thing that users wouldn't need that to be made explicit 🤷‍♂️. Thoughts?

**Comment by alex-larkin** [comment]
Use cases:
- User accidentally drags and drops
- User accidentally deletes or writes over selected texts
- User otherwise changes his mind on an edit

Note: Users are not asking for this as far as we can tell

**Comment by palmtreefrb** [comment]
Native undo/redo functionality using document.execCommand('undo') is marked as "Deprecated. Not for use in new websites." according to [mozilla exeCommand browser compatability](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#browser_compatibility). 
There are examples for coding and implementing the functionality, though not a trivial endeavor.  Third party libraries that might be an option. A concern might be the ageing angularjs framework might not have continued support for these libraries.

**Comment by megahirt** [comment]
Thank you @palmtreefrb for this research.  The original intention of this card was to gain a valuable feature (undo/redo buttons) for little cost or effort.  I see now from your research that there is no standard way to invoke the browser's undo/redo methods.  I can go two ways on this card:
1) abandon the effort, based on the research above, and based on a principle that we don't use a deprecated API.
2) implement an undo/redo button based on the deprecated `document.execCommand('undo')` but have the button only show on browsers where this is still implemented.  The result is that the buttons will be available for some but potentially not others (while the API may be deprecated, [it appears that it is still widely supported](https://caniuse.com/?search=execCommand))

I am leaning toward number 2 above, implementing it.  Any other feedback?

The `document.queryCommandEnabled('undo')` is what can be used to show/hide the button in the UI.
See [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandEnabled) and [caniuse.net](https://caniuse.com/?search=queryCommandEnabled)

**Comment by megahirt** [comment]
After discussion at our team meeting last week, we decided against pursuing this as a feature as there is weak evidence that this will add value to existing users, and it only serves to increase technical debt on an aging code base.
