### ISSUE TITLE
remove bugsnag completely from JS client

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1035]

**Comment by alex-larkin** [comment]
I notice that there are a LOT of open BugSnag issues at https://jira.sil.org/projects/LF/issues/LF-84?filter=allopenissues. Should we close all of those?

**Comment by alex-larkin** [comment]
I found how to mark all of these issues as resolved and archive them, but I don't have the permissions needed to do so. If someone could please do the following: 

1. visit https://jira.sil.org/issues/?jql=project%20%3D%20LF%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22%5C%22Created%20automatically%20via%20Bugsnag%5C%22%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC (all unresolved LF issues matching the string "Created automatically via Bugsnag")
2. Click on Tools on the upper right
3. Under "Bulk change", click "all 180 issues"
4. Hit the check box under "next"
5. Click "Next"
6. The rest should be straightforward. Maybe comment "This BugSnag comment has been bulk-resolved and archived." Then resolve and archive them?

Thanks!

**Comment by megahirt** [comment]
@alex-larkin I apparently don't have permission to archive them either.  I will contact the JIRA admin and see about getting permission to bulk archive.

![image](https://user-images.githubusercontent.com/3444521/128371725-774408e1-ac61-4eae-ac4e-5f52c77aed97.png)

**Comment by megahirt** [comment]
I have successfully gotten permission to archive these issues and archived 152 of them.  I left 30 or so open because they still seem worth reviewing.
