### ISSUE TITLE
Feature request: lexical relations in Language Forge

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1052]
Feature request from a user: being able to establish links between two words (antonyms, synonyms, etc.) in Language Forge. The current way to handle this is to establish those links in FLEx and do a Send/Receive, but Language Forge doesn't provide any UI for seeing or editing those links. Lexical relations created in FLEx are invisible to Language Forge users, and multiple people have asked for this feature in Language Forge; it's not just the one user who would like to have this.

**Comment by alex-larkin** [comment]
Dale shared that this is an important feature to him.
