### ISSUE TITLE
Animation for fading out a field that is being hidden because it's empty

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1057]
When you delete the last writing system of a hidden-if-empty field, it just immediately vanishes. Could use an animation there, showing the field fading out over the course of a half second, and then the rest of the fields sliding up over the course of another half second. (Timings to be adjusted once we see what it looks like).

Alternate idea: don't disappear the field until you've clicked elsewhere and it has lost cursor focus.

**Comment by megahirt** [comment]
> Alternate idea: don't disappear the field until you've clicked elsewhere and it has lost cursor focus.

Perhaps a combination of both...fade out instead of immediately vanish, and don't vanish until the field has lost cursor focus.

**Comment by megahirt** [comment]
@palmtreefrb see details of this issue over at #1064
