### ISSUE TITLE
Branching, Tagging and Release Process

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1060]
This issue lays out the branching, tagging and release process for LF

We will follow a modified version of [GitFlow as described in this seminal article](https://datasift.github.io/gitflow/IntroducingGitFlow.html).  A diagram from the article:
![image](https://user-images.githubusercontent.com/3444521/128802895-2e68ab9d-8abe-4176-a6ae-1bc550d7c92a.png)

### Develop
In conforming to GitFlow and the way that others would expect to interact with our repo, the **develop** branch will now be our default branch for feature work and PRs.  **develop** will be our default git branch.  All PRs for new features will be against **develop**.

### Staging
The staging branch is like the "release" branch in the illustration above.  We make stabilizing squash commits (still make PR branches) on staging much like we do on **develop**.  In the process of preparing to release, developers create PR branches against the **staging** branch.  These are squash commits just like on develop.

### Master
The **master** branch as seen in the illustration above represents our production release.  Git tags on the **master** branch will indicate a published image from that commit.  **Master** will contain only merge commits from **staging** and an unlikely hotfix.

## In What Ways Do We Differ From GitFlow?

- We do squash commits for single-author PRs. (most are single-author)
- Merge commits are reserved for merging branches (master, staging, develop) into each other
-  We have a single **staging** branch instead of multiple feature branches.

## Prerequisites
- The build number must be established/made available in GitHub Actions as that is where the application is built for production, the image is tagged and the image pushed to DockerHub.
- The build version number will be SemVer

## Release Process
- The LF team will ideally release a new minor version once a month e.g. v1.8 (August), v1.9 (September), etc.  These releases are characterized by a public announcement and "GitHub Release" created with accompanying release notes.
- In between minor releases, small stabilizing bugfix releases may be shipped.  These smaller releases are not publicized widely or call for a new Github Release.  Directly communication with users who may be affected by these stabilizing releases is necessary, but it's not necessary to communicate to the general public about bugfix releases unless it affects everyone.
- Each release should have a GitHub Release associated with the monthly major/minor release
- We also maintain a release notes file that is linked to from within the application.  This would be identical to the GitHub release in content.

## Build Number Usage
Each shipped release will be referenced by a unique build version number.  This number will be used for:
- Docker image tagging
- displaying the version number in the running application
- cache busting
- tagging a commit in our repo

## Build Number Determination
A SemVer build version number contains 3 components: major.minor.patch The major and minor version components will be determined by the release cycle we are in (e.g. August = 1.8).  The patch number (starting at 0 for each release) will be increment by 1 for each actual shipping release, however minor.

## Docker Image Naming
We will publish both staging and production docker images.

### Staging Image
Staging images will follow the image name convention `sillsdev/web-languageforge:staging-abc123` where `abc123` is the commit SHA of the commit of the image.  Additionally, the latest staging image will also be tagged as simply `sillsdev/web-languageforge:staging`.

### Production Image
Production images will follow the image name convention `sillsdev/web-languageforge:1.8.0` where `1.8.0` is the version tag, also tagged in git as `v1.8.0`  Additionally, the latest production image will asso be tagged simply as `sillsdev/web-languageforge:latest`.

## Triggers
A Git tag created by the project lead in the form of "v1.8.0" will trigger a new production build that indicates a release.  We will manually deploy production releases.

A push to the **staging** branch will also trigger a build of a staging image intended to be automatically deployed to the staging server.

Note: I put a lot of thought into how it might work with a trigger from a "GitHub Release" being created.  This would seem to work for monthly major.minor releases, however I don't want to publish revision bugfix releases in GitHub Releases, which left me with "How would I create a new release if I don't want to create a new GitHub release for this small change?"  That's what led me to the tagging solution, since I can craft tags in a predictable way that lead to production image builds.

### Staging Deployment
Our long-term goal will be to have a fully automated staging deployment based upon the docker image tag `sillsdev/web-languageforge:staging`, representing latest staging.  A TeamCity build configuration will be configured to automatically deploy to the K8 staging environment accessible at qa.languageforge.org whenever a new staging image is available.

### Production Deployment
Deployment of a new production release is a manual process due to various complexities and the need to control when users actually receive new code.  Manual deployment is a good thing :)  The product lead waits for the production image to be built and published, crafts a release announcement (monthly) to the user community, and then runs the deployment scripts to deploy a new image to our production environment in AWS.  This is done from the product lead's machine with their authorized K8s token.

## Action Items

- [x] create a **develop** branch and protect it in the same way as master (no direct commits)
- [x] make **develop** the default branch in GitHub
- [x] change all existing PRs to target **develop**
- [x] change TeamCity to trigger and build off the **develop** branch
- [x] update the GA build and publish to trigger on both tags and staging. (PR #1066)
- [x] Determine build number in GA and use that for image tagging. (PR #1066)
- [x] merge develop into staging
- [x] merge staging into master
- [x] tag latest master as v1.8.0
- [ ] Paste the contents of this issue text into a CONTRIBUTING.md file once I've finalized what it should say

**Comment by longrunningprocess** [comment]
> We also maintain a release notes file that is linked to from within the application. This would be identical to the GitHub release in content.

I wonder if we might consider either simply linking to the `/releases` url, e.g., https://github.com/silinternational/idp-profile-ui/releases, or if we might write a little web scraper in LF that scrapes the content from the GitHub page?  Obviously, if we can do this release content once and have a single source of data that will be simpler than copying and pasting.

---

I can image a `staging` branch being helpful in a complex scenario of timing, features and commits but I'm wondering whether we want to consider whether simply having a `develop` and `master` where `develop` will deploy to the staging environment and the associated images would be tagged with `:develop` or even `:develop-<uid>`?  Maybe we can chat more about it at our next pairing session.

---

> Production images will follow the image name convention sillsdev/web-languageforge:1.8.0 where 1.8.0 is the version tag, also tagged in git as v1.8.0 Additionally, the latest production image will asso be tagged simply as sillsdev/web-languageforge:latest.

I don't immediately see the value in additionally tagging with the `v` as well, mind explaining the rationale there?  And, is tagging the production image with `:latest` out of convention or do we anticipate that being useful for something specific?

---

> Our long-term goal will be to have a fully automated staging deployment based upon the docker image tag sillsdev/web-languageforge:staging, representing latest staging. A TeamCity build configuration will be configured to automatically deploy to the K8 staging environment accessible at qa.languageforge.org whenever a new staging image is available.

Yes, I do believe this is achievable but will require a little more creativity since we're mixing TC and GHA platforms..."wiring" them up is the only hold-up here.

---

> Manual deployment is a good thing :) 

That might be a bit of an overstatement, at best its just "ok" ;-)  Anyway, this probably doesn't belong in the final version.

> This is done from the product lead's machine with their authorized K8s token.

There may be a long-term vision where that kind of access would be taken away and the only way to do deployments is via TC so LTOps is always in control of production deployments, i.e., there would be a job in TC for deploying to production and if for some reason someone needed direct access via tokens, they would be granted on an as-needed basis.  Again, this is a long-term possibility and something we can further discuss when we're together again.

**Comment by longrunningprocess** [comment]
> I don't immediately see the value in additionally tagging with the v as well, mind explaining the rationale there?

Maybe it's for this? https://github.com/sillsdev/web-languageforge/pull/1066/files#diff-645877df28ed52028e568a1857840168e80368210dfccfe6213c48fc3808bf13R7

**Comment by longrunningprocess** [comment]
@rmunn , with this work I believe you can delete https://github.com/sillsdev/web-languageforge/pull/1026 now.

**Comment by megahirt** [comment]
@longrunningprocess I really appreciate the feedback.  Here are some of my responses:

> I wonder if we might consider either simply linking to the `/releases` url, e.g., https://github.com/silinternational/idp-profile-ui/releases, or if we might write a little web scraper in LF that scrapes the content from the GitHub page? Obviously, if we can do this release content once and have a single source of data that will be simpler than copying and pasting.

Yes, this would be a welcome contribution.  We should add this as a nice-to-have after releasing.  We will stick with the current release notes working the way it is for v1.8

> I can image a `staging` branch being helpful in a complex scenario of timing, features and commits but I'm wondering whether we want to consider whether simply having a `develop` and `master` where `develop` will deploy to the staging environment and the associated images would be tagged with `:develop` or even `:develop-<uid>`? Maybe we can chat more about it at our next pairing session.

I do understand well the temptation to get rid of release branches all together and just go with **develop** and **master**.  After all, we currently only have two deployments - why not just have two branches?  I think this can work for smaller projects.  My experience with large projects like LF is that release branches (staging) are necessary.  There are times where we will be making larger, more complex changes on develop that could span multiple weeks of work at a time and multiple PRs.  During periods where we are doing larger changes or implementations we also want to have the ability to stabilize a release by fixing bugs (and testing them on staging) before shipping them.  Without a release branch, PRs can become large and unwieldy, sticking around for weeks because of the desire not to destabilize **develop**.

GitFlow is a well-known branching methodology where each element has a purpose and adds value.  In our case, we should feel free to question the value of each element and pick the elements which work best for us.  I believe that having at least one release branch adds good value.  I am stopping short of full GitFlow by not going with multiple release branches :)  That said, the closer we align with GitFlow, the easier it will be for outsiders to understand and engage with our workflow.

> I don't immediately see the value in additionally tagging with the `v` as well, mind explaining the rationale there? And, is tagging the production image with `:latest` out of convention or do we anticipate that being useful for something specific?

The debate over whether to "v" or not "v" in Git tags is long and continues on today.  There are a host of well-known projects that use "v" and many that do not.  Both Git and the Linux kernel use "v" in tags, and the Git documentation itself uses examples of tagging with "v" in the tag name.  As I understand it, both are conventions now and primarily a matter of opinion.  There were historical reasons why one would choose a preceding "v", and even SemVer 1.0 required it, but that's no longer the case.

Further reading: 
- https://stackoverflow.com/questions/2006265/is-there-a-standard-naming-convention-for-git-tags
- https://git-scm.com/book/en/v2/Git-Basics-Tagging

> There may be a long-term vision where that kind of access would be taken away and the only way to do deployments is via TC so LTOps is always in control of production deployments, i.e., there would be a job in TC for deploying to production and if for some reason someone needed direct access via tokens, they would be granted on an as-needed basis. We could still push the button to deploy to production anytime we wanted but TC would be the only place with tokens granting production access. Again, this is a long-term possibility and something we can further discuss when we're together again.

I don't see any issues with this long term vision, however I would expect that LTOps would need to mature quite a bit in order to safely take over the mantle of sole authorized agent to deploy production code such that the product lead (myself) could be comfortable and sleep at night. :)  TC could be the proxy for LTOps authorization, yes.

**Comment by megahirt** [comment]
> And, is tagging the production image with :latest out of convention or do we anticipate that being useful for something specific?

@longrunningprocess I'm going off my reading of docker tagging best practice articles and the general consensus is that tagging the same image using both *stable tagging strategies* and *unique tagging strategies* are a best practice and versatile way to reference images.  Having a `:latest` provides us with a stable tag that we can reference in staging specifically.  We probably won't use the production `:latest` but I'll tag it since it's minimal effort.

References: 
- https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/
- https://docs.microsoft.com/en-us/azure/container-registry/container-registry-image-tag-version

**Comment by longrunningprocess** [comment]
I'm going to re-open this since we should produce some artifact from it like a CONTRIBUTING doc or an update to the README, thanks.

**Comment by longrunningprocess** [comment]
An outstanding question to this is the merge from `staging` to `develop`... who's involved, what are the tollgates, etc...

**Comment by megahirt** [comment]
We are reviewing this process and trialing it this month.  Up for discussion during our retrospective.

**Comment by megahirt** [comment]
This document is significantly out of date such that we've moved to a two branch model and have a different version tagging strategy.  Closing as obsolete.
