### ISSUE TITLE
Consider adding `mono-runtime` package to Docker image

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1098]
The LfMerge package currently (2021-08-24) needs the `mono5-sil` package to run the FW 8 versions of lfmerge, and the `mono-runtime` package to run the FW 9 versions. I'm currently working on figuring out whether we can go back to running both the FW 8 and FW 9 builds on `mono5-sil` or whether we can run both builds on `mono-runtime`. But in the event that we have to run one build on `mono5-sil` and the other one on `mono-runtime`, we might have to add the `mono-runtime` package to the list of packages installed in the `app` Dockerfile.

**Comment by megahirt** [comment]
we decided this morning to not make this dependency change until after deployment, and this would be done in a testing channel where we have time to test the impact of this change.

**Comment by megahirt** [comment]
Closing this issue as outdated since we are now pursuing a dot net core strategy.
