### ISSUE TITLE
Project titles not being handled well on small viewports

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1102]
![image](https://user-images.githubusercontent.com/4412848/131172873-7a627397-a687-41a2-80f4-787e1a28864b.png)

maybe truncate or move block vertical...the dev team can talk through solutions. since there are various ways to solve this for users.

**Comment by alex-larkin** [comment]
Thanks!

**Comment by megahirt** [comment]
This is still an issue.

**Comment by megahirt** [comment]
Steps to improve title flow on small viewports:

The following apply to the small device width and lower:
- [ ] use icon only for Settings and Share button.  Do not show the label
- [ ] Change font size of title to match the "Language Forge" label font size, which is slightly smaller
- [ ] truncate title to available width (dynamic) using `white-space: nowrap; overflow: hidden;`

**Comment by longrunningprocess** [comment]
> Steps to improve title flow on small viewports:
> 
> The following apply to the small device width and lower:
> 
> * [ ]  use icon only for Settings and Share button.  Do not show the label
> * [ ]  Change font size of title to match the "Language Forge" label font size, which is slightly smaller
> * [ ]  truncate title to available width (dynamic) using `white-space: nowrap; overflow: hidden;`

I like all of those ideas, in addition we could consider ellipsis (https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) as well as a horizontally scrollable container in that scenario.

**Comment by megahirt** [comment]
@longrunningprocess I thought about the `text-overflow: ellipsis` but given how little width there is to begin with, I wasn't sure how much width the `...` would take.  It's worth trying out and seeing how it looks.

I'd like to avoid scrolling containers at this point.
