### ISSUE TITLE
intermittent 502 errors for long-running client requests

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1106]
## Summary ##
This issue was discovered when testing the new K8s languageforge.org deployment.  To be fair, I cannot confirm that the issue didn't exist before, so it may not be unique to this deployment.

I first experienced this when trying to update the dictionary configuration for a Alex's project (non-S/R zip upload).

![image](https://user-images.githubusercontent.com/3444521/131461329-bef5a84a-b107-4d22-8847-13696a4db3a2.png)

Something in the configuration takes an extremely long time to update successfully.  The configuration takes between 20-30 seconds to update on languageforge.org and this seems absurdly long.  @rmunn suspects it is because of anthropological categories that PHP has to parse.

## Investigation Process ##
Our first thought was that the container was not responding appropriately to cloudflare, leading to a cloudflare 502.

On closer inspection, the 502 is just passed along from the webserver.  Cloudflare reports this in it's reply when it says: "The webserver reported a bad gateway error".  So this is not a Cloudflare 502, this is webserver 502 from inside K8s.

Our next thought was that the nginx ingress controller was prematurely cutting off the response, because it is a long wait after all.  We looked at the following ingress attributes and were able to apply those to the ingress directly in Rancher, but we did not experience any changes.  As it turns out, the [nginx default timeout is 60 seconds ](https://ubiq.co/tech-blog/increase-request-timeout-nginx)anyway, so this didn't seem to be the cause of the 502.

```
nginx.ingress.kubernetes.io/proxy-send-timeout
nginx.ingress.kubernetes.io/proxy-read-timeout
```

Additionally, in the nginx ingress controller log, we find the following:

```
2021/08/31 04:31:59 [error] 5814#5814: ***4014976 upstream prematurely closed connection** while reading response header from upstream, client: 172.68.6.37, server: languageforge.org, request: "POST /api/sf HTTP/1.1", **upstream: "http://10.42.1.34:80/api/sf",** host: "languageforge.org", referrer: "https://languageforge.org/app/lexicon/612dab37ba3db65ba56eba46/" 
172.68.6.37 - - [31/Aug/2021:04:31:59 +0000] "POST /api/sf HTTP/1.1" **502** 552 "https://languageforge.org/app/lexicon/612dab37ba3db65ba56eba46/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.78" 109760 19.205 [languageforge-app-80] [] 10.42.1.34:80 0 19.052 502 0be90a282d1af638e339b16066643e9a 
```

I bolded parts of the section above, since the nginx error indicates that **upstream** has closed the connection, not nginx itself.  The second line shows the 502 status code that nginx returns.

So now we are left looking at the application container itself, and specifically PHP.  @rmunn noticed that the project we tested with has a hefty configuration structure that takes a long time to persist in the DB.  @rmunn suspects this is due to the projects anthropological categories.  We could potentially get around this issue by optimizing the save configuration routine.

## PHP Investigation ##

So far, we've looked at the `max_execution_time` which in the production php.ini is set to 30 seconds.  This corresponds roughly to the amount of time that passes before we encounter the 502.  We were able to change the max_execution_time to be 60 inside the running container and verified that it was set using phpinfo() however, we could still reproduce the 502 error.  Additionally, we assume that if a max_execution_time was occurring, that we would see some PHP error being output to the container.  We checked, and PHP errors in the docker container should be logging to stdout/stderr.  We could find no such error.  So it sort of seems like the application is simply dying with no error or warning.  This could potentially point to a resource constrain, however Tim E reports OOM messages that he can find.

So at this point we don't know exactly what is causing this or how to fix it.

I took the time to compare the old VM php.ini to the docker php.ini and could not find any differences that would cause something like this.

We decided that since this probably only affects a few projects, we would create a card for it and try to deal with it as a separate task apart from the migration.

**Comment by longrunningprocess** [comment]
I have **not** been able to reproduce this locally.

**Comment by longrunningprocess** [comment]
while this issue is all about investigating the cause and #1162 is about absorbing some noise form the user, I'd like to link them just in case there's any overlap during the work on either.
