### ISSUE TITLE
parameterize volume sizes since they should be different in staging and prod

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1110]
assets send/receive db
staging 7 10 3
prod 10 35 10

**Comment by longrunningprocess** [comment]
there's an argument against the idea of an env further diverging from the prod...we should be striving for as much affinity as possible.  Thx @palmtreefrb

**Comment by megahirt** [comment]
Closing as "not planned".  Feel free to re-open if you think this should be a priority @longrunningprocess

**Comment by longrunningprocess** [comment]
absolutely, good call!
