### ISSUE TITLE
Eliminate white bar(s) on mobile

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1111]
When editing entries on mobile (PWA for Android), a white bar or two appears above the keyboard, blocking the view. See screen recording: https://user-images.githubusercontent.com/82162128/131802446-81f3b5ea-1bfe-42ae-9fd8-ce25f067001c.mp4

I've reproduced this on two different entries on two different days.

Thanks!

**Comment by alex-larkin** [comment]
Just noticed what might be a horizontal scroll bar when doing vertical scrolling. See attached screen recording.

https://user-images.githubusercontent.com/82162128/131810824-0f076e95-e5cd-4460-9975-ee4eb9b6bc8c.mp4

**Comment by megahirt** [comment]
Hi @palmtreefrb , as best as I can tell this problem appeared when we shipped v1.8 and has to do with the CSS changes you made in #1009 specifically the [`.container-scroll` class that you added](https://github.com/sillsdev/web-languageforge/pull/1009/files#diff-9a04a29df84348c7f672e1f52fa8888db2a1526d1166fb1380b4dc94d2c19b6e).  This works great on desktop, but it looks like the mobile viewport has a large whitespace that reduces the usable application space, most prominent when the mobile keyboard is up.

This is a regression in v1.8 and so the fix and PR should be against the staging branch, not develop.  Thanks!

@alex-larkin has posted two videos which demonstrate the white space on mobile.  I can also easily see it by resizing my desktop browser area down to a mobile size.

**Comment by megahirt** [comment]
Some screenshots from my desktop browser:

![image](https://user-images.githubusercontent.com/3444521/132275647-35d054a3-2f84-4f10-875e-c55e9850cbaf.png)

![image](https://user-images.githubusercontent.com/3444521/132275700-685ba40b-6db3-4daa-b678-a5748c941b5f.png)

**Comment by megahirt** [comment]
The actual desired behavior is for both of these panes, the list and the entry panes, to extend all the way to the footer across all viewports.  We don't want any white space at the bottom between the pane and the footer.  Vertical space is too precious.

**Comment by palmtreefrb** [comment]
Guess I need to find another mobile emulator. Don't see that white space with the Chrome plug in.

![Screenshot from 2021-09-08 20-03-04](https://user-images.githubusercontent.com/7799495/132615677-a9746d51-a733-4a20-910d-360b9bb05c12.png)

**Comment by megahirt** [comment]
Which chrome plugin / emulator are you using?  I'd like to try it to repro
what you are seeing.

**Comment by palmtreefrb** [comment]
This is the extension...
https://chrome.google.com/webstore/detail/mobile-simulator/ckejmhbmlajgoklhgbapkiccekfoccmk
