### ISSUE TITLE
Hide top entry paragraph while keyboard visible on small mobile devices

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1112]
When editing a long entry on mobile, the top portion of the page that shows all of the entry's data takes up a disportionate amount of screen space, making it difficult to see what the user is editing.

I would recommend hiding that part of the page when the keyboard pops into view, on small mobile devices. 

See the attached screen recording:

https://user-images.githubusercontent.com/82162128/131802828-3f8285c3-a8b2-47c8-9877-2de752c8a172.mp4

Thanks!

**Comment by alex-larkin** [comment]
Also some of those 502 errors you guys are taking about show up in the recording.

**Comment by alex-larkin** [comment]
> The only other possibility I can imagine would be related to the PWA already being installed and somehow not getting the update

In a quick troubleshooting call with Billy, this was determined to be the issue. Reinstalling the app eliminated the problem. 

> before uninstalling, could you look at the site in your browser on your phone and report back what you see?

My apologies for not remembering to try this. But if my memory is correct, when I have tried to go to languageforge.org in my browser, it automatically opens the PWA. Although, I could have also tried a different browser, I guess. 

I'm closing this issue and opening a new one on updates in PWA-installed apps.

Thanks guys!

**Comment by longrunningprocess** [comment]
sounds good Alex, I'll close then.
