### ISSUE TITLE
Disable initial capital letter for some fields

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1113]
Some fields should not have the first letter capitalized. Tell the keyboard to not auto capitalize the first letter for the following fields:

[ ] Word
[ ] Citation form
[ ] Pronunciation
[ ] Tone
[ ] Etymology
[ ] Etymology gloss
[ ] Gloss
[ ] Restrictions

This field should be all caps:
[ ] CV Pattern

Thanks!

**Comment by megahirt** [comment]
Alex - I assume you are talking about a mobile keyboard where it
automatically capitalizes the first letter of what you typed?  This would
only be applicable to a mobile keyboard, not anyone using desktop, correct?

**Comment by alex-larkin** [comment]
Yes, I believe so! Although I'm not sure if Chromium or other browsers auto-capitalize like Word. If so, we wouldn't want them to do that either, for the aformentioned fields.

**Comment by alex-larkin** [comment]
(Certainly if a user presses Shift, we want to respect that!)

**Comment by megahirt** [comment]
For iOS, here is a SO with a discussion:
https://stackoverflow.com/questions/5171764/how-do-you-turn-off-auto-capitalisation-in-html-form-fields-in-ios/5171812

**Comment by megahirt** [comment]
This article is newer and explains a cross-platform solution for iOS and Android.

Based on this article, I recommend the implementation be
```
<textarea autocapitalize="none"></textarea>
```

For all field inputs except Note and Example sentences.  Any other fields @alex-larkin that you think should have autocapitalize set to the default?  Note that this is keyboard dependent and is simply a _browser hint_.  It's up to the keyboard to take the hint and change behavior.  The keyboard you are using may not honor this setting in which case there's not much we can do except recommend a different keyboard :)

**Comment by alex-larkin** [comment]
Great resource! 

After looking at some published dictionaries in some languages, I see that some use initial caps in the definitions, and others don't. Let's disable auto-capitalize there, and users that want it can do it manually.

Fields I think should be capitalized:
- [ ] Note fields
- [ ] Example Sentantes
- [ ] Bibliography fields
- [ ] Scientific name
- [ ] Reference

Let's leave the rest lower case then.

**Comment by alex-larkin** [comment]
Something else I just thought of: I think that the search bar should also not auto-capitalize words.

**Comment by megahirt** [comment]
@longrunningprocess I think this would be a good first issue to get you into the code base.  Happy to talk through it more at a convenient time.

**Comment by longrunningprocess** [comment]
> @longrunningprocess I think this would be a good first issue to get you into the code base. Happy to talk through it more at a convenient time.

yep, sound like it, thanks!  I need to get through https://github.com/sillsdev/web-languageforge/issues/1137 and then (possibly) https://github.com/sillsdev/web-languageforge/issues/1117 before I can start unless you want to reprioritize #1117 .

**Comment by longrunningprocess** [comment]
ugh...I think I'll need to address #1152 first since those are actually breaking `make dev` 🙄

**Comment by palmtreefrb** [comment]
Angularjs template binding might be a solution...
[https://docs.angularjs.org/api/ng/filter/uppercase](https://docs.angularjs.org/api/ng/filter/uppercase)
[https://docs.angularjs.org/api/ng/filter/lowercase](https://docs.angularjs.org/api/ng/filter/lowercase)

**Comment by megahirt** [comment]
Thanks for the links, Rick.  This card is about letting the application
know the intention of the field (no first letter capital) however we don't
want to prevent the user from inputting capital letters if that's what they
actually want.

>

**Comment by longrunningprocess** [comment]
good news/bad news...

reference:  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

# the Good
I tested the following on my Android using the Chrome browser and got what we need from the different settings:
- `autocapitalize=off` puts the keyboard in lowercase mode 🎉 
- `autocapitalize=characters` puts the keyboard in all caps mode 🎉 
- `autocapitalize=sentences` is the default and puts the keyboard in a mode that only capitalizes the first letter of each sentence

# the Bad
Since we want to target certain fields with certain "hints", we'll need to add that piece of data to each field in the app somewhere and utilize it in `textarea` within the "Editor", e.g., "Word" gets `off`, "CV Pattern" gets `characters`, "Note fields" gets `sentences`, etc.  

# Next steps
I'll need to gain a deeper understanding of these types of field "properties" so I can determine if this is something that belongs in the database, backend models, frontend models or if it's something new we need to implement in the frontend codebase.

**Comment by megahirt** [comment]
@longrunningprocess take a look at [LexConfig.php](https://github.com/sillsdev/web-languageforge/blob/develop/src/Api/Model/Languageforge/Lexicon/Config/LexConfig.php#L23) for a list of valid `fieldName` values.

**Comment by longrunningprocess** [comment]
Excellent, thank you

**Comment by longrunningprocess** [comment]
- [ ] @alex-larkin agrees with the following categorization:

## `autocapitalize=off`

All other fields

## `autocapitalize=characters`

CV Pattern

## `autocapitalize=sentence`

Note fields
Example Sentences
Bibliography fields
Scientific name
Reference

**Comment by longrunningprocess** [comment]
What about "Etymology Comment"?  Seems like another one that should be `autocapitalize=sentence` to me, is that right @alex-larkin?

**Comment by alex-larkin** [comment]
Ah yes, you're right. Good catch! 😃

**Comment by megahirt** [comment]
Regarding cvPattern, one could argue that there are a small set of characters which are valid in this field.  Right now no validation is going on so any characters could be typed.  So it's not just capitalization.  It should probably have a different input method / keyboard entirely.  This should be a different card however.

**Comment by megahirt** [comment]
Per our conversation after standup, as with many things, there are multiple
ways to implement this.  It can be done entirely client-side, and I would
prefer client-side implementations where possible now.  This also lets you
avoid PHP changes.

**Comment by longrunningprocess** [comment]
> Regarding cvPattern, one could argue that there are a small set of characters which are valid in this field. Right now no validation is going on so any characters could be typed. So it's not just capitalization. It should probably have a different input method / keyboard entirely. This should be a different card however.

good idea, I've added a note:  https://github.com/sillsdev/web-languageforge/projects/2#card-69013808

**Comment by longrunningprocess** [comment]
> Per our conversation after standup, as with many things, there are multiple ways to implement this. It can be done entirely client-side, and I would prefer client-side implementations where possible now. This also lets you avoid PHP changes.

agreed, seems the maintenance trade-off should be minimal.  Thanks for the advice.

**Comment by alex-larkin** [comment]
> Regarding cvPattern, one could argue that there are a small set of characters which are valid in this field. Right now no validation is going on so any characters could be typed...

That could be an option, however users don't always use fields for their intended purpose, or they record data in a way that isn't traditionally recorded. (E.g., maybe in a language/writing system they use different abbreviations for consonant and vowel.)

For example, in my database, I have placed valency information (similar to "transitive / intransitive") in the tone field. 

In this issue we are suggesting how users enter data. However, if we introduce (hard) validation, that could create issues for some users.

My two cents. 😃

Thanks! This is good discussion.
