### ISSUE TITLE
feat: ignore diacritics as new default search behavior; add "match diacritics" search option for "exact match"

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1114]
Consider enabling approximate string matching when doing word searches, as in DAB.

https://user-images.githubusercontent.com/82162128/131817635-293f5f03-093b-4839-9e74-bc8b92a8ef9b.mp4

https://user-images.githubusercontent.com/82162128/131817667-d000bcd4-bfd2-443b-af3f-881f197eeaf7.mp4

This would be a very helpful feature, as the primary LF user is most likely still learning how to write in his language.

(Note: I like how DAB gives the option of matching diacritics, and that it is disabled be default. This is helpful because sometimes there can be two or more words that are only differencible by their diacritics. (Example in Panao Quechua: ćhaqui vs chaqui.) Adding this search option to LF I think is a separate decision from adding approximate string matching. We need to assess if the complication it adds to the GUI is worth it. My hunch of to not add the option.)

Thanks!

**Comment by megahirt** [comment]
This looks like a good fuzzy search library to investigate: https://github.com/farzher/fuzzysort

**Comment by longrunningprocess** [comment]
yes, the stuff you're bringing up in this last comment makes me think more of search capabilities, e.g., I want to search within certain fields, I want to search by exact word, I want to add multiple search criteria, I want to exclude/include diacritics, etc...

Narrowing things down by use case could help drive out the full capability.

Maybe our continued conversation here will help drive out individual issues that are more targeted.  For example, should we create an issue that would narrow the current search to only search those fields that would reflect a highlighted portion in the results?

**Comment by longrunningprocess** [comment]
# Should we provide a more powerful search capability?

Upgrading our search capability to include advanced features like, "exact word" or "most relevant", is certainly possible but would need to consider the impact to the UI for additional widgets that might take up precious space on a mobile user's screen.

**Comment by megahirt** [comment]
I asked the FLEx team about their algorithm for searching without diacritics and this is what @jasonleenaylor replied, which was really helpful:
>Roughly it looks like this:
Use Icu to Normalize both the find text and the target text to the decomposed form. (So the diacritics are split from the character they apply to)
Search for the first character in your find text. If it is found in the target consume any following diacritics. Then look for the next character in your find text. Repeat.

**Comment by megahirt** [comment]
We try and implement this in a similar way, both algorithmically and UX as
the other existing tools that have already implemented this, eg. DAB and
Flex.  Possibly also webonary.

Kind regards,

Chris

**Comment by megahirt** [comment]
Just to clarify, the "match diacritics" option is the current existing functionality.  This issue is about changing the default search behavior to ignore diacritics and then providing an option to "match diacritics" (the current code path doing an exact string match)

**Comment by longrunningprocess** [comment]
# Current behavior

`yacha`

![image](https://user-images.githubusercontent.com/4412848/140769748-c5d7f982-9352-4303-86d6-c29f53d5004d.png)

`yaćhä`

![image](https://user-images.githubusercontent.com/4412848/140769979-a9ebb8a6-79b1-4df8-9d40-cb5c7a7a8bf5.png)

# Desired behavior

`yacha` should result in all three matches above.

**Comment by alex-larkin** [comment]
Looks good! 

What if in the Advanced options, there is "Match diacritics" which is unchecked by default? 

DAB has a checkbox that is unchecked by default which says "accents and tones". Checking it makes it match diacritics. 

Speaking of which, I hadn't thought about tone markers. [Here is a Wikipedia article section on how tone is often marked in writing systems.](https://en.wikipedia.org/wiki/Tone_(linguistics)#Phonetic_notation) Does your current implementation take care of tone as well? 

If making search tone-agnostic is going to be a lot of work, maybe we would wait until the feature is requested and then make a separate issue for that.

**Comment by alex-larkin** [comment]
Here are two good sets for testing. (In linguistics two words that differ by only one similar sound is known as a "minimal pair." It proves that the two sounds are perceived as being different in the speaker's language, and that they should have separate representations in the writing system 🤓.) 

chacä chaca
ćhaqui chaqui

Thanks!

**Comment by longrunningprocess** [comment]
Excellent idea, much better UX!  Thank you.

# Current behavior

`chacä` 

![image](https://user-images.githubusercontent.com/4412848/140775516-5ee21939-d8f4-4457-852d-158c6262d4b6.png)

`chaca`

![image](https://user-images.githubusercontent.com/4412848/140775593-fb5d30c1-2af7-4369-ab75-a01fa8bc8d4d.png)

# Desired behavior
`chacä` or `chaca` should result in all of the matches above combined. Additionally, there should be a checkbox in the "Advanced" options area that would say "Match diacritics" that is unchecked by default. Checking that box would result in the current behavior's results.

**Comment by megahirt** [comment]
yes, I agree with the design decision to have "match diacritics" unchecked by default, keeping with DAB UI.
