### ISSUE TITLE
Auto-fill Word field after failed search

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1115]
Sometimes a user will search for a word, only to realize that it hasn't yet been added to the dictionary. Then he will want to create a new entry for that word. 

I explain my idea in this use case:

1. User searches for a word.
2. No results are found.
3. User hits "+" to add the new word.
4. Since there were 0 results when the user hit "+", LF copies the search query and auto-fills it into the word field for the new entry.

This would save a little bit of time and add some convenience.

https://user-images.githubusercontent.com/82162128/131823536-07ee65b2-7438-4d04-8632-3bc1900b13d4.mp4

Thanks!

**Comment by megahirt** [comment]
This is a very interesting and neat idea!  Thanks for sharing this.

**Comment by alex-larkin** [comment]
Ah, you make an interesting point! The user may have searched for a term in a language of wider communication. However, in that case, I think the probibility of the user clicking on the "+" is somewhat less. The user can always backspace too if needed. 

I was thinking this highlighted field would be filled. It's called the Word field in the LF GUI:

![20210903_071231.jpg](https://user-images.githubusercontent.com/82162128/132003344-91e0f596-2058-4907-bd2f-0b86e91332ee.jpg)

Toolbox had a similar feature. If your search came up blank, it asked you if you wanted to make a new entry with that search query. But the feature wasn't implemented well, and it was really easy to accidently make a new entry when you didn't want to, and maybe not even realize that you did. Databases would accumulate fake entries where the only field with data was the lexeme ("word") field.

If we implement this idea, we might want to also create a check. If a user navigates away from a new entry and the Word field is the only field with data, LF could show a pop-up that says something like, "Did you really mean to make a new entry called `term`?" With the options being "Yes" and "No, delete entry `term`". 

I think that this check could be good to apply anytime a new entry is created- not  just after the Word field is autopopulated.

Thoughts?
