### ISSUE TITLE
"X" sometimes hidden after saving comment

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1116]
The comment bar sometimes ends up a bit scrolled down after saving a comment, hiding the header and the "X" button. The user must realize he needs the scroll up in order to find the "X" button.  

This happens even when there is plenty of space in the comment bar and no need for scrolling.

![Screenshot_20210902-050407_Chrome.jpg](https://user-images.githubusercontent.com/82162128/131825546-5be4b690-54d8-4078-9818-2a0421115799.jpg)

![Screenshot_20210902-050415_Chrome.jpg](https://user-images.githubusercontent.com/82162128/131825579-d8c0b98e-7147-4cdb-b9af-3bb8310d9839.jpg)

(I am aware that the user can also tap anywhere in the gray area on the left- that is a good feature.)

Thanks!

**Comment by megahirt** [comment]
@alex-larkin can you provide more specific repro steps for us to see this bug locally?  Thanks so much!
