### ISSUE TITLE
run docker scan and triage results into future issues

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1117]

**Comment by longrunningprocess** [comment]
ran into an issue building the ui image locally...it's probably related to my new M1, I need to troubleshoot a missing python warning in the build.

**Comment by megahirt** [comment]
Per our standup discussion, this is likely due to node-sass not being able to download a binary for the ARM m1 architecture, so it falls back to building with node-gyp, python, etc.  Those build tools are missing from our image, which is why the build fails.  On x86 node-sass has pre-built binaries that can simply be downloaded, so no build tools are required.

The best way forward is to replace `node-sass` with `sass` (Dart Sass) in our development chain, as Dart sass should be architecture independent.  I've created #1137 to replace `node-sass` with `sass`
