### ISSUE TITLE
We need a way to interact with LF users in a private way.  Research and Explore this idea.

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1120]
Email is the simplest way to facilitate intakes, bug reports, user support.  It can become cumbersome when trying to involve multiple people.  It provides some level of privacy, so that's good.  It's hard to keep email organized, especially among multiple people.

**Comment by alex-larkin** [comment]
Maybe I missed the answer to this during standup, but would email be a good option? What are the pros and cons?

**Comment by megahirt** [comment]
cons of email:
- no user trail or single place to see a conversation go from intact to investigation to completion of issue.
- no direct connection with cards ( I cannot link to an email from Github)

**Comment by megahirt** [comment]
Closing this as I've decided to use email at the time being and be the triage person for new issues created.  This will potentially need to change in the future if the number of issues created via email increases over time.
