### ISSUE TITLE
verify these `mail` values are correct for prod https://control.languagetechnology.org/p/c-pr8h2:p-rvzml/secrets/languageforge:mail

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1121]
confirm with LTOps that it's ok to use the same user/token combination for staging AND production.
AI:  request a separate prod user (from LTOps)

**Comment by megahirt** [comment]
@longrunningprocess is this something you still want to pursue?  If not, please close.  Things seem to be working fine from my perspective.

**Comment by longrunningprocess** [comment]
nope, these are good, thanks
