### ISSUE TITLE
verify the `oauth` values are correct for prod:  https://control.languagetechnology.org/p/c-pr8h2:p-rvzml/secrets/languageforge:oauth

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1122]

**Comment by megahirt** [comment]
@longrunningprocess is this something you still want to pursue?  If not, please close.  Things seem to be working fine from my perspective.

**Comment by longrunningprocess** [comment]
nope, these are done now, thanks for the heads-up!
