### ISSUE TITLE
Variants and sense information

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#113]
The way LF handles variants could use some improvement.
1. Often variants have no sense information associated with them. Right now, a variant that has no sense information shows a meaning block in LF that has no data in it. I think it would be better if the whole sense block was not there. This is similar to what it looks like in FLEx. When there is a block that has blank information, it feels like one should add information there. Usually we don't want sense information entered because all the sense information is contained in the main entry that the variant is linked to.
2. There is no indication that an entry is a variant. It would be very helpful to indicate that the entry is a variant. Otherwise one wonders why there is no sense information for the word.
3. It would be very nice to show which entry the variant is linked to. This could be read-only. Also it would be nice to display the variant type as read-only information. With these two important pieces of information, the user knows why the entry is there. E.g. took -> take (past variant)

In the long-term it would of course be nice to be able to create variants and link them to main entries, but I realize that is probably a lot of work. For now, it seems like the above suggestions would not be a huge effort and could be really helpful to the user.

Thanks,
Ron

**Comment by megahirt** [comment]
@rmlockwood thanks for this.  There are several tasks / fixes in your email, so I think we'll need to split these up into separate issues.  @irahopkinson can you help facilitate splitting up issues and getting more information?

**Comment by irahopkinson** [comment]
Language Forge doesn't currently know that an entry is a variant (or sub-entry); everything is a standard entry. So making Language Forge aware of variants would be the first step.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-29, https://jira.sil.org/browse/LF-30, https://jira.sil.org/browse/LF-31
