### ISSUE TITLE
Keep selected term visible on word list

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1130]
When a user searches for a word, clicks on it, and clears the search query, the list on the left goes back to the very top.  This is not useful for navigating to other entries near the word in question. This is important for those who want to browse in a certain part of the dictionary, but don't want to scroll from the top. 

Demonstration on desktop:
https://user-images.githubusercontent.com/82162128/132067253-45c79b95-db9e-47f8-a0aa-5fe1431d464d.mp4

Demonstration on mobile:
https://user-images.githubusercontent.com/82162128/132068982-fcf42d23-339f-4455-b6a8-cd9b4df5515c.mp4

The current behavior is:
1. user searches for term
2. user selects term
3. user hits the "X" (or back arrow on mobile)
**4. The list of entries goes back to the very top**

The desired behavior is:
1. user searches for term
2. user selects term
3. user hits the "X" (or back arrow on mobile)
**4. the entry that the user selected stays exactly in the same position as it was in step 2. The words that are before and after it alphabetically show up above and below it.** 

So in my desktop example above, this is what I would expect to see after hitting the X: 
![image](https://user-images.githubusercontent.com/82162128/132069892-950d720d-8e08-4378-be5e-4ab4b1ba6495.png)

**Comment by megahirt** [comment]
I have a feeling that this can be fixed with a working and robust `scrollListToEntry(id: string)`
