### ISSUE TITLE
Infinite scrolling not working on some mobile browsers

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1131]
Infinite scrolling of the entries is not working on some mobile browsers.

For my project, these are the last terms I could access on various phone browsers:
Chrome  89.0.4389.90 (PWA) for Android 10: acaz
Samsung Internet 15.0.2.47 for Android 10: ancuy-ancuy
Firefox 91.4.0 for Android 10: ancuy-ancuy
Chrome  92.0.4515.166 for Android 7: ancuy-ancuy
Samsung Internet 15.0.2.47 for Android 7: ancuy-ancuy

However, infinite scrolling worked on Chrome and Safari on my ancient iPad Mini 2. 

Example:
https://user-images.githubusercontent.com/82162128/132071860-2b05baf8-70f6-4542-bb4b-2a4d85f0fb3c.mp4

**Comment by megahirt** [comment]
oh wow - this looks really broken.  thanks for reporting this.
