### ISSUE TITLE
Share with Others- Alert if user clicks "Done" before sending invite email

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1132]
(copied from https://jira.sil.org/browse/LF-552. Also included is a printscreen of some dialogue from JIRA.)

Today when I wanted to add my personal account to my project, I filled in the email address and considered which permission level to give, but I missed the paper airplane button. I clicked "Done," and waited for the email to come to my inbox. Later I realized that I had to click the paper airplane first. 

I suggest that when the user clicks "Done", that the app checks if there is any text in the email address text field. If there is text, ask the user, "Do you want to invite [thisemailaddress@gmail.com] as a *Commenter*?" If the user clicks "Yes", the invite is sent, the user is shown a confirmation, and the Share with Others window closes. If the user clicks "No", the Share with Others window simply closes. 

If possible, it would be great to include the paper airplane icon in the Yes button, to help associate the two in the user's mind. 

![SmartSelect_20210903-190831_Gallery.jpg](https://user-images.githubusercontent.com/82162128/132075784-006a6952-d23f-4922-ba91-e98071398670.jpg)

![Screenshot_20210903-190431_Jira.jpg](https://user-images.githubusercontent.com/82162128/132075730-0432b73e-1319-4d19-9382-a73b47487a3f.jpg)

**Comment by longrunningprocess** [comment]
To further simplify this I'd suggest we remove the airplane button altogether and, in line with previous suggestions, we change the button to "Send (plane icon)"

**Comment by longrunningprocess** [comment]
Additionally, I don't follow the second section's purpose..."Who has access".  As I see it the user is faced with determining how to invite a user and what permissions the invitee should have.  I don't understand how knowing those who currently have access plays into the use case here.

**Comment by longrunningprocess** [comment]
and what do we make of this situation?
![image](https://user-images.githubusercontent.com/4412848/135897620-99c0cd35-3571-4d42-8fbe-36f411d985ea.png)

invitee@example.org can edit but anyone who comes in with the magic link can only view?

There is an "or" so I would assume the user should only be able to choose one or the other...

I say all this because in my mind I'm thinking we could eliminate the magic link altogether, eliminate the "Who has access" as well in the name of simplifying the whole notion of how we share.

**Comment by alex-larkin** [comment]
Good idea on going back to the fundamentals. 

This dialogue box makes me think of how Google handles document sharing. When you click on the option to share, you can invite specific people, share a link, and see who already has access, and modify their permissions if needed. For managing previously-granted access, I think it makes sense for people to have that section there. If we remove it from there, then we need to add another button to LF somewhere that gives users access to manage who has access. 

I think if we emulate how Google does sharing, it would work well. 

Although I can't think of much of a use case for a permanent link by which anyone could edit a project. View, _maybe_. Comment, _maybe_. 

Thoughts?

**Comment by longrunningprocess** [comment]
I think replicating Google's sharing approach for this _seems_ like overkill... I'm hoping to get a better understanding of the use case at tonight's stand-up.

**Comment by megahirt** [comment]
@longrunningprocess after discussing this in our standup, this card needs more definition, and I apologize I wasn't able to get to this today.  I hope to tomorrow.  Thanks for your patience.

**Comment by longrunningprocess** [comment]
no worries @megahirt , you're trying to do the work of three people!  I'll just go with our last iteration of discussion from the stand-up.

# Use cases
1.  The user will have clicked on the "(icon) Share" button if they want to perform any of the following functions

## Share via email
1. User enters the email of an invitee
1. User chooses appropriate permissions
1. User clicks "(icon) Send" button
1. Dialog closes
1. A notification is presented to user "An invitation email has been sent"

Note:  I haven't yet thought through the UX if the backend call fails when the user clicks "Send".

## Share via link
1. User chooses the appropriate permission
1. The unique url is generated and displayed to the user
1. User clicks "(icon) Copy to clipboard"
1. Dialog closes
1. A notification is presented to user "An invitation link has been copied to your clipboard"

Note:  I haven't yet thought through the UX if the backend call fails when the user clicks "Copy to clipboard".

## Manage current user permissions
1. User chooses the appropriate permission(s) for an existing user or many users
1. User clicks the "x" or clicks away from the dialog to close it
1. A notification is presented to user "Member permissions have been updated"

Note:  I haven't yet thought through the UX if the backend call fails when the user changes a member's permissions.

**Comment by alex-larkin** [comment]
Ah yes, I missed that! Sorry =D
