### ISSUE TITLE
scrollListToEntry() isn't working reliably

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1133]
In [`editor.component.ts` there is a private function called `scrollListToEntry()`](https://github.com/sillsdev/web-languageforge/blob/9f6519e93d9617f10cc9f689fa32f6bb0dddf603/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L1158) that isnt' working as intended.  The purpose of the method is to scroll the item list so that the selected entry is visible.  A selected entry can easily scroll off the list or become not visible at all whenever searches are finished, are cleared, or whenever new entries are added (either by the user or by others).  This method should reliably manipulate the scrollable area so that the highlighted entry is always in view after the method returns.

This method is implemented in a certain way, however there may be a simpler way to implement this using more modern CSS tricks.  I am not sure.  My recommendation is to understand what this and its calling methods do, and then rewrite the method from scratch.  This may be the best way to make it more reliable than it currently is.

This method is complicated by the infinite scrolling feature whereby the list does not actually contain all items of the dictionary at startup. So it must "loadMoreEntries()" until the entry has been loaded into the list for it to be scrollable.

The main work of scrollListToEntry() is done in [scrollDivToId()](https://github.com/sillsdev/web-languageforge/blob/9f6519e93d9617f10cc9f689fa32f6bb0dddf603/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L1158).

Having a reliable scrollListToEntry() should fix #1130 and also #1014 

There is also the possibility that we can make this method simpler if the research in #1127 proves that we can simply load all entries for most dictionaries.

**Comment by rmunn** [comment]
One thing that's almost certainly wrong in the scrollListToEntry() logic is this line:

```js
const posOffset = (position === 'top') ? 274 : 487;
```

Those "magic numbers" have not been changed in over three years, so they're almost certainly out of date. And as Chris says, this is not the right approach in the first place.

I don't have suggestions to offer; I just found this while working on #1051 and looking at nearby code. So I'm jotting this note down before I forget it, to help whoever ends up working on this.

**Comment by rmunn** [comment]
Two things I thought of as we were discussing this issue today:

* There should be a button (or icon) in the UI that lets the user bring the current entry back into the middle of the scroll view. In other words, a button or icon that calls `scrollListToEntry()`.
* #1127 discusses whether we should have the list loaded at all times. My thought is that the list should always have the right number of entries in it — 5,466 entries in the project we looked at during the meeting — but that most of them should be `null` initially. Then the `loadMoreEntries()` function won't expand the list, but will *populate* sections of the list. You could use the [Intersection Observer APIs](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) on placeholder divs to see when they scroll into view, and have that trigger `loadMoreEntries()` to populate that part of the list. Then the scrollbar will always be reliable and always show the right relative position of the entry, but you won't spend memory on storing entry data that isn't yet in view.
    * For bonus UX points, the observer API events could be debounced by 250 milliseconds or so before using them to load more entries. That way if the user grabs the scrollbar and drags it all the way to the bottom, it won't trigger loading every single entry as it scrolls past, but will only trigger loading the bottom entries once the user releases the scrollbar.
    * I'm picturing `loadMoreEntries()` as loading a "chunk" of entries, maybe 50 or so, at once. The precise indices to be loaded could be the chunk of 50 that contains the div that triggered the load. E.g. if the load was triggered by index 49, it would load positions 0-49. If it was triggered by index 50, it would load positions 50-99.

**Comment by longrunningprocess** [comment]
thanks for the [virtual pairing](https://www.youtube.com/watch?v=h1f9_mIMQ_U) @megahirt .  Here some things I pulled out:

# Use cases

## Page refresh on a specific entry should scroll to that element ([t1:44](https://youtu.be/h1f9_mIMQ_U?t=104))
1. Got to a specific entry in the list, preferably even one toward the bottom of the visible entries or even below
1. Once the page renders, the entry referenced by id in the URL should be highlighted and scrolled to the middle of the list

- [ ] the scrolling should bring the entry to the vertical middle of the list container

**Comment by longrunningprocess** [comment]
One missing situations that should have further discussion is when a user scrolls the list away from the highlighted entry and for some reason doesn't select a new entry... 

That's a possible use case that _might_ warrant another button that will re-sync the highlighted entry to the current selected entry.  Is this truly a use case we think exists enough that it would warrant more user controls?

**Comment by megahirt** [comment]
Additional Use Case
- Using <kbrd>Prev</kbrd> and <kbrd>Next</kbrd> buttons or <kbrd>PgUp</kbrd> and <kbrd>PgDn</kbrd>

**Comment by longrunningprocess** [comment]
> Additional Use Case
> 
> * Using Prev and Next buttons or PgUp and PgDn

fix is in here:  https://github.com/sillsdev/web-languageforge/commit/704cb15bb2e670d216892cda6661d2494650af72

https://user-images.githubusercontent.com/4412848/143300171-51f8d970-975c-43c9-89bf-d10dea66c69e.mov
