### ISSUE TITLE
Triage/review open topics on Community Site

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1136]
For each topic still visible on https://community.software.sil.org/c/language-forge/20 we should:

- evaluate if the issue is still relevant
- ask for clarification if necessary from the topic author
- close topic if possible (issue is no longer relevant - bug has been fixed, etc)
- create new issues if the topic isn't adequately represented as a GitHub issue; link to topic
- link existing GH issues with existing community topics where possible

**Comment by alex-larkin** [comment]
Do I need to have an admin role on the site to do this? Who do I ask if I need to be assigned such a role? Thanks.

**Comment by megahirt** [comment]
@alex-larkin I gave you trust level 4 (highest level) which I assume is enough for you to moderate the Language Forge community site.  Can you check again please?

**Comment by alex-larkin** [comment]
Yea- I have all sorts of new abilities now, even on mobile! Thanks Chris!

**Comment by megahirt** [comment]
@alex-larkin , if you are satisfied with having looked through the community site to review what people have said in the past, then I am good with closing this issue.
