### ISSUE TITLE
Resizing textareas have wrong size in Firefox

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1144]
**Describe the bug**
When loading a new project in Firefox, I noticed that the newly-resizing text inputs looked wrong: they were too large vertically for their contents. Then when I clicked in them, every time I clicked in a new input the size of all text inputs shrunk by 1 pixel. Once they were the right size, they stopped shrinking.

**To Reproduce**
1. Go to a Language Forge project that already has existing data
2. Click on an entry
3. Observe the text inputs
4. If they're the wrong size, start clicking on different inputs

Pressing arrow keys also caused the inputs to shrink by 1 pixel until they became the right size.

**Expected behavior**
The textareas should start out with the correct size.

**Screenshots**

![bug-resize-textarea](https://user-images.githubusercontent.com/90762/132664003-67bdd703-dda9-4d9d-bd03-09a21fdbc7f8.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - Browser: Firefox 90.0.2

**Comment by palmtreefrb** [comment]
I have installed the latest version of Firefox and cannot reproduce...
![Peek 2021-09-09 06-22](https://user-images.githubusercontent.com/7799495/132693972-a25273c8-65c2-4a10-b39e-54ae82540605.gif)

**Comment by rmunn** [comment]
It seems like having a blank writing system is the key to triggering this issue. In my reproduction, there was data in Zapotec and Spanish but no data in English. Clicking through other entries in the same project, some of them did not show the too-large boxes, and all of those that didn't show the issue had data in all visible text fields.

So if you edit your project view settings and make 'en' or 'fr' visible for the Word field, you'll probably be able to reproduce the issue on your browser. (I was able to reproduce in both Firefox and Chromium, so it's probably not browser-specific).
