### ISSUE TITLE
Review resource utilization after a week or so and determine whether we’re right-sized or not

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1145]

**Comment by rmunn** [comment]
Today while providing on-site tech support for a Language Forge user, we observed multiple 502 errors in JSON-RPC calls, mostly from the lex_dbeDtoUpdatesOnly call. We definitely have *some* resource that's too small.

**Comment by longrunningprocess** [comment]
> Today while providing on-site tech support for a Language Forge user, we observed multiple 502 errors in JSON-RPC calls, mostly from the lex_dbeDtoUpdatesOnly call. We definitely have _some_ resource that's too small.

Thanks @rmunn , I think this would be more valuable info over in #1106.  Mind moving it over there?

**Comment by longrunningprocess** [comment]
I spent some time with LTOps today reviewing some of our reports now that we've been up and running for a while.  Our utilization across the board is pretty low, we're actually in fantastic position as far as sizing goes.  We are at the minimum instance-type LTOps will give us so we're GTG!

CPU utilization across workers averages ~25%
I/O metrics have been well below 1 UNIT, meaning we've got a ways to go before aws would upgrade/expand
Memory utilization across workers averages ~50%

@megahirt , ew are definitely right-sized, please feel free to close this issue at will.

**Comment by megahirt** [comment]
Thank you for the summary @longrunningprocess
