### ISSUE TITLE
pull together some strategy or plans for LTOps and some pen testing

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1146]

**Comment by longrunningprocess** [comment]
LTOps is continuing to attempt testing on their side.

They suggested something https://www.zaproxy.org/ for our own testing.

**Comment by megahirt** [comment]
I moved this to the backlog since we haven't made any priority decisions on when we might pursue security testing

**Comment by megahirt** [comment]
Closing as not actionable
