### ISSUE TITLE
Improve search results by prioritizing hits from key fields (e.g. lexeme, citation, gloss, definition)

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#115]
In my Swedish project, in the List view, I type the word 'tag'. This is the whole word. I don't see the word at all in the results and a lot of other words that don't seem related show up in the list. A word like 'arbeta' shows up in the results. I'm now wondering if I'm getting this result because I have a lot of entries with a custom field that contains a url and in the url is the string 'tag'. It would be nice if key fields like lexeme form, citation form, gloss, etc. would get priority for the results. It might be good if urls were ignored for searching.

**Comment by megahirt** [comment]
Good point @rmlockwood .  I've renamed this issue so we can track this.

**Comment by irahopkinson** [comment]
See also #15. Could be improved together.
