### ISSUE TITLE
Ability to "star" / "flag" / mark certain entries

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1153]
**Is your feature request related to a problem? Please describe.**
One user wanted the ability to mark certain entries, and then have a filter that would show only the marked entries. Something like the "star" feature in Gmail. Then a filter could be used to see only the starred entries, or only the unstarred ones.

**Describe the solution you'd like**
This would involve a new boolean property on entries in MongoDB, or perhaps we could plan ahead and make it a string so that we could have multiple label colors à la Trello (red, blue, green...). There would also be UI to mark or unmark ("star" or "unstar") the entry on the entry view page, and the star would show up in the entry list view on the left.

The star status would not be sent in a Send/Receive operation; this would be in Language Forge only and would not show up in FieldWorks. (Unless user feedback suggests that they want to see the star status in FieldWorks as well, in which case we'd track that work in a separate issue).

**Describe alternatives you've considered**
Comments could be used right now to implement this: we have a status on comments called "To Do", along with "Resolved" and "Unresolved". But that's at a field level, not an entry level, and there's no entry-list filter for "All entries with a "To Do" comment".

A custom field called "Status" could also be used to implement this idea, but that's also not as easy to filter for in our current entry-list implementation.

**Comment by alex-larkin** [comment]
This looks like #1008, with more detail.

If this is implemented without FLEx support, please notify the user when he starts using the feature that stars won't be visible in FLEx. 

I imagine a common reason for starring entries would be to prepare them for publication, which would generally be done via an export from FLEx. Workaround: without FLEx compatibility, I guess that the user could also manually mark the publication field, or a field custom to his project. Ensuring 100% alignment between stars and a second field would likely be difficult, though. 

What are other use cases for starring?

Thanks

https://github.com/sillsdev/web-languageforge/issues/1008

**Comment by rmunn** [comment]
This is actually a duplicate of #1008. I was looking through our user-observed issues for this one after a discussion with Chris, saw that I hadn't created a card for it, and missed Chris's #1008 because I thought that entry tagging meant something else. I'll close this one as a duplicate, and move my description into #1008 as a comment so it's easy to find.
