### ISSUE TITLE
Security Vulnerability Report

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1155]
**Describe the bug**
Here's a report outlining current app vulnerabilities:  https://docs.google.com/document/d/1ItvavFI1DCh1oaglhlQ7sF5Hv6-Hq6QiRa0hYuw3T7w

**To Reproduce**
`make scan` within the `docker` directory will produce the results.

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Mobile (please complete the following information):**
N/A

**Android App in Google Play**
N/A

**Additional context**
None

**Comment by megahirt** [comment]
This is outdated since our images have changed significantly.  Closing

**Comment by megahirt** [comment]
I reran this report today and updated the Google Doc.  Many of the vulnerabilities seem to be associated with the older PHP version images, and if we can somehow migrate to PHP 8, I think we will be in much better shape.  Who wants to tackle the upgrade to PHP 8? :)
