### ISSUE TITLE
When arriving at a project, go to most recently-viewed entry

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1161]
**Is your feature request related to a problem? Please describe.**
#1016 suggests going directly to a project on sign-in, but we have learned that it would also be good to go directly to the most-recently-used entry.

**Describe the solution you'd like**
Any time the user clicks on a project, in the projects view or the breadcrumbs or by logging in and being redirected to the project, it's a good idea to take them directly to the most-recently-used entry as well. Only when you click on the "←List" button should you actually see the entry list.

**Describe alternatives you've considered**
Not doing this and leaving the status quo.

**Additional context**
Also related: #1129.

**Comment by alex-larkin** [comment]
I like this idea! 😃

**Comment by megahirt** [comment]
I would like this implementation to be 100% client-side / AngularJS / indexdb.

Requirements:

- [ ] 100% AngularJS / Indexed DB
- [ ] handle multiple projects

Implementation suggestion
- Implement a mostRecentlyViewedEntry cache service similar to the [EditorOfflineCacheService](https://github.com/sillsdev/web-languageforge/blob/develop/src/angular-app/bellows/core/offline/editor-offline-cache.service.ts) that uses OfflineCacheService.
- will probably need to make the [getOneFromStore method](https://github.com/sillsdev/web-languageforge/blob/9f6519e93d9617f10cc9f689fa32f6bb0dddf603/src/angular-app/bellows/core/offline/offline-cache.service.ts#L34) be projectId aware just like getAllFromStore already is.
- store the entry id in the cache service on each entry view
- when loading the editor for the first time, look up the mostRecentlyViewEntry via the cache service, then go to that entry.
