### ISSUE TITLE
Don't report 502 errors to the user

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1162]
**Is your feature request related to a problem? Please describe.**
Currently our infrastructure is throwing a lot of HTTP 502 errors, which get reported to users in a yellow "Oh. RPC Error" box. But there's no action the user can take in response to a 502, and most of the time it doesn't mean there's anything wrong with their project.

**Describe the solution you'd like**
We should filter out HTTP 502 errors from the pop-up notifications, and only log them in the Javascript console (which most users will never look at).

**Describe alternatives you've considered**
We could also not log 502s in the JS console at all, but I think there's benefit to logging them in the console without showing a notification pop-up.

**Comment by rmunn** [comment]
After discussion at today's standup, we decided that we should also retry 502s a couple of times, since a 502 is likely to be a short-term failure that would succeed with a retry.

**Comment by longrunningprocess** [comment]
Looks like the to absorb the `502`, i.e., don't call the `notify` service, should be in here:  https://github.com/sillsdev/web-languageforge/blob/develop/src/angular-app/bellows/core/api/json-rpc.service.ts#L125
