### ISSUE TITLE
cvPattern validation

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1165]
Carrying on from a conversation over at https://github.com/sillsdev/web-languageforge/issues/1113#issuecomment-921544139

Regarding cvPattern, one could argue that there are a small set of characters which are valid in this field. Right now no validation is going on so any characters could be typed. So it's not just capitalization. It should probably have a different input method / keyboard entirely. This should be a different card however.

**Comment by megahirt** [comment]
copying what @alex-larkin wrote:

> Regarding cvPattern, one could argue that there are a small set of characters which are valid in this field. Right now no validation is going on so any characters could be typed...

That could be an option, however users don't always use fields for their intended purpose, or they record data in a way that isn't traditionally recorded. (E.g., maybe in a language/writing system they use different abbreviations for consonant and vowel.)

For example, in my database, I have placed valency information (similar to "transitive / intransitive") in the tone field.

In this issue we are suggesting how users enter data. However, if we introduce (hard) validation, that could create issues for some users.

My two cents. 😃

Thanks! This is good discussion.

**Comment by megahirt** [comment]
@alex-larkin this is a classic discussion about the software tool / UI enforcing users to use the tool in a certain way vs. letting the user decide how they want to use the tool, possibly in a way that the programmers hadn't thought of or intended.  This has advantages and disadvantages.

If it turns out that CV Pattern is more or less a text/note field that linguists enter data in a way they'd like to see it, then no validation is necessary.

If the data is processed in a certain way so as to take advantage of phonological parsing capabilities in FLEx or another program, then the program should expect input to be of a certain format and should be able to validate the input data.

It may be that FLEx does not validate the CV Pattern field in FLEx to confirm to any sort of data standard, in which case we should ask questions, and default to what FLEx does (no validation).  I haven't looked into it enough to understand what FLEx does and why it does or doesn't do it.

As a philosophical discussion around validation of structured data, this is why FLEx was built...to replace Toolbox.  Users are generally content to do what is right in their own eyes and for the most part were very happy (some actually *more* happy) to continue using Toolbox over FLEx because it did not prescribe or limit them in how they structured their data.  This is fine until you want to do something programmatic or transformative with the mostly-structured data.

As an anecdote, I have myself put notes alongside the telephone number in the `telephone` field in my contacts database, which works great until you want to pass that data to a program to actually call someone. :)

**Comment by alex-larkin** [comment]
That is a GREAT analogy from Toolbox! Perhaps we can ask around to find out if "C" and "V" are used by linguists globally, regardless of language and writing system. If so, then, yea, that could be a great idea. Only allow Cs, Vs, and periods for the syllable breaks, if I'm not mistaken.

If LF starts doing data validation here, I imagine it could grey out any field that already contains non-confirming characters, similar to how it presently handles fields with formatting.

As a side note, I also put notes in the "Job Title" and "Organization" fields of my contacts. They are easily visible during calls on my Android phone. 😎

**Comment by rmunn** [comment]
I've looked through the FieldWorks code and I don't see anywhere that enforces any kind of rule on the contents of CV Pattern. Users are allowed to put anything they like into that field, so I believe LF should act the same way.
