### ISSUE TITLE
Example sentence WS not properly set after initial S/R clone

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#117]
In my Swedish project for the word om [prep], I have several example sentences added for different senses. I added them in FLEx, none of these show up in LF after syncing even though translations of the example sentences do show up.

**Comment by irahopkinson** [comment]
This is a bug with it not selecting the right writing system for the **Example** (in fact it has a non-existent *th* selected). For now you can work around it by going to **Settings** (gear icon) > **Configuration**. On the **Fields** tab, click **Sentence** on the left, then on the right select the appropriate **Input Systems**.

**Comment by megahirt** [comment]
Let's rename the issue once we can isolate how the field was not properly
selected, I'm guessing on initial send/receive.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-27
