### ISSUE TITLE
App is trying to locate a js file that doesn't exist

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1170]
**Describe the bug**
I noticed in `staging` and `production` (not locally) that there are requests being made for `js/lib/languageforge.min.js` that are not found.

**To Reproduce**
1. Go to https://qa.languageforge.org or https://languageforge.org
2. Open dev tools
3. Notice the red `404` requests in the Network tab

**Expected behavior**
Resource requests the app makes should all be present

**Screenshots**
![image](https://user-images.githubusercontent.com/4412848/134568931-886a5d28-5a97-4657-a281-cae3f43cae80.png)

**Additional context**
I assume this line can be removed: https://github.com/sillsdev/web-languageforge/blob/develop/src/Site/views/shared/container/container.html.twig#L35

Additionally, I noticed while in that file that many of the assets being requested are in the "minified" block but are not actually requesting a minified version...and I'm not sure whether the minified versions are even being generated in in production/staging environments.  This is being driven by an environment variable and utilized here: https://github.com/sillsdev/web-languageforge/blob/develop/src/Site/Controller/Base.php#L28

**Comment by megahirt** [comment]
> I assume this line can be removed: https://github.com/sillsdev/web-languageforge/blob/develop/src/Site/views/shared/container/container.html.twig#L35

@longrunningprocess  Yes, deleting this line should resolve the issue - thanks for finding this!

The other dependencies specified in there - ugh - my wish list is that all dependencies are 100% managed by npm and webpack.  The ones in this file are the ones that are left out, and the reasons why are lost in the sands of time.  some tech debt that we can probably ignore in this code base.

**Comment by megahirt** [comment]
This was removed in a PR that I cannot remember now.  Closing
