### ISSUE TITLE
Upgrade Mongo to 4.2 or later

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1173]
**Is your feature request related to a problem? Please describe.**
Mongo 4.0 introduced aggregation pipelines, and Mongo 4.2 introduced the ability to pass an aggregation pipeline to a Mongo `update()` call. This led to the Mongo team declining several feature requests like https://jira.mongodb.org/browse/SERVER-4798 (pop multiple items from an array at once), because in Mongo 4.2 you can do that with an aggregation pipeline.

Some of the Language Forge code (such as the code that makes entry updates into deltas, instead of replacing the entire entry at once) will occasionally need to remove multiple items from an array (for example, if someone removes two Meanings from an entry before saving the entry), and that's not possible before Mongo 4.2.

**Describe the solution you'd like**
Upgrade the Mongo container to at least Mongo 4.2, and probably the latest version of Mongo 4.x so we don't have to pay the cost of a database upgrade as often. (For thoughts on Mongo 5.0, see below). Then we'll be able to use aggregation pipelines in Mongo updates, which would allow some efficiency wins, and in some cases allow updates that wouldn't have been possible to write before. For example, at one point we were considering having a `dirtySR` flag on projects, and the Send/Receive code would decrement the flag if and only if it was greater than 0. That's not possible before Mongo 4.2, but aggregation pipelines make it possible to write that logic into a single atomic Mongo update.

**Describe alternatives you've considered**
We could stay on Mongo 4.0, and add logic that forces entry saves before adding or removing a meaning or example. That way any Mongo update will contain at most a single array push or pop.

**Additional context**
Mongo 5.0 is worth considering, but it's a bit riskier as it's a major version number and a recent change. However, looking through the Mongo 5.0 release notes, the only thing I see that could cause us issues is that the `mongo` shell command is being deprecated and replaced with `mongosh`, which is only an issue of habits (when connecting to the Mongo DB directly, got to get used to typing `mongosh` instead of `mongo`).

**Comment by megahirt** [comment]
I am all for an upgrade to MongoDB 5.0 if the E2E tests pass.  I have a high degree of confidence that the E2E tests will exercise the majority of our database use cases.  My answer would be the opposite if we were talking about upgrading PHP.  In this case, catching up to the latest MongoDB is likely an easy win.

**Comment by rmunn** [comment]
At this point [I would not recommend upgrading to MongoDB 5.0](https://www.theregister.com/2021/11/11/mongodb_51_for_dbaas_arrives/):

> The versions following 5.0 "have been problematic for users so far," she claimed, with bugs impacting through to the release of MongoDB v5.0.3 on September 21, 2021.

> Those first three releases were all labelled with the warning: "MongoDB version 5.0.0 is not recommended for production use due to critical issues..." The bugs caused issues such as duplicate unique keys, omitting a page of data, data loss, and problems restarting.

Let's stay on 4.x until at least next year.

**Comment by megahirt** [comment]
Upgrade to version 5.X if e2e tests pass

**Comment by longrunningprocess** [comment]
attempting to simply upgrade to `mongo:5` and spinning the app up against an existing db volume (filled with a 4.0 worldview) results in the following upon startup: `lf-db  | {"t":{"$date":"2022-10-07T19:07:05.132+00:00"},"s":"F",  "c":"STORAGE",  "id":4671205, "ctx":"initandlisten","msg":"This version of MongoDB is too recent to start up on the existing data files. Try MongoDB 4.2 or earlier."}`

out of interest, running unit and playwright tests against a clean 5.0 however seems ok.

**Comment by longrunningprocess** [comment]
upgrading to 5+ is going to require some intermediate steps:  https://www.mongodb.com/docs/manual/release-notes/5.0-upgrade-standalone/#upgrade-version-path

I'd recommend we open another issue taking the db to 4.4: https://www.mongodb.com/docs/manual/release-notes/4.4-upgrade-standalone/

I do that instead of in this one so we can let the app run on 4.2 for a bit first.
