### ISSUE TITLE
bug: Redirect.php PHP warning flashes upon loading LF before redirect to projects page

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1175]
**Describe the bug**
This PHP warning page appears on a local developer machine, flashing briefly before redirecting to the projects page.

**To Reproduce**
Developer reproduction steps:
1. `make clean-volumes`
2. `make`
3. Browse to https://localhost
4. See error flash briefly before redirecting to https://localhost/app/projects

The error can also be observed in the app container logs `docker-compose logs app
**Expected behavior**
This PHP warning should not be seen on production systems anyway, however this seems like a simple thing to fix.  The warning should not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/3444521/135051313-b57f0a74-b4f1-4153-8912-ba2fd6658ca6.png)

**Comment by rmunn** [comment]
This is a result of removing the useless `appName` and `projectId` parameters after the code review suggested removing them. I didn't test after removing them, so I didn't find out that they were required by the PHP type-checker, such as it is. I'll put them back and have the Redirect code do nothing with them.

**Comment by rmunn** [comment]
Created #1176 against `staging` branch. Not yet tested as I'm hard at work on the delta-updates feature, but this was a quick fix (if I'm right that #1176 fixes it, of course).

**Comment by megahirt** [comment]
> This is a result of removing the useless `appName` and `projectId` parameters after the code review suggested removing them. I didn't test after removing them, so I didn't find out that they were required by the PHP type-checker, such as it is. I'll put them back and have the Redirect code do nothing with them.

Yup - that was my bad.  This is classic inheritance in PHP that generated a runtime compiler warning.  Boo for runtime compiler warnings.

**Comment by megahirt** [comment]
fixed by #1176 and shipped in 1.9
