### ISSUE TITLE
Bad UX for PgUp/PgDn while in Editor

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1177]
**Describe the bug**
When a user is in the Editor and tries to use PgUp or PgDn to move through the entries, not only will the entry change but the Editor will also scroll a different field into view at the same time.
 
**To Reproduce**
1. Highlight an entry and place your cursor into one of the input fields
2. Press PgUp or PgDn
3. Notice the entry did change to the desired entry but the Editor also scrolls up or down too.

**Expected behavior**
The Editor view should not scroll at all when the PgUp/PgDn is pressed

**Screenshots**

https://user-images.githubusercontent.com/4412848/135315108-0ca510eb-979d-42e3-9d3c-fb2334a884ff.mov

**Additional context**
This was introduced as part of the work for #1017

**Comment by megahirt** [comment]
excellent - thank you for documenting this

**Comment by megahirt** [comment]
fixed in #1182 and shipped in 1.9
