### ISSUE TITLE
Whitespace is limiting the number of entries visible

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1179]
**Describe the bug**
When users view a project's list of entries, only one word is visible at a time.

**To Reproduce**
1. Go to a project with a handful of entries
2. Notice only one word is visible

**Expected behavior**
The list should show as many entries as possible before running into the "footer" of the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/4412848/135330978-9ce5f75b-86c0-4eb4-bfbb-0ef2fcb02b84.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Additional context**
This was most likely introduced as part of the work on https://github.com/sillsdev/web-languageforge/pull/1143 which covered a number of issues.

It looks fine on the mobile viewport only, all desktop breakpoints have this extra whitespace now.

**Comment by palmtreefrb** [comment]
This selector was inadvertently changed from `.lexiconItemListContainer` `height: 460px;` to `height: calc(100vh - 568px);` ment for another selector. It needs to be reverted back.

**Comment by megahirt** [comment]
shipped as part of v1.9
