### ISSUE TITLE
Homograph numbers

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#118]
Is it possible to show homograph numbers? It would be nice to show them as subscript numbers as in FLEx. I guess this depends on what you are going to do with the concept of 'Headword'. It doesn't look like you are displaying headwords in LF which is the citation form (if available) otherwise the lexeme form. Homograph numbers go on headwords.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-26
