### ISSUE TITLE
"My Projects" menu might need to be scrollable in some cases

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1180]
**Is your feature request related to a problem? Please describe.**
Very few people will ever encounter this, but there's no way to scroll the "My Projects" menu, so if it ever gets to the bottom of the page it's impossible to click on the last entry.

**Describe the solution you'd like**
It would be nice if the "My Projects" menu had a maximum height with `overflow-y: scroll` in its CSS.

**Describe alternatives you've considered**
Leaving it alone, since only people with absurd numbers of projects (like LF devs) will ever encounter this, and anyone who does encounter this can click on the "My Projects" breadcrumb and use the projects view. And we have lots of higher-priority issues. I'm just opening this one so we can track it if we decide it's worth doing *eventually*.

**Additional context**
Here's what it looked like on my 1920x1080 screen. There are three more projects in that menu, below the "TestLangProj-DW-FLEx", which aren't clickable. (I blurred out the names of non-test projects in case any of them are sensitive.)
![image](https://user-images.githubusercontent.com/90762/135389057-6771faf0-add7-4a24-998c-a629eea03283.png)

**Comment by megahirt** [comment]
I appreciate this report.  I agree that it's a problem, however I don't exactly know how to make the Bootstrap menu scrollable and since it only applies to administrators realistically I will close this as "won't fix".  You are free to investigate and make a quick CSS fix if that's possible - don't spend much time on it.
