### ISSUE TITLE
bug: old LF images are not being cleaned up from Docker Hub

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1193]
**Describe the bug**
We currently have no process to remove "old" images from Docker Hub

**To Reproduce**
1. Go to https://hub.docker.com/r/sillsdev/web-languageforge/tags
2. Notice all the images

**Expected behavior**
We should establish a retention policy for our images and then enforce that.  I'd suggest retaining 3 versions of the software.

**Screenshots**
N/A

**Additional context**
GHA seems like the right place to implement a job that runs regularly to find images that are "old" and remove them.

**Comment by megahirt** [comment]
Are we using the free-tier plan of dockerhub?  If so, it looks like DockerHub is putting into place a 6 month retention policy starting in November for inactive images (not pulled or pushed).  I'm actually fine with that and am happy to let DockerHub cleanup the images itself.  If we are on a pro account and have unlimited storage/retention, then we should write something.

See https://www.techradar.com/news/docker-could-be-set-to-delete-all-your-files-if-you-havent-accessed-them-for-a-while

**Comment by longrunningprocess** [comment]
I presume we are so if that's the case, we can definitely close this issue.  I'm going top presume that's the case for https://hub.docker.com/u/sillsdev for now.  I'll follow up with the admin and if I hear differently I'll come back out here and open this one back up.  Thank you for checking on that!
