### ISSUE TITLE
Gloss field not displayed

### ISSUE THREAD

**Issue by toby-1-kenobi** [sillsdev/web-languageforge#12]
In FLEx I put my analysis language glosses in the gloss field, but I cannot get this field to display in the Language Forge. I realise that WeSay defaults to putting meaning data in the definition field so perhaps Language Forge uses definition for the meaning data, I don't know, but I'm not comfortable with putting glosses in the definition field. Perhaps there should be a way to tell Language Forge to look in the gloss field for meaning data.

**Comment by megahirt** [comment]
Dear Toby,

Thanks for reporting this.  Can you take a look at this google groups post and see if that doesn't fix your problem?  We are planning to role out a fix next week or sooner to address this, but until then you can change the setting yourself manually.

https://groups.google.com/forum/#!topic/languageforge/yqK4Mu4Xw9g

Thanks,

Chris
