### ISSUE TITLE
chore: Prettier our repo

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1203]
Use Prettier as part of our standard developer experience.  This will help all of our code to be committed in a uniform style regardless of how developers write it.

Steps:
- [x] Add Prettier config file for supported file types
- [x] Add git commit hook for prettier
- [x] Add VSCode workspace extension
- [x] Coordinate with all developers to push all branches by the end of the day
- [x] Run prettier on all branches and commit
- [x] Communicate that all branches are now Prettier

**Comment by megahirt** [comment]
@myieye this is high priority for me next week while I and several other devs are gone - best time to do this is when there are few people working in the repo.

Is this enough description?  Adding the prettier extension to VSCode seems like the wrong thing since it should be transparent and part of the git commit hook I'm thinking, so maybe scratch that.

I want Prettier to run for every language in our repo that has support for Prettier.

**Comment by megahirt** [comment]
In your communication post-cleanup we will probably need instructions to help devs clean up their own unpushed branches if they weren't able to push before you run prettier.

There are currently 15 open branches, so it will take some work.

**Comment by myieye** [comment]
As discussed with @megahirt and @longrunningprocess we're going to:

1. Initially exclude all `js`, `ts`, `svelte`, `html`, `yaml` & `yml` files
2. Add ESLint in a future issue for at least `js`, `ts` and `svelte`

Then we can get a feel for what we've gained and if ESLint's formatting satisfies our needs.

If desired we can then increase prettier's scope. We think that's safer/tidier than doing too much and then discovering we want to reduce it.

**Comment by myieye** [comment]
Just ran into this bug in prettier/plugin-php:
![image](https://user-images.githubusercontent.com/12587509/196177745-0ce276fa-74f6-4c30-808a-242126b6ae33.png)

My workaround is to add a space (` `) at the beginning of those lines, then the weird placeholder doesn't get added.

I created a bug for it: https://github.com/prettier/plugin-php/issues/2087

**Comment by myieye** [comment]
> > double-quotes
> 
> I was thinking it was supposed to be single-quote but maybe that was just for js/ts?

Oh no 😆. I was/am pretty sure we agreed on double-quotes for everything. @megahirt was pretty clear that he doesn't care.  Do you have a strong opinion about this? Otherwise, I'm just going to stick with double-quotes.
