### ISSUE TITLE
feat: Implement a full infrastructure teardown during `staging` deployments

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1211]
**Is your feature request related to a problem? Please describe.**
Right now we simply apply changes to our deployment when we deploy to our staging environment.  Recently there was an outage that might have been prevented if we had been tearing our entire staging infrastructure before deploying.

**Describe the solution you'd like**
I want to make sure we delete everything in staging before deploying to it again.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by megahirt** [comment]
@longrunningprocess do you know what the status of this is?

**Comment by megahirt** [comment]
Yes, I agree, we should talk through this more.
