### ISSUE TITLE
Pasting HTML content into a field can disable the field when content contains <span> elements

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#122]
This was reported on our (now deprecated) user voice site by user Joo:

> Hi. There seems to be a problem with pasting text. When I paste text into a field, I will no longer be able to type or edit anything in the field I pasted the text to.

**Comment by irahopkinson** [comment]
Although this is now fixed in most cases, the problem of the field being locked for editing will still occur if the data contains a **span** with a language attribute, e.g. <span lang="en">
