### ISSUE TITLE
bug: `make dev` didn't work for `src/Site/views/languageforge/container/languageforge.html.twig` change

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1221]
**Describe the bug**
I made changes to `src/Site/views/languageforge/container/languageforge.html.twig`, refreshed the app but did not see my changes in the running app.  I had to re-build `app` to get my changes to show locally.

**To Reproduce**
1. `make dev`
2. Open the Help menu and notice the name of one of the menu items
3. Change one of those names in `src/Site/views/languageforge/container/languageforge.html.twig`
4. Refresh the app and noticed the change did not take effect

**Expected behavior**
Changes should've been reflected upon refresh

**Screenshots**
N/A

**Additional context**
Rebuilding `app` did eventually reflect my changes.

**Comment by longrunningprocess** [comment]
I just sort of assumed this was some kind of build-time issue, I've never looked at how twig's get turned into html...is this typically done at runtime, i.e., upon request?  If so, I guess the idea of a cache being in the mix could explain it.

**Comment by megahirt** [comment]
Closing.  The solution is to refresh the browser after updating the twig file

**Comment by longrunningprocess** [comment]
does a simple refresh still hold true here @megahirt ?  I think the initial issue was noticed because there might've been a cache involved and the refresh was not working.

**Comment by megahirt** [comment]
Yes. In my recent work on a PR I was able to make changes to the twig file
and a simple refresh showed changes.
