### ISSUE TITLE
feat: "whole word" search option

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1222]
**Is your feature request related to a problem? Please describe.**
@alex-larkin described the reasons for why a "whole word" search option is useful and in what circumstances over in issue #1114  
- other tools like FLEx and DAB have this
- it is critical when wanting to find stems, roots or affixes which are only a few characters

**Describe the solution you'd like**
A search option "search whole word only"

**Comment by longrunningprocess** [comment]
I'm also curious about a few concrete use cases as they exist today and how the results should change in those cases.

I demonstrate below that the exact match works pretty predictably (I think):

https://user-images.githubusercontent.com/4412848/137974539-d5474314-ef5a-4a9f-b704-4ee12bf3e80d.mov

**Comment by megahirt** [comment]
Hi @longrunningprocess good research here, my friend.  You have identified where changes should be made.  I also agree that a "search whole words" checkbox should sit somewhere in the collapsible options panel for the time being.  We're trying to add maximum value with minimal changes or trying to redesign stuff.

Please read this short article for background on "whole word search"  https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch02s06.html

The [`String.indexOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf) method is semantically equivalent to [`String.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) for search purposes.  This is what you are referring to when you say "exact match".

"exact match" or "string match" is not the same as "whole word match".  For "whole word match" I recommend switching to using regular expressions as the article above demonstrates.  This will achieve what @alex-larkin wants for his and most other Latin-based scripts.  Non-roman scripts are another beast all together, where "word" may not be a well-defined concept.

**Comment by alex-larkin** [comment]
I'm making a spreadsheet with examples. 
https://docs.google.com/spreadsheets/d/1_BGfMCDz3Gk1rTO3mY61e5kmyKYVJsKkz5ci_lw0-Tg/edit?usp=sharing
I'll comment again when I finish

**Comment by longrunningprocess** [comment]
Thanks for the clarification on the `for all` use cases, I've updated my little sandbox use cases.  You'll notice for this specific use case my algorithm did not work and the regex did...further confirmation that @megahirt 's instincts on the approach were right on.  not only is the solution more elegant, it also works :-D (not always a foregone conclusion)
