### ISSUE TITLE
feat: improve search result UX wrt highlighted terms in search results

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1223]
**Is your feature request related to a problem? Please describe.**
@alex-larkin and @longrunningprocess described UX confusion over the entry search results list highlighting the result in some entries and not others.  Discussion over in #1114 

**Describe the solution you'd like**
This is up for debate, and I personally don't have an issue with the UX because I can use several different apps with search results that are not highlighted.

Github Issue search is one example:
![image](https://user-images.githubusercontent.com/3444521/137466538-046ad3d0-d188-4c5b-a2fb-13fbb6225fd7.png)
In this example, the search term "highlight" is not visible in any of the issue titles, yet these issues are listed in the results.  The assumption is that you can trust that "highlight" is somewhere inside the issue itself, but not in the title.  The same assumption applies IMHO to searching lexical entries.

Gmail example:
![image](https://user-images.githubusercontent.com/3444521/137468128-6f221ea5-9e62-4482-90c6-7caf9110ccbf.png)

When I search for "Clark" in my email, the results come back with some results showing the word highlighted and some results do not have any highlighting.  I find this intuitive and understand that the word "Clark" is somewhere in the message but not in the results preview.

I can think of several ways to change the UX which might reduce confusion:

1. hide results where the match is not in the headword or definition.  Either leave them out entirely or put them in a collapsible pane with a "show more" link to expand the results pane.
2. figure out which field the results are present in, and show that instead of the definition, highlighting the result
3. remove the highlights so that the result look consistent
4. put a label on results that have no highlight saying "matched in entry"
5. something else I haven't thought of

**Comment by alex-larkin** [comment]
Thanks so much Chris for writing this up! I really think number 2 is the best option. I think number 3 would reduce search functionality. 1 and 4 could also be alternatives.
