### ISSUE TITLE
bug: missing fields in project configuration

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1228]
**Describe the bug**
Fields are missing in the **Simtho Syriac Lexicon FLEx** project's configuration view.

**To Reproduce**
1. Go to https://languageforge.org/app/lexicon/603a9809ee2c9e10c03d6fb0/#!/configuration
1. Notice there are no fields

**Expected behavior**
Fields should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/4412848/138311851-60c45883-9829-41ac-ab7f-468a978c9df7.png)

**Additional context**
Apparently this project was migrated from a Word doc at some point.

**Comment by longrunningprocess** [comment]
browser console error:

![image](https://user-images.githubusercontent.com/4412848/138312737-61e07b2e-ca6b-45ff-b78e-3659972af67d.png)

**Comment by longrunningprocess** [comment]
I wasn't necessarily expecting to find anything in the server-side logs but I checked anyway, I did not find anything there.

I think we're at the stage now where @megahirt or @rmunn might look at the project and determine what's wrong with it OR someone will need to pull this project in locally and walk the stacktrace to figure out where the data structure is out of shape.

**Comment by alex-larkin** [comment]
Ah, another factor that could be relevant: this project has a lot of custom fields, including (possibly) some custom lists.

**Comment by rmunn** [comment]
Got it figured out at last. The custom field had two different names: it was called `ORTH_Madnaya` in the roleViews part of the config, but it's called `ORTH_Madnḥaya` (note the ḥ) in the main part of the config. I double-checked the project's actual data and verified that `ORTH_Madnḥaya` was the right spelling, so I renamed `ORTH_Madnaya` to `ORTH_Madnḥaya` in the roleViews config and now the project configuration is loading correctly.

**Comment by longrunningprocess** [comment]
@alex-larkin would you mind closing this one once you confirm with your user they're happy with this?

**Comment by alex-larkin** [comment]
This is great! Thanks so much @rmunn! Will do @longrunningprocess. I just emailed him. 

Is there a bug in LF code, such that it didn't pick up on the rename? Should that be a separate issue?

Thanks!

Alex

**Comment by alex-larkin** [comment]
The user reports that it's working now. Thanks, and great work!
