### ISSUE TITLE
Remove "Beta" from video on languageforge.org homepage.

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1234]
I'll download the video from Youtube, cover "beta", and see if Chris or someone else can reupload it. Then someone will need to change the hyperlink. Billy, can you update the link once the revised video is up? Thanks!

**Comment by longrunningprocess** [comment]
will do, just let us know when it's done.

**Comment by megahirt** [comment]
@alex-larkin this was an easy one for me to handle.  You can review https://github.com/sillsdev/web-languageforge/pull/1235
