### ISSUE TITLE
Remove "Share" button from My Projects Page

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1241]
**Describe the bug**
Currently, the "Share" button is visible on the My Projects page. But when you click on it, it opens a window with just a heading. It doesn't do anything. It should be removed. 

**To Reproduce**
1. Go to https://languageforge.org/app/projects from an account with sharing permissions
2. Click on "Share"
3. Observe that there is nothing to do. 

**Expected behavior**
No "Share" button on the "My Projects" page. The button should only be visible while working in a given project. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82162128/140787421-027e9f4b-d570-496b-8094-15bb1bda5424.png)
![image](https://user-images.githubusercontent.com/82162128/140787444-21d71705-936d-4c7e-8cb0-c67404a3eea7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Mobile (please complete the following information):**
NA
**Android App in Google Play**
NA

**Additional context**
None

**Comment by alex-larkin** [comment]
@palmtreefrb, is this something you can take care of? If not, feel free to resasign. Thanks!

**Comment by megahirt** [comment]
This card is very similar in implementation to move settings cog #993
