### ISSUE TITLE
bug: inconsistent save behavior

### ISSUE THREAD

**Issue by dowens76** [sillsdev/web-languageforge#1248]
**Problem**

While working on a lexicon entry, some work saves and some work does not.

**Steps to reproduce**

1. Go to an entry.
2. Make some changes to two different fields. For the screen capture, I could only reproduce this for changing the part of speech.
3. Navigate to another entry and then return to the original entry. 
4. Note that some data is saved and some is not saved.

**Expected behavior**
All data entered into fields should save (as it usually does). 

**Screenshots**
Here is a screen capture showing the behavior: https://youtu.be/E96ZbUz94pQ

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: reproduced on Vivaldi, Firefox, and Brave

**Comment by alex-larkin** [comment]
Hello Daniel, 

Our apologies for the delay in response to your issue. Thank you so much for bringing this to our attention in GitHub. I watched your video several times and I was able to reproduce your issue sporadically in several different fields, in my own project.  It appears that it is possible to navigate away from an entry before a very recent edit is saved- something we certainly need to address. I'll bring it up with the development team. 

In the meantime, a workaround that works in my brief testing is to always click on a field in a different meaning, or, in the entry section, before navigating to a different entry.  We'll keep you posted.

**Comment by dowens76** [comment]
Thanks, @alex-larkin. I noticed this again today and experimented a bit, and I noticed two things: 

- Custom fields do not save, even if I type something elsewhere afterward. 
- Built-in fields seem to save, as you say, if I click on a field in another part of the entry (such as another definition).

**Comment by alex-larkin** [comment]
Thanks @dowens76. 

I'm sorry you continue to have trouble with this. 

I was able to reproduce this behavior. 

For the developers' reference, using the Quechua Demo project, I was sometimes able to reproduce the issue in these customs fields, which are at the entry level:
* Morpheme Properties
* Publicar En

I was more consistently able to reproduce the issue with this custom list, at the meaning level:
* Transition Value

Some of these fields are hidden by default.

**Comment by alex-larkin** [comment]
I also tried setting a Transition Value and then counting to 20 seconds before changing entries. But even so, the value would be lost.

**Comment by megahirt** [comment]
@dowens76 we have shipped a fix for the issue that you reported - can you confirm that the bug is fixed?  Thanks!

**Comment by rmunn** [comment]
We've seen this happening again, so I'm reopening this issue. The bugfix we deployed in #1313 was clearly not the only cause of this happening.

**Comment by megahirt** [comment]
Hi Alex and Chris, 

Had a little bit of funkiness with custom fields. My guess is that the current best practice is to only add custom fields in FLEx and then propagate through the LD/LF ecosystem, but we thought you should know what we ran into.  The biggest worry was that a custom field create in LF was not synchronizing across LF users. 


Larry

---------- Forwarded message ---------
From: Jay
Date: Tue, Mar 15, 2022 at 1:42 PM
Subject: Language Forge Bug

To whom it may concern,

We found a few bugs in language forge recently when we created a custom field on the entry level. I added the field in language forge on my device, but when another team member opened the same project, the field did not exist. Then, after syncing the project, the field disappeared from my device. 

We then tried creating the custom field in FLEx, running send/receive, and finally syncing LF again. This allowed us to see the FLEx-generated custom field within LF. Still, when I tried to populate this field on some entries (but not others), the changes would not save within LF.

The code for the project in language depot is ****, and these changes were attempted on March 9. 

Thank you for your help!
Jay

**Comment by rmunn** [comment]
In the project from https://github.com/sillsdev/web-languageforge/issues/1248#issuecomment-1072062621, I found the following:

* The Language Forge project config included configuration for a custom field named `customField_entry_Variant2`
* The FLEx project configuration included a custom field named Variant2 on the LexEntry, which would correspond to a field name of `customField_entry_Variant2` in LF. So far, so good.
* The data in the Language Forge lexicon included three entries with data in a custom field. All three of them had data in a custom field named `customField_entry_Variant_1`.

My conclusion: at some point the custom field was renamed from "Variant 1" to "Variant2" (i.e., from `customField_entry_Variant_1` to `customField_entry_Variant2` in LF), and the Language Forge code that renames custom fields failed to rename the field name in the existing data. So the three entries that had data in `customField_entry_Variant_1`, which should have had that data field renamed to `customField_entry_Variant2`, didn't get renamed. And so now there's data in the project that doesn't have a field in the project config, which is causing confusion as some entries' custom fields don't seem to be there, data doesn't seem to be saved, etc.

We can manually rename the field names in the three affected entries. I'll wait until I hear back from the project owner(s) before making that change.

**Comment by rmunn** [comment]
Finally found the cause of the original issue where the Part of Speech field wasn't working. I will add end-to-end tests to verify that the fix also works for custom fields, but since the root cause was "the field is a list field" (that is, one where you have a dropdown menu to select one option from a list) rather than "the field is a custom field", I believe the same fix will work for custom fields of type list, as well as the built-in fields like Part of Speech. So I've created #1368 to fix the bug with list fields right away, and I'll create the end-to-end tests later since that's less urgent.
