### ISSUE TITLE
Diacritic matches not being highlighted properly

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1260]
@longrunningprocess in my testing this, I realized that we didn't address the highlighting that matches a string.  I'm pretty sure you are already aware of it, and that's fine.  I'm mostly just commenting about it explicitly for future reference.

The [highlightMatches() method](https://github.com/sillsdev/web-languageforge/blob/staging/src/angular-app/languageforge/lexicon/editor/editor.component.ts#L661) would need to be rewritten or modified to take into a account the part about ignoring diacritics.

When I search for "chu" in the default mode, only the exact matches for "chu" are selected, even though the results show those that include diacritics, see below.

![image](https://user-images.githubusercontent.com/3444521/144189807-048094be-2cdc-4302-ac7b-c3c5a277c1f3.png)
(whole word is selected as an option to reduce hits)

What I would expect to see is that all headwords that contain a form of "chu" are highlighted, including:
- ćhü
- ćhu
etc.

_Originally posted by @megahirt in https://github.com/sillsdev/web-languageforge/issues/1243#issuecomment-983362809_

**Comment by megahirt** [comment]
That's for creating an issue for this
