### ISSUE TITLE
Eliminate JQuery dependency

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1263]
**Describe the bug**
An idea occurred in #1261 related to the possibility of eliminating LF's dependency on JQuery.  This issue will be a place to capture the work of that.

**To Reproduce**
N/A

**Expected behavior**
JQuery should be removed from the `package.json` and all uses of it should be converted to either native browser API's or JQLite (via `angular.element`.

**Screenshots**
N/A

**Comment by megahirt** [comment]
AFAICT the only reason we have kept fully JQuery around was because of our use of intl-tel-input widget, which is being removed in #1611 

We should be good to go to remove JQuery and intl-tel-input from package.json once #1611 is in.
