### ISSUE TITLE
feat: Improve diacritic-agnostic search result ranking

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1266]
**Is your feature request related to a problem? Please describe.**

Issue explainer video:
https://user-images.githubusercontent.com/82162128/145472277-a811b6fe-d3a7-40c5-bb94-f1a14736d881.mp4

The new diacritic-agnostic search feature is great. However, the order of search results is not intuitive. In fact, when I first was testing this feature, I thought that it wasn't working, because of the order of the search results. Reordering the search results to conform with user expectations will greatly increase the usefulness of this feature. 

Current ordering (as best as I can tell):
1. The word as typed
    A. Lexeme exact matches 
    B. Lexeme close matches
    C. Matches anywhere in the entry
2. The word but with a diacritic difference 
    A. Lexeme exact matches 
    B. Lexeme close matches
    C. Matches anywhere in the entry
3. The word but with another diacritic difference 
    A. Lexeme exact matches 
    B. Lexeme close matches
    C. Matches anywhere in the entry
4. The word but with yet another diacritic difference, etc. etc. etc...

For example, in the [Quechua Demo*](https://languageforge.org/app/lexicon/61b155d57dfdc546ab4939c3/) project:

Search term: **chaqui**
Results (abbreviated):
1. chaqui -_v. to dry_
2. chaqui -_adj. dry_
3. chaquicäcu
4. ancash
5. ćhaqui -_n. foot_
6. ćhaqui ataca
7. chicsa
8. dirïcha

**Describe the solution you'd like**

Desired ordering: 
1. Lexeme exact matches
    A. The word as typed
    B. The word but with a diacritic difference 
    C. The word but with another diacritic difference 
    D. The word but with yet another diacritic difference, etc. etc. etc...
2. Lexeme close matches
    A. The word as typed
    B. The word but with a diacritic difference 
    C. The word but with another diacritic difference 
    D. The word but with yet another diacritic difference, etc. etc. etc...
3. Matches anywhere in the entry _(but note that the order at this point isn't so important)_
    A. The word as typed
    B. The word but with a diacritic difference 
    C. The word but with another diacritic difference 
    D. The word but with yet another diacritic difference, etc. etc. etc...

For example, this is the ordering I would expect:

Search term: **chaqui**
Results (abbreviated):
1. chaqui _v. to dry_
2. chaqui _adj. dry_
3. ćhaqui _n. foot_
4. chaquicäcu
5. ćhaqui ataca
6. ancash
7. chicsa
8. dirïcha

**Describe alternatives you've considered**
Leaving as is- not desired. 

**Additional context**
Consider how DAB sorts results. [Here's a link to my app*.](https://sil-language-software.slack.com/files/U01S5PRM4CC/F02Q79X71QA/smith_draft_lexical_database-1.0.apk) 

@longrunningprocess, since you worked on this feature, is this something you can take up? 

Thanks!

*Private resource- development team only.

**Comment by longrunningprocess** [comment]
>@longrunningprocess, since you worked on this feature, is this something you can take up?

Most definitely, however it probably won't be until next year at this point.  

You've done an outstanding job explaining this and detailing what's needed, should make the goals of the effort very straightforward, not the implementation or "ranking" might be a different story.  Hopefully the code is written in a way that totally separates the "matching" process form the "ranking" process.

Make sure this sits high on yours and @megahirt 's priorities for our next sprint.

**Comment by alex-larkin** [comment]
Ok, thanks so much Billy! Sounds good
