### ISSUE TITLE
feat: make the search bar look more like a search bar

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1271]
**Is your feature request related to a problem? Please describe.**
Today I was talking on the phone with a senior linguist and a very gifted coder about Language Forge. He told me that he couldn't figure out how to search for words. I had to guide him in to the right spot. He eventually found it, but told me that he had thought that "Filter Entries" looked like a header to him. I agree that the search bar could be made more intuitive. 

**Describe the solution you'd like**
- Lighten the background of the search bar
- Add a magnifying glass icon inside the search bar to one side. Maybe one like this:
![outline_search_black_24dp](https://user-images.githubusercontent.com/82162128/146288362-2aa1eac5-3f9a-4a48-ac6f-dd8867b9946a.png)
![outline_search_white_24dp](https://user-images.githubusercontent.com/82162128/146288855-ca074b7b-2f5b-4139-9536-999a730d2a28.png)

Source: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asearch%3A
- Replace "Filter Entries" with "Search"

**Describe alternatives you've considered**
- Leave as is
- Poll more people

**Printscreen**
Current Search Bar:
![image](https://user-images.githubusercontent.com/82162128/146287917-e7537ea9-1071-45c6-b5d3-7b821c2ba321.png)

Other search bars for reference:
![image](https://user-images.githubusercontent.com/82162128/146288674-11b052a9-0e3f-495f-8368-5bd957f2e59c.png)
![Screenshot_20211215-200123_Smith DRAFT Lexical Database](https://user-images.githubusercontent.com/82162128/146288936-50b8d2b3-d310-43f9-ac1a-7ba9323fc539.jpg)

I welcome any thoughts.

**Comment by nachi0310** [comment]
hI @alex-larkin, i would like to give this issue a try.

**Comment by longrunningprocess** [comment]
Go for it my friend!  You know how to create the feature branch and do pr's?

**Comment by alex-larkin** [comment]
Yea man! Thanks. Go for it.

Thinking about it some more, I wonder if "Search entries" would be better than "Search."

Thoughts anyone?

**Comment by longrunningprocess** [comment]
Just tag me here if you have questions @nachi0310  and we can try to connect real-time if needed.

**Comment by nachi0310** [comment]
Thanks @longrunningprocess @alex-larkin, I am aware about feature branches and PR's. will set up the project and get back here if i get any issues / questions.

**Comment by longrunningprocess** [comment]
looks like you already forked it which is definitely the right way to go.  If you have a chance and/or an interest in getting together over MEET or Zoom or something please let me know.  I'd love to know more about how you ended up in our repo :-)

**Comment by nachi0310** [comment]
@longrunningprocess I won't be able to get on a zoom call today but wanted some help regarding setup. I am a novice in docker and I have done the setup as mentioned in the setup docs. I can see multiple processes running in docker desktop application, but when i visit localhost i am not getting any app output. is there something additional setting we need to do to get the website running ? I can see there are  6 docker processes on docker dashboard.

**Comment by megahirt** [comment]
@nachi0310 Thanks for reaching out.  What timezone are you?  I am GMT+7. 

About 8 months ago I made this developer video.  It's a bit dated with our process, but it could be helpful in seeing how to build LF.

https://youtu.be/Q0ObpyMJAU0

**Comment by nachi0310** [comment]
@alex-larkin Due to some things, i will not be available for next 20 - 25 days . Please assign the above issue to someone else. I will try to come back to this repo in the future for contributions. Thank you.

**Comment by alex-larkin** [comment]
Oh, okay. I hope everything's okay. Thanks, in any case! Looking forward to collaborating with you in the future. Take care.

**Comment by megahirt** [comment]
Regarding what text to display:
The technical term for this feature is indeed "filter entries" however I think the term "search" communicates better and is more commonly used.  If I asked an user to differentiate between "filter" and "search" I'm not sure everyone would be able to articulate the differences.

Regarding how it should look:
I suggest we include a magnifying glass icon to the left of the search input box and style the input more like an input, similar to the examples that @alex-larkin posted.
