### ISSUE TITLE
bug: "Oh. RPC Error. Server Status Code 500"

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1289]
**Describe the bug**
Today while trying to reproduce the issue discribed in [#1248](https://github.com/sillsdev/web-languageforge/issues/1248#issuecomment-1015038998) I ran into this error code: 

![image](https://user-images.githubusercontent.com/82162128/150590180-c5f65515-403e-4df0-8621-3f1f70f1b6c5.png)

It would appear after changing the value of a custom field and then switching entries. 

Here is what I found in the console: 
![image](https://user-images.githubusercontent.com/82162128/150590873-13116513-24f0-4c78-b94d-08f6f0799f91.png)
![image](https://user-images.githubusercontent.com/82162128/150590886-f5331157-507f-475f-8c8d-73655d59cc86.png)
![image](https://user-images.githubusercontent.com/82162128/150590902-021ffbb6-a33c-4dd2-8df5-4c540865a1a5.png)

Here is the complete second line- a beast so long that made the GitHub editor freeze continually as I wrote up this issue! It is 11 times longer than the maximum GitHub body length, so I had to attach it as a file. 
[error code 500 console error text 2022.01.22.txt](https://github.com/sillsdev/web-languageforge/files/7916304/error.code.500.console.error.text.2022.01.22.txt)

Possibly related: LF had a really hard time loading the custom lists on desktop. The list would simply show an empty box. (But they loaded fine on Chrome for Android).
![image](https://user-images.githubusercontent.com/82162128/150591139-73a7f54a-e237-46e2-bfd3-572cdd0df2fa.png)

Sometimes, after waiting, clicking on the drop-down arrow would cause the list to show correctly:
![image](https://user-images.githubusercontent.com/82162128/150591163-fc6cf45f-ad36-4c13-a9a0-a9556507fa72.png)

**To Reproduce**
1. Go to Quechua Demo project
2. Show all fields. 
3. Scroll down to the custom fields Status and Transition Value
4. Attempt to change their values and switch to another entry. 
5. See error

**Expected behavior**
1. LF loads the list
2. I select a value
3. That value is saved when I switch to another entry. 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome

**Additional context**
Possibly related to #1248

**Comment by megahirt** [comment]
This bug occurred long enough ago that I don't know if it is still reproducible.  @alex-larkin I'd like for you to follow your own steps to repro this bug again, and if so, we should address it.

**Comment by alex-larkin** [comment]
Thanks Chris! I tried to reproduce this on a few devices but was unable. (Note that I am still having problems with custom fields not saving properly, but that isn't what this issue is about). Closing issue.
