### ISSUE TITLE
feat: S/R "Source language and Variant of" fields

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1298]
**Is your feature request related to a problem? Please describe.**
A user noticed those fields were not syncing on his project.

**Describe the solution you'd like**
The user has requested those fields be synced during the S/R process.

**Describe alternatives you've considered**
N/A

**Additional context**
Request first raised here:  https://community.software.sil.org/t/sync-between-flex-and-lf-via-s-r-missing-fields/5855

**Comment by alex-larkin** [comment]
Thanks for creating this issue!

How much work world be required on the developer end to implement this?

Thanks!
