### ISSUE TITLE
Remove Transifex from app-for-e2e container

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1311]
**Is your feature request related to a problem? Please describe.**
I just experienced some very slow testing running Playwright E2E tests. Using Playwright's trace feature, I looked at the timing of the test, and the screenshots along different parts of the test timeline. And I noticed the following in the status bar of the E2E test browser:

* From 0.0 to 2.6 seconds: "app-for-e2e" showing in the status bar
* From 2.6 to 5.4 seconds: "Looking up cdn.transifex.com" showing in the status bar
* After 5.4 seconds: "Looked up cdn.transifex.com" showing in the status bar

If I'm reading that correctly, the simple DNS lookup for cdn.transifex.com took 2.8 seconds to complete.

**Describe the solution you'd like**
Translated UI is not desirable during E2E testing, as a lot of the E2E tests rely on the English UI language anyway. So by disabling Transifex during E2E testing, we'll save time (as above) and we'll remove a potential source of flakiness.

**Describe alternatives you've considered**
Of course, if we had any E2E tests that verify that the translations are loading properly, we'd need Transifex running for that. But I question whether such tests would be useful, as they would be testing someone else's code that's not under our control. E2E tests cost a lot of time, and should only be run against code that you might be able to fix. If the E2E tests showed Transifex translations not showing up properly, there's nothing we could do about it except wait for Transifex's service to come back online.

**Additional context**
Start of DNS lookup at 2.6 seconds:
![1](https://user-images.githubusercontent.com/90762/154621100-e7ad7274-d8e4-496c-88aa-615fec23312a.png)

DNS lookup still underway at 5.4 seconds:
![2](https://user-images.githubusercontent.com/90762/154621106-e968497c-5c61-46e6-b1c4-13cdf74e5410.png)

DNS lookup completed a couple milliseconds later at 5.4 seconds:
![3](https://user-images.githubusercontent.com/90762/154621109-d164ae3e-b376-4ea1-986d-52ea62acf17f.png)

**Comment by megahirt** [comment]
We can remove transifex CDN loading here: https://github.com/sillsdev/web-languageforge/blob/master/src/Site/views/shared/container/container.html.twig#L54

**Comment by megahirt** [comment]
The app-for-e2e container is removed in #1614 so this issue is no longer relevant
