### ISSUE TITLE
Optimize build-and-publish and integrate-and-deploy workflows

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1332]
While I was working on #1328 #1329 I made some changes to `build-and-publish-adhoc.yml` and `integrate-and-deploy.yml` to include a `npm install` step.  I hadn't taken a closer look until that time at the excellent work that @longrunningprocess did to utilize the GHA workflow_call trigger which basically sets up integrate-and-deploy as a function used by production.yml and staging.yml.  Slick!

In this issue I propose turning build-and-publish-adhoc.yml into a workflow_call trigger (and keep the workflow_dispatch trigger) and utilize this workflow inside of integrate-and-deploy.

Currently, the functionality contained in build-and-publish is almost entirely duplicated in integrate-and-deploy with a slight difference in how the image is built.  It was this difference in how the app image is built (one with docker and one with docker-compose) that made me think maybe these should be the same code path and we don't need to duplicate code.

I don't have experience doing this myself, otherwise I would have just taken it on.  Experimenting with GHA with regard to deployments and building images takes patience and lots of trial and error, so it will probably take some time to get right.

**Comment by longrunningprocess** [comment]
I've thought about that many times as well, especially every time I create another one that only differs my some small thing:
![image](https://user-images.githubusercontent.com/4412848/158388219-e206a815-1522-48c2-8db2-120dae2e2762.png)


but I keep running into security concerns along the way.   This is one I think we could do better on but I'd like to pair on it to discuss the security implications and other things first.
