### ISSUE TITLE
Disable adding custom fields in LF

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1340]
In #1248, we discovered that custom fields created in Language Forge were not making it through the Send/Receive process properly. I remember looking at the Language Forge custom field code a few years ago when I was implementing Send/Receive for custom fields, and my general impression was that LF's code for editing custom fields is, to put it bluntly, a mess. I propose that we turn off the ability to add **or edit** custom fields in Language Forge for Send/Receive projects, and replace that UI with a simple message saying "Please use FieldWorks to edit custom fields".

**Comment by rmunn** [comment]
A note about custom fields should also be added to the "Known Issues and Limitations" in the wiki,

**Comment by megahirt** [comment]
I totally agree with this assessment.  Let's disable the UI for creating / editing custom fields entirely.

- [ ] remove the + button for adding entry level custom fields
- [ ] remove the + button for adding sense level custom fields
- [ ] remove the + button for adding example level custom fields

![Image](https://user-images.githubusercontent.com/3444521/189054718-6f4f0a96-c3b9-4b24-a071-a7fb67726d13.png)

The above simply removes the capability for the user.

Optional and more extensive changes
- [ ] delete UI code associated with the + button press above, including the modal dialog
- [ ] If it exists, delete PHP code associated with creating custom fields



![Image](https://user-images.githubusercontent.com/3444521/189055247-42a5240e-a7d0-4b37-b147-5d4044575c69.png)
