### ISSUE TITLE
Affixes should be marked somehow

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#138]
If you look at the first 6 entries in my Swedish lexicon you will see 0, and 5 'a's. These are all suffixes, but there is no way to tell they are suffixes. It would be very helpful in the word list and also in the dictionary preview of an entry to put the appropriate symbol for the affix. e.g. -a for a suffix, b- for a prefix, -c- for an infix, =d for an enclitic, e= for a proclitic, etc.
Also it is not really correct to list the part of speech as shown for affixes (for clitics this is ok). -a (gloss=AGR.DEF) is not an adjective, but attaches to an adjective. If someone changed the POS to something else I don't know what kind of damage it would do. I would recommend showing the POS as in FLEx. E.g. adj:(NAgr) or n:(Any) or n > adj if possible, but at least making the POS field read-only since we aren't providing the facility in LF to really do much with affixes/clitics.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-23
