### ISSUE TITLE
bug: audio jumpiness in LF audio recordings

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1381]
**Describe the bug**
Audio recorded through the Language Forge website (whether mobile device or PC) results in degraded audio recording, identified by  "audio jumpiness", clicks or pops, or even repeated audio segments of ~100ms length

**To Reproduce**
1. Go to a project that has an audio writing system e.g. chris-test-sr1
2. Click on the microphone button to the right of the field (assuming no previous recording)
3. Click the large microphone button to start recording.
4. Record a 10 second clip with constant talking.
5. Save the recording by clicking the large microphone button again and then clicking the checkmark.
6. Play back the audio you just recorded and observe that it contains "jumpiness".  In my experience, the jumpiness occurs most often within the first second of the audio, but can also appear later on in the recording.

**Expected behavior**
Audio is recorded and saved as expected without additional degraded audio artifacts

**Screenshots**
![image](https://user-images.githubusercontent.com/3444521/163755006-002bfd49-9103-4940-be3d-4c444d35b517.png)

Reproduced on:
- Windows 10 - MS Edge (Chris)
- Android 12 Chrome (Chris)
- iPhone iOS 14 (Jay)

Additional context:
As one of the developers, I (Chris) know that this used to work 5 years ago when it was introduced.  However, frequent OS, browser and now LF dependency upgrades have changed the environment in which this code runs and there is obviously a regression identified by this bug report.

Proposed solution:
@rmunn and I did some initial investigation into the code responsible for this feature, and found that while it uses the standard [AudioContext API](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) (what was available when this feature was developed) there is a new [MediaStream Recording API ](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API )that we can use that should fix this bug and simplify/update our code.  See #1382 for more details.

**Comment by megahirt** [comment]
I want to note that while this is easily reproducible for me on languageforge.org, I cannot reproduce it locally in my development environment, which suggests the issue could possibly be related to network latency or other network conditions.

**Comment by Nateowami** [comment]
While I don't recall running into this problem, I'm not surprised to hear it, as it's an understandable failure mode. In the MP3Encoder class there's a comment that says:
> copy the data, because Chromium 66.0.3359.139 overwrites it (FF 60.0.1 does not)

If I recall correctly, every 100ms or so the `audioprocess` event would fire and give us a piece of audio data. And in Chromium, if we tried to save a reference to that data and access it 100ms or so later, it would have been overwritten already. The workaround for this was to copy the chunk of data so it didn't have to be encoded in real time, but I could imagine a brief increase of CPU usage or something else blocking the thread could cause us to miss a chunk and end up copying it later after it had been overwritten with the next chunk. I think this could cause the behavior that is being observed.

**Comment by megahirt** [comment]
@Nateowami just wanted to say thank you for adding your two cents to this - this is helpful to understand the background issues.

**Comment by LHayashi** [comment]
You might check in with @jasonleenaylor to see what they are using in thecombine.app for recording from a web app.
