### ISSUE TITLE
feat: Switch audio recording to use MediaRecorder API

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1382]
**Is your feature request related to a problem? Please describe.**
While looking into #1381, I discovered that our audio-recording component could be updated. It currently uses the [AudioContext API](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext), and then has to do quite a lot of work to massage the raw PCM data into a form that's acceptable to pass into lamejs to convert to MP3.

But there's a newer Web API, supported by all browsers except IE: [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder). The last browser to support this was Safari, which added support in Safari 14.1, as of April 2021. The MediaRecorder API allows you to write code like this:

```js
navigator.mediaDevices.getUserMedia({audio: true}).then(stream => {
  const recorder = new MediaRecorder(stream, { mimeType: "audio/mp3" });
  elem.addEventListener('dataavailable', event => saveDataToFile(event));
  recorder.start();
  // Sometime later, probably in the click handler for your stop button:
  recorder.stop();  // This triggers a `dataavailable` event
});
```

No need for external libraries like lamejs; the browser handles the encoding for you and presents you with data in the format you specify (MP3, MP4, WAV...). The media type can include a `codecs` parameter, such as `audio/mpeg;codecs="opus"`, and if the user's browser supports it, you'll get an MP4 container with Opus-format audio inside. (You can query which formats the browser supports using `MediaRecorder.isTypeSupported` beforehand).

**Describe the solution you'd like**
Change https://github.com/sillsdev/web-languageforge/blob/9f6519e93d9617f10cc9f689fa32f6bb0dddf603/src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts to use MediaRecorder to encode the MP3 files. (Or whatever other format; we might want to move up to M4A, for example). This will also reduce our external Javascript dependencies and remove some tech debt.

**Describe alternatives you've considered**
Doing nothing and leaving our code as-is, since it does work.

**Comment by rmunn** [comment]
I just want to mention that @Nateowami did excellent work on the audio-recorder code we plan to replace. At the time he wrote that, MediaRecorder was not available and he used the most up-to-date web APIs available. Now that MediaRecorder is widely available, it's the superior choice for this task, but that doesn't diminish Nate's excellent work in any way.

**Comment by Nateowami** [comment]
Scripture Forge has very similar needs for recording and uploading audio. Currently we're using [recordrtc](https://www.npmjs.com/package/recordrtc) for recording, and our back end converts the files to MP3.

For a long time I've wanted to drop the dependency on recordrtc, so I'm interested to see how this goes. Hopefully the Scripture Forge team can learn from the work you do to get this working in Language Forge.

**Comment by megahirt** [comment]
Thanks @Nateowami !  We'll keep you updated with our progress.
