### ISSUE TITLE
feat: allow m4a audio file extension when uploading audio recordings

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1383]
**Is your feature request related to a problem? Please describe.**
A common audio recording file extension (for both mobile and desktop recording software) is m4a.  This should be supported by LF.

**Describe the solution you'd like**
Uploading an m4a from the phone or desktop PC should be allowed.

**Proposed solution**
Add m4a to the list of allowed upload file types and see if that will achieve what we want

**Comment by rmunn** [comment]
I don't know how common it is to have .mp4 as an extension for a file that contains only audio and no video, but it's completely doable from a technical standpoint, so some software probably creates audio files with an .mp4 extension that are really .m4a files (no video tracks at all). It's possible that we'll end up needing to accept .mp4 extensions as well, and use something like the `ffprobe` command-line tool to check what streams are in the file, then handle it differently if it's audio-only vs. if it's a video file.

**Comment by megahirt** [comment]
This feature was shipped and tested in [Release 2022-04-18](https://github.com/sillsdev/web-languageforge/releases/tag/v2022-04-18).
