### ISSUE TITLE
Searches should give priority to exact matches at the beginning of the word

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#139]
In my Swedish project I want to find the word 'ta' (actually 'ta' is the citation form and 't' is the lexeme form) which means 'to take' and I type in the letters 'ta' I get a whole bunch of words, but words beginning with 't' are way down the list apparently, but only so many hits are shown. The only recourse to find this word is to scroll through the list of words until I get to the 't's. It would be very helpful if like FLEx the search would give priority to exact matches at the beginning of the word.

**Comment by irahopkinson** [comment]
Similar issue here https://github.com/sillsdev/web-languageforge/issues/15

**Comment by rmlockwood** [comment]
This is great!
