### ISSUE TITLE
No scroll bar on search pop up

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#14]
When I search for a word a pop-up comes up, but there is no way to scroll through all the results.

**Comment by megahirt** [comment]
This could definitely be improved.  When the search filter was written, I decided to only display 10 results (with no scroll bar) for performance reasons.  Now that we have large dictionaries (with 1000s of entries) on the site, it's obvious to you and me that we need something better.  Perhaps a scroll bar or a paging mechanism to be able to see all results would be the next step.

**Comment by darcywong00** [comment]
This is fixed in https://github.com/sillsdev/web-languageforge/issues/34

Search results now have a scrollbar for the top 50 results
