### ISSUE TITLE
bug: Race condition in Playwright webServer config

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1402]
**Describe the bug**
There's a race condition in the [Playwright `webServer` config](https://github.com/sillsdev/web-languageforge/blob/8164ccf592aa0f6b0054882c3f1b0bccd4a3811f/playwright.config.ts#L101): Playwright watches for the specified port to open, and as soon as the port is open, it assumes the configured webserver is up and running. Whereas Docker-Compose will open the port on localhost as soon as the container is up, even if nothing is listening to the port inside the container yet. That means that once we run `docker-compose up`, there's a race condition between the Apache process starting inside the container, and Playwright trying to talk to the webserver. If Playwright wins the race, it exits immediately with an ECONNREFUSED error, because nothing was actually listening on the port yet.

**To Reproduce**
1. Stop the webserver (via `docker-compose down`)
2. Run `npx playwright test`
3. Sometimes it will work, sometimes it will exit immediately with an error
4. If it exits, re-running it will work.

**Expected behavior**
We need to have a way to tell Playwright to wait for the port to actually be *ready* rather than merely open. That's not possible right now, but [in a future version of Playwright](https://github.com/microsoft/playwright/pull/13779#discussion_r861344756) there should be a `readinessCheck` parameter in the Playwright config. Once that is implemented, we'll be able to tell Playwright "Wait until this URL returns 200", which will solve this race condition and let us close the issue.

**Comment by myieye** [comment]
Just for the record, this is probably the relevant log. I forced this by just removing most of the contents of `docker/app/Dockerfile` so that the application doesn't run:

```
Running 1 test using 1 worker

[WebServer] lf-db is up-to-date
[WebServer] ld-db is up-to-date
[WebServer] lf-mail is up-to-date
[WebServer] ld-api is up-to-date
Starting app-for-playwright ... 
[WebServer] Starting app-for-playwright ... done
Error: apiRequestContext.post: connect ECONNREFUSED 127.0.0.1:3238
=========================== logs ===========================
→ POST http://localhost:3238/api/testControl
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/[53](https://github.com/myieye/web-languageforge/actions/runs/3088369860/jobs/4994793273#step:7:54)7.36 (KHTML, like Gecko) HeadlessChrome/105.0.5195.19 Safari/537.36
  accept: */*
  accept-encoding: gzip,deflate,br
  content-type: application/json
  content-length: 1[54](https://github.com/myieye/web-languageforge/actions/runs/3088369860/jobs/4994793273#step:7:55)
============================================================

   at utils/jsonrpc.ts:21

  19 |
  20 | export async function jsonRpc(request: APIRequestContext, url: string, method: string, orderedParams: any[] = [], params: any = {}) {
> 21 |   const result = await request.post(url, {
     |                                ^
  22 |     data: jsonRpcParams(method, orderedParams, params),
  23 |     // If debugging API calls, uncomment the next line so your debug session won't time out
  24 |     // timeout: 0,

    at jsonRpc (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/jsonrpc.ts:21:32)
    at testControl (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/jsonrpc.ts:39:10)
    at createUser (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/globalSetup.ts:15:10)
    at globalSetup (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/globalSetup.ts:35:13)
apiRequestContext.post: connect ECONNREFUSED 127.0.0.1:3238
=========================== logs ===========================
→ POST http://localhost:3238/api/testControl
  user-agent: Mozilla/5.0 (X11; Linux x86_[64](https://github.com/myieye/web-languageforge/actions/runs/3088369860/jobs/4994793273#step:7:65)) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/105.0.5195.19 Safari/537.36
  accept: */*
  accept-encoding: gzip,deflate,br
  content-type: application/json
  content-length: 154
============================================================
```

**Comment by megahirt** [comment]
AFAICT we never get this error when running using the [Makefile](https://github.com/sillsdev/web-languageforge/blob/develop/docker/Makefile#L24) because we've already solved it:
```
# wait until the app-for-playwright service is serving up HTTP before continuing
	until curl localhost:3238 > /dev/null 2>&1; do sleep 1; done
```

The trouble is, we aren't using the Makefile in GHA, so this race condition *could* happen.  sigh.

**Comment by myieye** [comment]
I guess we could just add that line to the action workflow.

**Comment by myieye** [comment]
It's not the same error, but I think it's quite possible that this has the same cause, so rather than creating a new issue:
```
Tue, 20 Sep 2022 12:01:00 GMT url: /api/testControl
Tue, 20 Sep 2022 12:01:00 GMT Error: apiRequestContext.post: socket hang up
=========================== logs ===========================
→ POST http://localhost:3238/api/testControl
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/105.0.[51](https://github.com/myieye/web-languageforge/actions/runs/3089915212/jobs/4998066336#step:7:52)95.19 Safari/[53](https://github.com/myieye/web-languageforge/actions/runs/3089915212/jobs/4998066336#step:7:54)7.36
  accept: */*
  accept-encoding: gzip,deflate,br
  content-type: application/json
  content-length: 1[54](https://github.com/myieye/web-languageforge/actions/runs/3089915212/jobs/4998066336#step:7:55)
============================================================

   at utils/jsonrpc.ts:24

  22 |   console.error('url: ' + url);
  23 |
> 24 |   const result = await request.post(url, {
     |                                ^
  25 |     data: jsonRpcParams(method, orderedParams, params),
  26 |     // If debugging API calls, uncomment the next line so your debug session won't time out
  27 |     // timeout: 0,

    at jsonRpc (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/jsonrpc.ts:24:32)
    at testControl (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/jsonrpc.ts:42:10)
    at createUser (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/globalSetup.ts:15:10)
    at globalSetup (/home/runner/work/web-languageforge/web-languageforge/test/e2e/utils/globalSetup.ts:42:13)
```
I found it interesting that the error happens virtually immediately rather than after a 30s timeout (for example).

**Comment by myieye** [comment]
Adding the [missing await](https://github.com/sillsdev/web-languageforge/blob/d4b1be4061f0748e1c8dbbc1fa7be0e9b68cc76f/test/e2e/utils/globalSetup.ts#L35) simply results in this no longer being logged. The rest of the log is basically identical.
```
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^
```

**Comment by rmunn** [comment]
There's now [a `url` parameter](https://playwright.dev/docs/api/class-testconfig#test-config-web-server) available in the `webServer` config. That specifies a URL that is expected to return a status code below 404 (e.g., 2xx, 3xx, and 400/401/402/403 are all considered to mean "the server is up and running"). Note that `url` and `port` are mutually exclusive.

So if we replace `port` with `url` in our `webServer` config, I believe this race condition will be solved.

**Comment by myieye** [comment]
I did play around with the url parameter. I.e. I went from `port: 3238` to `url: http://localhost:3238`. The `globalSetup.ts` worked, but in tests I got this:
```
 1) [chromium] › editor-entry.spec.ts:49:10 › Lexicon E2E Entry Editor and Entries List › Entries List › yay 
    apiRequestContext.post: Invalid URL

      23 |
      24 |   test.beforeAll(async ({ request, manager, managerTab, member, member2 }) => {
    > 25 |     project.id = await initTestProject(request, project.code, project.name, manager.username, [member.username]);
         |                        ^
      26 |     await addUserToProject(request, project.code, member2.username, "observer");
```
Somehow setting the URL in the `webServer` config affects URLs used in the tests. I didn't look further into it though.

**Comment by myieye** [comment]
I just ran the tests with the make file on my fork and it seemed fine. There's quite a bit more output, but it's not slower. Not quite sure what that's about.
https://github.com/myieye/web-languageforge/actions/runs/3090977938/jobs/5000474952

It's desireable to execute tests the same way locally and on GH as much as possible. So, using the make file seems very sensible to me.

Maybe I'll just open a PR and see what the reviewers have to say 😉.

**Comment by rmunn** [comment]
I believe that somewhere in the E2E test setup, I used the `port` value from `webConfig` to configure the base URL for API requests, and if there's no `port` value then that ends up being wrong. I'll look it up and post a link to the bit of code that needs to change.

**Comment by rmunn** [comment]
It's here:

https://github.com/sillsdev/web-languageforge/blob/develop/test/e2e/utils/globalSetup.ts#L20

Looks like I already took into account that there could be a `port` or a `url` parameter, but it might be necessary for the `url` parameter to end with *no* trailing slash, e.g. `http://localhost:3238` instead of `http://localhost:3238/`. Try removing the trailing slash and see if that works.

**Comment by myieye** [comment]
I run into the same errors regardless of whether I have a trailing slash or not.

At our team meeting we agreed that we should be using the make file, so I'm going to make that change. I think that will likely fix `ECONNREFUSED ` and `socket hang up`. We'll see and then go from there,
