### ISSUE TITLE
feat: store project assets (images/audio/uploads) in dedicated folder outside of src folder

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1443]
We should store the image/audio assets in a dedicated folder outside of /var/html or src and instead store them on a separate S3Bucket volume e.g. /assets

We should also copy/duplicate image/audio assets between this folder and the webwork folder, so that webwork is a true "cache" ([which could theoretically be evicted](https://github.com/sillsdev/LfMerge/issues/203))

**Comment by longrunningprocess** [comment]
current location with legacy app's container: `/var/www/html/assets` owned by `www-data`

volume mapped:  `lf-project-assets:/var/www/src/assets`

for non-s/r projects, this is the only location for audio/pics

for s/r projects, file is here: `/var/lib/languageforge/lexicon/sendreceive/webwork/chris-test-sr1/LinkedFiles/[AudioVisual|Pictures]` and linked from `/var/www/html/assets/lexicon/[project]/[audio|pictures]

**Comment by longrunningprocess** [comment]
@megahirt  a few questions below or maybe we can meet to discuss some time.

1.  You mention "uploads" as well in the title of this issue.  I'm not familiar with that, is that something that's still around?
1.  These assets are in two places depending on whether the project is S/R or not, I'd like to talk about the idea of centralizing projects whether they are sendreceive or not.  I'd presume we'd want all projects under the sendreceive folder.
1.  In all of this, we still need to maintain two copies, one in the cloud and one in the filesystem for S/R receive purposes...and then a reference in the database that will be utilized by the frontend to show it in the entry.  That's potentially three references we need to try and keep in sync for updates, deletes, etc., that sounds ambitious but maybe we can chat a little more about it.
1.  Do we just take all of this in steps, shut off the ability to create non-s/r, then move this separate folder and then finally work toward getting assets in the cloud?

In addition to this refactoring, I believe we'll need to be thinking of a migration of existing assets to a different area and hope we can get away with some "relative" aspect of filesystem access so we don't incur more refactoring.

One "ideal" data flow in my mind would be to simply maintain these assets in the cloud and have a reference in the db to them.  If lfmerge were to try a s/r, it would need to potentially extract the files from the cloud source and place them in the correct folder for the mercurial repo.

**Comment by megahirt** [comment]
@longrunningprocess good questions all around.  Here are my responses.
- Uploads are in the form of the initial lift, zip or 7z archive that is uploaded initially or imported at a later time under LIFT import.  This feature probably isn't used much given that FLEx has a more robust LIFT importer.
- The assets are always in the assets folder.  If a project is a S/R project (which is our main use case) then the project's asset folder is symlinked into `/var/lib/languageforge/lexicon/sendreceive/webwork`
- Yes, we need to chat about it.  I am really glad that you have looked into this some more and are asking these good questions.  I only see two actual copies: the cloud copy and the server copy in the assets folder.  We shouldn't double count the send/receive data because of the symlink.

**Comment by megahirt** [comment]
This task was created as a stepping stone to get us closer to a true repo cache which we could discard at will.  I am now having second thoughts about this approach in favor of merging Language Depot and Language Forge's repo storage together.  This is the ultimate goal, and I'm beginning to carve out an epic which describes how we can merge these two services together conceptually and architecturally.

We could address cloud-based storage of assets as a separate task if we wanted, but in this new future I'm not sure if the payoff is that big anymore.

**Comment by longrunningprocess** [comment]
> @longrunningprocess good questions all around. Here are my responses.
> 
> * Uploads are in the form of the initial lift, zip or 7z archive that is uploaded initially or imported at a later time under LIFT import.  This feature probably isn't used much given that FLEx has a more robust LIFT importer.

Should we create an issue to remove this capability altogether?

> * The assets are always in the assets folder.  If a project is a S/R project (which is our main use case) then the project's asset folder is symlinked into `/var/lib/languageforge/lexicon/sendreceive/webwork`

Actually, what I found is that the physical file is **either** in the assets folder **or** the project's sendreceive folder.

> * Yes, we need to chat about it.  I am really glad that you have looked into this some more and are asking these good questions.  I only see two actual copies: the cloud copy and the server copy in the assets folder.  We shouldn't double count the send/receive data because of the symlink.

---

> This task was created as a stepping stone to get us closer to a true repo cache which we could discard at will. I am now having second thoughts about this approach in favor of merging Language Depot and Language Forge's repo storage together. This is the ultimate goal, and I'm beginning to carve out an epic which describes how we can merge these two services together conceptually and architecturally.
>
> We could address cloud-based storage of assets as a separate task if we wanted, but in this new future I'm not sure if the payoff is that big anymore.

I agree, there's a lot of gross migration and refactoring stuff involved here, the merger sounds way more valuable to me as well.

**Comment by megahirt** [comment]
I agree - based upon new conversations, I'll close this as not planned
