### ISSUE TITLE
Integrate with lfmerge's "catch all exceptions"

### ISSUE THREAD

**Issue by josephmyers** [sillsdev/web-languageforge#1444]
### The UI should behave as follows

- [ ] A sync failure resulting in a HOLD state generates a red notice message.
- [ ] If the state is HOLD, the sync button should be greyed
- [ ] A sync with skipped entries or comments generates a yellow notice message. e.g. "Sync completed with skipped entries [or comments]"
- [ ] The synchronize page reflects all state file data that is relevant to the user (see below)
- [ ] If the state is HOLD, the UI should display a message:

We're sorry that we've run into an issue syncing your project with Language Depot. Please reach out to us at [issues@languageforge.org](mailto:issues@languageforge.org) if you don't hear from us directly. We want to help get you going again.

### State file data relevant to user (represented at cards in the UI?)

- [ ] Date/Time of last sync
- [ ] Duration of last sync
- [ ] Number of entries skipped (if errors)
- [ ] - Number of comments skipped (if errors)

## Mockup
![Screen Shot 2022-09-22 at 2 08 58 PM](https://user-images.githubusercontent.com/3444521/191684569-d22fffa9-0ba2-4460-8a16-593a03dd56f7.png)

## Code references

- [send-receive-status.model.ts](https://github.com/sillsdev/web-languageforge/blob/chore/fixes/src/angular-app/languageforge/lexicon/shared/model/send-receive-status.model.ts#L3)
- [getSyncProjectStatus()](https://github.com/sillsdev/web-languageforge/blob/chore/fixes/src/angular-app/languageforge/lexicon/core/lexicon-send-receive.service.ts#L182)
- [SendReceiveCommands::getProjectStatus()](https://github.com/sillsdev/web-languageforge/blob/chore/fixes/src/Api/Model/Languageforge/Lexicon/Command/SendReceiveCommands.php#L203)

c.f. #1188 

## LFMerge updates
Corresponding lfmerge issue [here](https://github.com/sillsdev/LfMerge/issues/232).

Language Forge needs to be updated to work with the changes in the above issue/PR. Due to complications in lfmerge, it's recommended to use `lfmerge:2.0.129-alpha.635` as the package which contains these changes.

**Comment by josephmyers** [comment]
In testing the fix for the above, I encountered a different issue where ChorusMerge failed. I modified the same field of the same entry, synced with FW, then synced with LF. Beware, this put the project into an unrecoverable state that required deleting it and re-pulling from LD.

As part of this feature for Language Forge, be sure to verify the above test case.

**Comment by megahirt** [comment]
fixing this closes #1303

**Comment by josephmyers** [comment]
```
{
  "Error": {
    "timestamp": "timestamp of when the exception occurred (or in the case of skipped entries/comments) the time when processing finished",
    "exceptionMessage": "string of global error message that occurred (not while looping entries/comments)",
    "skipped": {
      "toMongo": {
        "entries": {
          "count": 5,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the entry - probably lexeme first non empty WS. 100 character limit"
            }
          ]
        },
        "comments": {
          "count": 3,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the comment- 100 char limit",
              "entry": {
                "guid": "FW GUID",
                "id": "MongoId",
                "label": "string representing the comment- 100 char limit"
              }
            }
          ]
        }
      },
      "toLcm": {
        "entries": {
          "count": 5,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the entry - probably lexeme first non empty WS. 100 character limit"
            }
          ]
        },
        "comments": {
          "count": 3,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the comment- 100 char limit",
              "entry": {
                "guid": "FW GUID",
                "id": "MongoId",
                "label": "string representing the comment- 100 char limit"
              }
            }
          ]
        }
      }
    }
  }
}

```

**Comment by josephmyers** [comment]
Above is the lfmerge structure from the original issue

**Comment by megahirt** [comment]
I'm labeling this as blocked until we have a project we can test with that contains entry or comment level sync errors.

**Comment by longrunningprocess** [comment]
@josephmyers or @megahirt , is there a project for this?  Or can I simply fiddle with files to cause something like these?  

❗ FYI, arm64 users cannot utilize lfmerge locally at this time, i.e., Mac M1

**Comment by megahirt** [comment]
Since we're blocked and need a concrete project that can trigger this code with a repro, I am moving this off the dev board and back to the PO board.
