### ISSUE TITLE
bug: "create project" button missing when logging in via Google

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1473]
**Describe the bug**
I (Chris) received an email bug report from "Peter" about the following issue on languageforge.org:

> I created a Language Forge account but at the point where I should see a button to create or join a project, I only have a blank screen like this.

There are no JS console errors.
And then in a later email:

> I stumbled onto the source of the issue: 
> If I log in using my Google account I do not get the Start or Join a New Project, when I log in using my email address and password, I get it.

**Expected behavior**
The create project button should be visible to all users

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome and Edge

**Comment by megahirt** [comment]
I am wondering whether this could have been the result of the missing cache busting + a recent release.  First we need to see if this is an actual reproducible issue.

**Comment by megahirt** [comment]
@myieye can you put some time into trying to repro this on languageforge.org ?

**Comment by laineyhm** [comment]
I tried signing in with two Google accounts that I have. With both, I am getting the expected behavior. I come to the screen with the "Start or Join Project" button, click, and can make a project. I wonder how conditions might differ for Peter to cause the issue.

**Comment by myieye** [comment]
@megahirt How blank is the "blank screen"?

I wasn't able to reproduce it. I played around a bunch:
- Creating new account with Google and trying both sign in options
- Creating new account with email and password and trying both sign-in options
- In incognito mode as well as not

Potential next steps would maybe be getting (1) a HAR of the network requests and (2) the DOM state. 🤷
I haven't worked with HAR's much myself, so in case it's helpful:
![image](https://user-images.githubusercontent.com/12587509/191694707-f9e8d658-37bc-4783-8bc5-89b2d4e7d01b.png)

**Comment by alex-larkin** [comment]
It's showing up for me when I log in with Google: 


![Image](https://user-images.githubusercontent.com/82162128/191763663-e0a5e90d-e0e9-47aa-822d-c1085568bbc6.png)

**Comment by megahirt** [comment]
Thank you all for your help testing!  I will write Peter back that we cannot reproduce the issue.  Closing.

**Comment by alex-larkin** [comment]
Perhaps he has some kind of browser plugin that is interfering? Did he see the same behavior on multiple devices?
