### ISSUE TITLE
bug: missing favicon

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1476]
**Describe the bug**
The favicon on LFNext does not match the original legacy LF favicon

**Screenshots**
![Screen Shot 2022-09-23 at 3 22 00 PM](https://user-images.githubusercontent.com/3444521/191920436-0e52f338-dff8-4316-9cbe-d11f1b150776.png)

**Comment by longrunningprocess** [comment]
thanks for pointing out, should just be a matter of dropping in the same favicon if it's not already the same image.  Hopefully this is a quick one.
