### ISSUE TITLE
Word search feature can return some incorrect results

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#149]
While trying to reproduce a different bug, I typed a few random letters into the "Search Entries" bar above the word list in Language Forge's main edit view, and got some results that did not appear to contain that search text.

Specifically, I typed the letters `abf` into the "Search Entries" bar in my local copy of the `sv-flex` project, and got 8 matches, some of which did not appear to contain the letters "abf" anywhere in the data (including in the "extra fields" that are hidden by default). One such result, for example, was "Herr", meaning "Lord": the letter b appears nowhere at all in that entry. Further investigation revealed that the letters `abf` *do* actually appear in one place in that entry, though: in the GUID for that entry's first (and only) sense. The GUID for that LexSense object is `4418e7a9-4abf-4be6-9b5c-2e085f610af1`, which contains the letters `abf` in its second part (4abf). Another example is searching for "beef", which produces two results: "nötkött", the actual Swedish word for beef; and "se", the Swedish word for the verb "see". The "se" entry doesn't contain the English text "beef" anywhere, but it does happen to have a LexSense GUID of `114ff5441-0950-4fd7-beef-1864b5e109b2`, which is why it was incorrectly matched by the search string "beef".

So our "Search Entries" bar is currently searching through GUIDs as well as the actual text of entries, which produces a number of incorrect results that don't *actually* contain that text in any data that the users actually care about.

**Comment by megahirt** [comment]
Nice find Robin.

**Comment by megahirt** [comment]
@rmunn in the future I would like for bugs like this to be created as Trello cards (with the same detailed documentation, of course) and leave github / JIRA for user-reported issues.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-21
