### ISSUE TITLE
Local test artifacts should be cleaned up

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1494]
After running some playwright tests, I noticed many artifacts that are thankfully ignored by git.  I think it would be helpful to have these things cleaned up at the appropriate time.

![image](https://user-images.githubusercontent.com/4412848/193116787-ec0da8b4-66db-432c-a323-144ef2052322.png)

**Describe the solution you'd like**

I'd like to see a a target that is just for cleaning up the test remnants, I'm not sure at this point whether that's better located in the `package.json` or the `docker/Makefile`.  Once that target is made, at a minimum, I'd like to see that target utilized during a `make clean-powerwash`.  Whether it happens during a typical `make clean` can be open for discussion.

**Describe alternatives you've considered**
N/A

**Additional context**

Any removal should be done in a cross-platform way, e.g., `rimraf`

**Comment by longrunningprocess** [comment]
In addition, I also see the following docker images are left behind after a `make clean-powerwash`:

![image](https://user-images.githubusercontent.com/4412848/193123496-e1f72618-0511-4e78-85b4-e03309d8688b.png)


These should either be renamed to follow the `lf-` naming convention or have lines added explicitly in the `clean-powerwash` target.

**Comment by longrunningprocess** [comment]
I also noticed `docker/PhpUnitTests.xml`

**Comment by megahirt** [comment]
@longrunningprocess these are all great suggestions.  Go for it!
