### ISSUE TITLE
Search results should be ordered better

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#15]
In my Swedish project I have a word that is just one letter 'i'. When I search to try to find it, it is not in the results at all. Some kind of preference needs to be given for short words that begin with the search letter. In FLEx this is also a problem, but at least it shows up as the 4th result. Thanks, Ron L.

**Comment by megahirt** [comment]
Hi Ron,

Thanks for bringing this problem up.  So in addition to the other sorting bug you raised, short words (specifically one letter words) should be prioritized above the others, if they aren't naturally.

**Comment by rmdiamondl** [comment]
I didn't understand the last part of your comment: "if they aren't naturally", but yes if there is a complete match on a short word, it should be first.
