### ISSUE TITLE
chore: move Makefile to repo root, out of docker directory

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1511]
Our Makefile should be in the repo root as this is the expected location for a project Makefile.

In order to facilitate this change, various paths in the following files will probably need to be changed to make this work

- [x] Makefile itself
- [x] GHA yml files
- [x] Dockerfile in various folders?
- [x] docker-compose.yml
- [x] our various README files

As a matter of opinion, it would also seem appropriate to move the docker-compose.yml file to the repo root as well.

Thoughts @longrunningprocess ?

**Comment by longrunningprocess** [comment]
I know it's something @rmunn has wanted for a long time, he'll be thrilled if this moves forward.

> As a matter of opinion, it would also seem appropriate to move the docker-compose.yml file to the repo root as well.

yes @megahirt , that is convention.

**Comment by myieye** [comment]
We'd also want to undo #1510. 😆

**Comment by longrunningprocess** [comment]
# Testing

## `make` from a totally clean environment

💥 
```
#0 130.3 acing.o  -lm -lc  -soname xdebug.so -o .libs/xdebug.so
#0 130.3 cc: error: xdebug.so: No such file or directory
#0 130.3 cc: error: unrecognized command line option '-soname'
#0 130.3 make: *** [Makefile:324: xdebug.la] Error 1
#0 130.4 ERROR: `make -j4' failed
------
failed to solve: executor failed running [/bin/sh -c install-php-extensions xdebug]: exit code: 1
make: *** [build] Error 17
```

ran `make` again without making any changes and app started just fine.

1. logged in with `admin` user
2. updated admin's  avatar
3. changed admin password

✅  looks good

## `make dev`

everything started fine

✅  updated `src/Site/views/languageforge/container/languageforge.html.twig`, refreshed page and saw change
✅  updated `src/angular-app/bellows/apps/projects/projects-app.component.ts`, waited for bundler to re-run, refreshed page and saw change
✅  updated `src/angular-app/bellows/apps/projects/projects-app.component.html`, opened Dev Tools and disabled cache, refreshed page and saw changes
✅  updated `src/config.php`, refreshed page and saw change

## `make playwright-tests`

everything started fine

✅  tests ran, not all passed but those aren't related to this work

## `make next-dev`

✅  updated `next-app/src/routes/+layout.svelte` and instantly saw update

## `make clean`

✅  shut containers down and while maintaining volumes

## `make clean-powerwash`

✅  shut containers down, removed volumes and appropriate images

## `make unit-tests`

everything started fine

✅  tests all ran successfully
