### ISSUE TITLE
Issues need to be created for Alex

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1517]
With Alex taking a temporary leave, he's asked us to create issues for his following observations:
![image](https://user-images.githubusercontent.com/4412848/194342975-6b924ce3-cfcb-458f-b5ba-fdeb64d43129.png)

**Comment by longrunningprocess** [comment]
@megahirt already had this one:  [bug: missing favicon](https://github.com/sillsdev/web-languageforge/issues/1476#top)

**Comment by alex-larkin** [comment]
Thanks so much Billy! So sorry to drop this on you guys.

**Comment by longrunningprocess** [comment]
> Thanks so much Billy! So sorry to drop this on you guys.

not a problem at all, these are great observations, we'll get them worked in.

**Comment by longrunningprocess** [comment]
I was not able to reproduce the "occasional white bar on bottom of screen issue", @alex-larkin mind directing me how you saw that?

**Comment by longrunningprocess** [comment]
created [feat: Clickable stats on project landing page](https://github.com/sillsdev/web-languageforge/issues/1525#top)

**Comment by longrunningprocess** [comment]
created [bug: adding large pictures not working](https://github.com/sillsdev/web-languageforge/issues/1526#top)

**Comment by longrunningprocess** [comment]
I was not able to reproduce the "caption field only appears for first image" observation, maybe you can show me how to reproduce it @alex-larkin ?

![image](https://user-images.githubusercontent.com/4412848/195907182-3dc61bc8-c80c-4ab7-a3da-a8c86e376924.png)

**Comment by longrunningprocess** [comment]
I'd like more info for the infinite scrolling observation, I'm not sure exactly what problem you were seeing.  Thanks @alex-larkin

**Comment by megahirt** [comment]
@longrunningprocess I don't have any further insight into the issues @alex-larkin has encountered.  You've done a great job pulling what we can confirm into issues for further action.  I'll close this meta issue now.
