### ISSUE TITLE
Delete entry or sense not working

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#152]
I'm trying to delete an entry in my Swedish lexicon. Nothing happens when I click on the trash can. Same thing for a sense.

**Comment by megahirt** [comment]
I opened up your Swedish project on our QA server and deleted an entry there without a problem (this is not your actual data).  What browser/OS are you using?  You should see a confirmation dialog when you click on the trash can.  Like this:
![image](https://user-images.githubusercontent.com/3444521/29958534-614d217c-8f1d-11e7-8dd4-fc387bf651bc.png)

If it's not working for you, can you open up a browser console and see if there is a javascript console error?

Also, try and do a Ctrl-R to reload the app and see if that fixes it?

**Comment by rmlockwood** [comment]
I did Ctrl-R and it works now. Thanks.

**Comment by megahirt** [comment]
Thanks @rmlockwood .  Your experience confirms that we really need a better way to roll out updates.  The browser clients sometimes is "partially updated" while other stale files are still cached.  We will need to find a solution to ensure that everyone's browser gets the full update once we ship a new release without having to ask users to do Ctrl-R.

Closing this issue now.
