### ISSUE TITLE
feat:  References for help needed on public site

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1522]
**Is your feature request related to a problem? Please describe.**
Users without a login do not where to go for help, looks they have to set up an account to learn more

**Describe the solution you'd like**
LF should offer resources to emails, community, videos, etc. from the public pages.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by megahirt** [comment]
This is totally needed - thanks for creating this issue!
