### ISSUE TITLE
feat: Clickable stats on project landing page

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1525]
**Is your feature request related to a problem? Please describe.**

@alex-larkin requested these stats be clickable:
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/4412848/195902483-d16bae23-02cb-496b-831a-3937cf9f205d.png">

**Describe the solution you'd like**

We would need to discuss where those clicks would take the user and determine from there whether we'd build new pages for them or not.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by megahirt** [comment]
This is basically acknowledging that there is more information behind these stats that a user wants to see.  These are probably all views that don't exist yet, except for maybe clicking on entries takes you to the entry list.

**Comment by megahirt** [comment]
I do think that there could be a valuable view for each of these stats, however in the meantime I actually think we could deep link into the editor to at least show something close to what these stats mean.

Here are the stats and the corresponding link:

- users = go to share dialog (listing the users)
- entries = go to the dictionary
- entries with audio = go to the dictionary with the filter set to show only entries with audio
- entries with pictures = go to the dictionary with the filter set to show only entries with pictures
- unresolved comments = go to the dictionary with the filter set to show only entries with comments

**Comment by longrunningprocess** [comment]
yeah, I like those ideas!

**Comment by longrunningprocess** [comment]
this is good timing because it's going to raise the issue of the conversion between project code and project id again... maybe we discuss how to solve it for these and the rest will take care of itself

**Comment by longrunningprocess** [comment]
What do. you think about the idea of accepting the `project_code` into LFNext where, when needed, it converts to the `project_id` on the server side before calling any php api's?

1. This would allow us to interact directly with mongodb from our sveltekit code which we had begun talking about already
2. It would allow us to utilize existing php api's without changing to `project_code` consumers the way we did for `Sf.php->project_read_by_code`

Of course, as an alternative to #1 above, we could simply create a php api that utilizes `ProjectModel::getByProjectCode($projectCode)` for the conversion.

Anyway, just some thoughts for discussion.

**Comment by megahirt** [comment]
> What do. you think about the idea of accepting the project_code into LFNext where, when needed, it converts to the project_id on the server side before calling any php api's?

When I read this I don't understand exactly what you mean.  I think we probably need to have a Meet about it.

I generally like the move toward using project code instead of project ID - it is nicer for users (including me) I think.

I think having a [`setProject(projectCode)` api method as mentioned](https://github.com/sillsdev/web-languageforge/issues/1576#issuecomment-1299633540) in #1576 will go a long way toward sorting this out.  As a side effect, I don't think `project_read_by_code` would be necessary anymore.

**Comment by longrunningprocess** [comment]
> * users = go to share dialog (listing the users)

I don't think this one is deep-linkable actually... 😞

**Comment by megahirt** [comment]
> I don't think this one is deep-linkable actually... 😞

Yeah, you're right, it's not deep linkable out of the box but it wouldn't be too hard to add a URL parameter for the share dialog as an additional step.

**Comment by megahirt** [comment]
Here's something I just now realized: the "unresolved comments" should not be visible or clickable for user's whose role is Observer.  They shouldn't be able to see comments in the first place.  So this is a future todo.
