### ISSUE TITLE
bug: adding large pictures not working

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1526]
**Describe the bug**
When adding large images (not sure of the exact size cutoff here), sometimes it won't display the first time it's uploaded.

**To Reproduce**
1. Go to the editor for a project
1. Click the "Show Extra Fields" button
1. Scroll down and find the "Add Picture" button
1. Add a picture that is "large" at least > 1MB
1. You should not see the image display but still get a warning about it being too big for FLEx
1. Try uploading it again and you should see the image show this time

**Expected behavior**

The image should show immediately the first time it's uploaded

**Screenshots**

I was not recording the first time it happened and then I was not able to reproduce it while recording... maybe someone else can attempt.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**

N/A

**Comment by megahirt** [comment]
@laineyhm can you try and repro this when you get back to work on LF?

**Comment by megahirt** [comment]
@laineyhm I'd like to get second eyes on this, as @longrunningprocess cannot reliably repro this.

**Comment by laineyhm** [comment]
I tried with 2 MB and 5 MB jpg files, and both appeared ~immediately (some delay with the 5 MB picture, but it appeared on its own without me needing to retry uploading, or refresh the page). I didn't notice this bug in Chrome, Firefox, or Edge on Windows.

**Comment by megahirt** [comment]
@laineyhm thank you for trying further.  One final try would be to simulate a throttled internet and see if we can repro with a slow connection.  If not, then I am happy for you to close this issue as "not planned / cannot repro".

**Comment by laineyhm** [comment]
Sounds good. I just tried simulated 2G and 3G and uploaded a 5 MB image. I didn't experience the bug of it uploading but not displaying. In both simulations, the image loaded slowly, with the progress bar showing loading progress, and no notice about the send/receive limit until after the image finished loading. The images displayed as expected. I tried this in Firefox, Chrome, and Edge on Windows.
