### ISSUE TITLE
Show citation form in the search results

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#153]
It's very nice to have the citation form in the browse view of the dictionary. It would be nice and proper I think to have the citation form in the search results as well. You are giving two piece of information in the search results and these should be the canonical data pieces for the entry. The citation form, if it exists and the definition (which you already have).

**Comment by megahirt** [comment]
I'm pretty sure that the citation form does show up in the search results.  It's working for me.  Can you verify?
![image](https://user-images.githubusercontent.com/3444521/29959166-4d3004ea-8f20-11e7-8dae-0c2ed120641d.png)

**Comment by rmlockwood** [comment]
Yes, it seems to be working now. Maybe I was in some in-between state. I was seeing citation forms in the browse list, but not in the search results. Thanks.

**Comment by megahirt** [comment]
ok, glad it's working now.  closing this issue.
