### ISSUE TITLE
feat: Better UI for deleting entries

### ISSUE THREAD

**Issue by laineyhm** [sillsdev/web-languageforge#1537]
**Is your feature request related to a problem? Please describe.**
How to delete an entry from Language Forge is not obvious. A user had to ask how to do that (answer: use the three dots at the top right of the editing area). 

**Describe the solution you'd like**
Trash can symbol or red X symbol, visible (not in the three dots) for Entry, Meaning, and Example. These should display on mobile.

**Describe alternatives you've considered**
What we already have

**Comment by megahirt** [comment]
The hotdog menu, three dots which contains the delete feature, isn't intuitive/discoverable for users.  I observed this first-hand on our Cambodia trip.  e.g. "How do I delete an entry?"

- [ ] for entry - replace three dots with trashcan icon delete button (no label)
- [ ] for meaning and examples, replace three dots with the the delete button and the re-order buttons as applicable
- [ ] verify the new UI works on mobile

**Comment by longrunningprocess** [comment]
<img width="766" alt="image" src="https://user-images.githubusercontent.com/4412848/200443422-8486c40e-da6b-4044-9797-1810f96c0365.png">

**Comment by longrunningprocess** [comment]
> * [ ]  for meaning and examples, replace three dots with the the delete button and the re-order buttons as applicable

@megahirt , I only saw the one item in the dropdown for Meaning and Example, are there scenarios where there are more?

**Comment by megahirt** [comment]
@longrunningprocess you can find additional options in the drop down once you have more than one Meaning or Example.

![image](https://user-images.githubusercontent.com/3444521/200456958-7657ce73-60c0-465b-bb4d-f770a2f46c40.png)

There is an option for moving the item up or down based upon its position in the list.  This applies to both Meaning and Example.

**Comment by longrunningprocess** [comment]
That totally clarifies your second bullet above, thanks

**Comment by megahirt** [comment]
> the trash can icon, maybe it should be red and it should have a tooltip on hover just in case. Each of the actions have chicken pages FYI

Yes to the red trash can icon and tooltip.

What are chicken pages?

**Comment by longrunningprocess** [comment]
> What are chicken pages?

:-D "Are you sure?" stuff  🐔

**Comment by megahirt** [comment]
yes to the trash can delete chicken

no chicken necessary for moving items within a list.

**Comment by longrunningprocess** [comment]
> yes to the trash can delete chicken
> 
> no chicken necessary for moving items within a list.

thankfully, there's no chicken page for the move actions already.  I was saying that early when I thought delete was the only action.
