### ISSUE TITLE
feat: Make the "My Projects" menu scrollable

### ISSUE THREAD

**Issue by laineyhm** [sillsdev/web-languageforge#1539]
**Is your feature request related to a problem? Please describe.**
In viewing the My Projects menu, a long list of projects may not be visible because the dropdown doesn't scroll.

**Describe the solution you'd like**
Make the My Projects dropdown menu scrollable

**Comment by megahirt** [comment]
![Image](https://user-images.githubusercontent.com/3444521/198686134-6f0ef969-ae4e-4bb0-9d59-70e9ff55606d.png)

I am on a large number of projects.  This fix is really only for an admin use-case, so it's low priority, but...

In the above example, only projects A-E are showing for me until I run out of vertical browser real estate.  If the dropdown was scrollable, then I can navigate to the project I want without having to visit the projects page first.

I don't want a dev to spend 2 hours on this.  If there's an easy fix, then that's what I want, but it's not worth a lot of effort for an admin use case IMO.

If it's hard, let's mark it as "wont fix".

**Comment by longrunningprocess** [comment]
hopefully it's just a matter of adding `scroll-behavior` to the parent

**Comment by megahirt** [comment]
> hopefully it's just a matter of adding a `max-height` and `scroll-behavior` to the parent

sounds great - try it and and if it works, then make it so!

**Comment by longrunningprocess** [comment]
> then make it so!

Nice Star Trek reference!  You need the additional "#1" 🤓

**Comment by longrunningprocess** [comment]
https://user-images.githubusercontent.com/4412848/198860195-64f387ea-ac67-4e51-ac19-198a46041828.mov



```css

   max-height: 100vh;
   overflow-y: scroll;

```

![image](https://user-images.githubusercontent.com/4412848/198860159-25339661-af5f-41fb-b0fc-973be56f56ff.png)

**Comment by megahirt** [comment]
Demo looks great!  This is exactly the kind of quick work I'm looking for.  Unlikely to affect your average user...super helpful for me :)
