### ISSUE TITLE
feat: Backup/Restore project as zip file

### ISSUE THREAD

**Issue by laineyhm** [sillsdev/web-languageforge#1542]
**Is your feature request related to a problem? Please describe.**
There is currently no simple way to download a Language Forge project for purposes of reproducing errors and fixing up projects.

**Describe the solution you'd like**
A menu option to download the project as a zipfile (export) and one to import the project as a zipfile, and the right processes in place to make these actions possible.

Data to be backed up

- [ ] mongodb project db (includes entries, comments and activity)
- [ ] mongodb project doc inside sf db
- [ ] assets folder
- [ ] s/r repo folder
- [ ] s/r state file
- [ ] user records involved in the project

UI should have an option to include filesystem data or leave it out of the backup (results in broken media links)

Backup behavior

- [ ] create zip file on server, then link to the file for download
- [ ] how to clean up zip file on server (/tmp file location?)...is this even necessary in an ephemeral container?

Restore behavior (dev command line use case)

- [ ] resolve dangling userRefs - create stub anon users for these userRefs; check project integrity?
- [ ] add user to project as owner/manager

Implementation notes

- have to install `mongo-tools` in the php app image in order to access command line tools e.g. `mongoexport` and `mongoimport`. `mongodump` and `mongorestore` are not suitable for this use case as we cannot easily choose which collections fields to export/import.

**Comment by longrunningprocess** [comment]
Please update Kent Schroeder when this is released @megahirt , he was asking about it today on the ALTC meeting.

**Comment by wensherix** [comment]
I think adding a feature to create ebook and paper dictionaries for Amazon would be ideal and it could help developer to even monetise the solution in the future.
Amazon publishing does not have tools for creating dictionaries or even sorting the measurements of the pages.
The solution could be monetised by using cloud storage 
And could be free by using local storage.
I hope to see this feature of exporting documents for Amazon publishing , Google publishing and kobo publishing and maybe even more.

the solution as it is is good but needs the publishing compatibility features .
As I said it could be monetised when using cloud storage 

the other feature that could be added is integration with mobile apps and selling it as a SaaS by adding a domian to the account, adding front end view for customers with checkout that supports free or paid subscription access.

there are so many dialects and languages in this world and there are so many missing languages.

there are specialised dictionaries or industry specific dictionaries could be offered to the customers. I supposed students will love this 

good luck
Addar

**Comment by megahirt** [comment]
This is reasonably high priority for me to be able to continue to develop LF Classic and respond to user issues in the system.

I will modify the issue text that Lainey posted and update it with my current thinking.

**Comment by hahn-kev** [comment]
As for zip cleanup. In dotnet we just stream the zip, so there is no tmp file to clean up. This has the benefit of not making the connection wait for the zip process to finish and resulted in a much faster download, the only downside is that you don't know the progress of the download since you don't know the size of the zip file since it's not done compressing.

**Comment by megahirt** [comment]
In talking with Robin, we think we can achieve the backup/restore project feature as two scripts that run kubectl for remote execution and data transfer.

In order to resolve userRefs, we think we can
- download a list of userIds that are part of the project data e.g. userRef, createdBy, modifiedBy, etc.
- create a dummy user for each userRef
- the project users can just be set to the admin user
