### ISSUE TITLE
feat: view and interact with comments all in one place

### ISSUE THREAD

**Issue by laineyhm** [sillsdev/web-languageforge#1543]
**Is your feature request related to a problem? Please describe.**
There is currently no way to view a collection of all of the comments that have been made on a Language Forge project.

**Describe the solution you'd like**
An activity or panel to view all of the comments in your project, with entries hyperlinked to comments. 

**Additional context**
This was requested by one of our users at a recent consult.

**Comment by laineyhm** [comment]
We already have "# Comments" button, which, when clicked on, shows all the comments for a single entry. Maybe we could do a similar thing with a button on the line above saying "All Comments" or something like that, which when clicked on, shows a scrollable dropdown of all the comments in the project, with links to their entries. Kind of like Google Docs does ([](https://workspacetips.io/tips/docs/see-all-comments-in-a-google-doc-even-resolved-ones/#:~:text=Click%20on%20the%20Comments%20button,list%20summary%20of%20all%20comments.))

![image](https://user-images.githubusercontent.com/56163492/197920420-5a88e0ac-bba5-49af-b687-3fa4cc4d3056.png)

**Comment by megahirt** [comment]
@longrunningprocess this is likely going to be our next Svelte view.  We need to spend some time designing this out.
Essentially we want a single view that displays all comments for the entire project, with some tooling around sorting, filtering, bulk state changes, etc.
