### ISSUE TITLE
feat: Home page improvements

### ISSUE THREAD

**Issue by myieye** [sillsdev/web-languageforge#1548]
**Is your feature request related to a problem? Please describe.**

There are several things I don't love about the home page:
- The forge image is huge (and pixely).
- The light gray color of the help links/buttons makes them look disabled
- The image doesn't feel very "forgey" to me

![image](https://user-images.githubusercontent.com/12587509/197136355-58a676a3-8dae-49a9-b103-5148d09f8590.png)

**Describe the solution you'd like**

1. The "forge" image should be the same shape ans size as the city image:

![image](https://user-images.githubusercontent.com/12587509/197136448-eca04693-9bb9-4656-9e05-3070be040732.png)

2. The help links/buttons should use a darker color. E.g. black.

3. We should use a different forge image. E.g. one of thse from unsplash:

![georg-bommeli-Q-wG7ciuD_k-unsplash](https://user-images.githubusercontent.com/12587509/197136628-85e2e7eb-11c2-4fbc-a42b-59eb0346bde6.jpg)
![clark-young-fQxMGkYXqFU-unsplash](https://user-images.githubusercontent.com/12587509/197136646-a0b4a33b-0fcc-40b5-8b05-c2532e7cfbe4.jpg)
![jonny-gios-4AT3mZMuFuI-unsplash](https://user-images.githubusercontent.com/12587509/197136648-f1cd971f-0336-4d58-8040-5491116aa4d0.jpg)
![hannah-gibbs-BINLgyrG_fI-unsplash](https://user-images.githubusercontent.com/12587509/197136662-ceaaceb2-719f-4270-bdbd-8f9cad3cb0eb.jpg)

**Comment by megahirt** [comment]
@myieye great suggestions!

The front page is static and easy to edit - no compilation necessary.  It's just a forked template, so edit away to make it so it's not annoying :)

**Comment by longrunningprocess** [comment]
while you're in this one, I'd ask that you also consider putting in E2E tests for these pages since that would've helped us out recently.  The home page as well as the `terms_and_conditions` page were both broken.
