### ISSUE TITLE
fix GHA warnings from usage of ::set-output

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1550]
**Describe the bug**

See warnings on this run:  https://github.com/sillsdev/web-languageforge/actions/runs/3299222198

**To Reproduce**

We should see these warnings on any run that utilizes deprecated apis

**Expected behavior**

We don't want any warnings if we can avoid them.

**Screenshots**

N/A

**Desktop (please complete the following information):**

N/A

**Mobile (please complete the following information):**

N/A

**Android App in Google Play**

N/A

**Additional context**

N/A

**Comment by rmunn** [comment]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by megahirt** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/3444521/197372237-37c377a3-f8d2-4c06-8430-2f6826582dd8.png">
