### ISSUE TITLE
disable editing of Option lists in LF (all option list edits should happen in FLEx)

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1552]

**Comment by laineyhm** [comment]
Does this mean getting rid of the + capability for all of the lists?

![image](https://user-images.githubusercontent.com/56163492/197919219-1c19d150-ab52-4899-9c4c-68ac5fa0b6aa.png)

**Comment by laineyhm** [comment]
^ yes and edit the message to say "Use FLEx to edit this list"

**Comment by rmunn** [comment]
See also https://github.com/sillsdev/web-languageforge/issues/977 and https://github.com/sillsdev/web-languageforge/issues/976.

**Comment by rmunn** [comment]
And see my proposal in #1559, spurred on by my discussion with @josephmyers and @megahirt in the Slack chat. Once option lists in LF are keyed by GUID, it should be possible to restore the editing feature without breaking Send/Receive.
