### ISSUE TITLE
disable editing of writing systems in LF (all edits of writing systems should happen in FLEx)

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1553]

**Comment by laineyhm** [comment]
-get rid of the three dots menu
-keep RTL setting, abbreviation, and font name
-other settings should be displayed but not editable
-get rid of new button in input systems tab and under input systems in configuration

**Comment by rmunn** [comment]
For #1552, I proposed redesigning the option lists to be keyed by GUID, which would allow us to restore the edit feature eventually. But for this one, I agree with removing the edit feature. I don't see a way to allow writing system edits in LF without massive Send/Receive conflicts. There might be a way involving a massive rearchitecture, but I don't have ANY good ideas. (Only some bad ones that are so bad they're not worth considering). So I agree with removing the ability for LF to edit writing systems, and not restoring that feature in the future (unlike option lists, which I think we *will* be able to edit in the future once we rearchitect them).
