### ISSUE TITLE
feat: allow admins to delete a project

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1561]
**Is your feature request related to a problem? Please describe.**
Currently, only project owners can delete a project.  This is challenging from a tech support perspective.

**Describe the solution you'd like**
If you are a site admin, you should be able to delete a project.

**Describe alternatives you've considered**
This feature request is related to #1560 

**Additional context**
This feature will be helpful when helping users to "reset" their project from Language Depot

![image](https://user-images.githubusercontent.com/3444521/197938085-5389ceed-188f-4796-87e2-b9a578e44159.png)
The Delete tab should work for site admins, not just project owners

**Comment by laineyhm** [comment]
![image](https://user-images.githubusercontent.com/56163492/201826165-cc8dbfc7-a1d6-4127-b54c-cbc29c67f0c0.png)

We discovered that the ability for admins to delete projects has already been coded. So now we just need to update the message in the chicken page.
