### ISSUE TITLE
bug: online/offline messages are distracting and unnecessary for flaky connections that mostly work

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1571]
**Describe the bug**
A user has reported that the online/offline messages fill their screen when they are trying to use Language Forge.  This could be due to a flaky/unstable internet connection.  The user reports that the website is still usable, but that the messages continue to fill the screen if she doesn't continually close them.

**To Reproduce**

I don't think we can repro this behavior easily.

**Expected behavior**
We don't need explicit messages for online/offline that repeat themselves.  We just need a simple indicator for online/offline.  We already have this with the change in title and color.

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/3444521/199022771-4ac14f74-6801-4905-975a-e36054765190.png)
User-reported screenshot

Proposed change:

- Remove use of the notice system for online/offline transitions.

The existing color change and title change to "Language Forge Offline" is enough for the user to notice.
See screenshot:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/3444521/199023845-8d81c454-cd12-45dc-8cb4-3ab764125342.png">

**Comment by longrunningprocess** [comment]
There are a few ways to solve this but I'd recommend the easiest and quickest for now to simply not pop messages for this.  Simply changing the color of the app and updating the title to "Offline" seems like a decent solution for the moment.

A longer term solution might involve ensuring the notification service uses a different id when queueing things so dupes won't show.

I also noticed we are using an abandoned library for detection, I'd suggest we simply pull that dependency out altogether and utilize https://caniuse.com/online-status.

I'll go ahead and put a PR out to stop generating notifications for now for a quick fix and we can discuss more options if needed.

**Comment by megahirt** [comment]
Yes, I would like to use the https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine#Specification HTML spec on this - @longrunningprocess can you create an issue for this upgrade?  Will be nice to get rid of another dependency!
