### ISSUE TITLE
stateless LFNext calls need to accommodate stateful legacy PHP calls

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1576]
> This doesn't really address the core issue described in #1536. We will likely run into this issue (wrong project context) as we build out more views in Svelte, so we need to take a step back and engineer something that allows the Svelte code to set the project Id directly. The AngularJS application doesn't have to do this because the project ID is embedded in the URL of the PHP code that serves up the application. The svelte application works differently, so we need to add functionality to our API to facilitate this new way.
> 
> How about adding a PHP API method called `setProject` whose purpose is to set the project context before calling subsequent API methods.
> 
> I think ultimately we want an api where you pass the project id as a parameter (stateless), but that would require re-architecting all the api methods and calling (a big job). We would design our new rest API in this way, with all the things.

I can take a look at converting the project code to an id in the Svelte backend before any legacy calls.  I'd suggest we get this fix in ASAP since that's a bug right now and we can circle back with our desired, long-term solution.  What are your thoughts on that approach?

_Originally posted by @longrunningprocess in https://github.com/sillsdev/web-languageforge/issues/1563#issuecomment-1298709695_

**Comment by megahirt** [comment]
> I can take a look at converting the project code to an id in the Svelte backend before any legacy calls.

That sounds hard since you don't have the id or an easy way to derive it that I can think of.  You already have the project code, so the API method you implement should look like `setProject(projectCode)`.  Call that just before you call the other methods and this should fix the issue.
