### ISSUE TITLE
Unresolved comments on dashboard should be hidden for users with observer role

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1579]
Need to review stars for authz, e.g., 

        Here's something I just now realized: the "unresolved comments" should not be visible or clickable for user's whose role is Observer.  They shouldn't be able to see comments in the first place.  So this is a future todo.

_Originally posted by @megahirt in https://github.com/sillsdev/web-languageforge/issues/1525#issuecomment-1303000296_

**Comment by megahirt** [comment]
Yes, this is going to be important to have.  The project dashboard needs more information on the project and the current user and their capabilities.
