### ISSUE TITLE
Search not working in SBF project for contributor

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#158]
When logged in to the project with the initials SBF as a contributor, the search box doesn't come up when I type a word in English or in the vernacular. It happens in both Chrome and Firefox. When I am logged in as Owner/Manager, the search comes up fine.

**Comment by megahirt** [comment]
OK, so just to confirm you are talking about the search box above the compact list view:
![image](https://user-images.githubusercontent.com/3444521/30063635-8ff4895c-9279-11e7-82b4-8260753e9086.png)

What's the project name in LF ?

**Comment by rmunn** [comment]
I can confirm the issue. I added myself as a contributor to that project and I could see the "Search Entries" box, but typing into it did nothing. Oddly, though, if I clicked on the Options button to the right of the search box and changed the sorting order to either "Part of Speech" or "Modified By" and *then* did a search, I was able to see search results.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-19
