### ISSUE TITLE
bug: audio input system detection not working for non-standard language tag

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1601]
**Describe the bug**
In working today with a team member interested in using Language Forge, I pulled in their project from Language Depot and showed them their dictionary in LF.  What was unexpected was that the audio input system with the audio files were represented as plain text field instead of the audio playback widget.  See screenshot:

![image](https://user-images.githubusercontent.com/3444521/202403860-ddbd1eb8-aa9a-4144-afb5-2199ec535bd9.png)

I was initially confused about this, but then I looked at the language tag for the audio input system.  I note that it does not follow the standard format for an audio input system that LF expects (expecting `Zxxx-lang-x-audio`).  In this project, the audio input system look like` Zxxx-lang-x-other-audio` where `other `is an arbitrary string.

LF should make its pattern matching detection of audio writing systems more flexible to be able to handle this kind of uncommon input system tag, one I've never seen before.

[Elawa200810](https://languageforge.org/app/lexicon/6375e5395be4fc4cbb03d862)

I also want to note that the LFNext dashboard has audio detection built in that appears to work fine, since it correct shows the number of entries which contain audio:
![image](https://user-images.githubusercontent.com/3444521/202406225-8fd8275c-392d-4305-9867-57bad0b1a16e.png)

**To Reproduce**
Open the project above and note that the audio input system does not have a play/record button, but instead has a plain text field.

**Expected behavior**
The audio play/record button is visible for fields which contain an audio file.

**Comment by myieye** [comment]
Well this is interesting (at least for me). Here in the UI it's parsed "minority" out of the name and displays it in the UI. Do we want that?:
![image](https://user-images.githubusercontent.com/12587509/202487916-8c2314a4-502e-4876-99fb-7628730f5efb.png)

And it correctly shows up as audio:
![image](https://user-images.githubusercontent.com/12587509/202487982-71283702-9d8b-4423-9f5c-814141568408.png)
