### ISSUE TITLE
bug: editor component of empty project blank for users who aren't managers, owners, admins

### ISSUE THREAD

**Issue by laineyhm** [sillsdev/web-languageforge#1605]
**Describe the bug**
Whereas the editor component would normally populate this information for an empty project:
![image](https://user-images.githubusercontent.com/56163492/202617396-6ec08edd-b10b-4441-99f0-ca32d2cfbd37.png)

New members of the empty project who are editors, commenters, or viewers but not managers see a blank component:
![image](https://user-images.githubusercontent.com/56163492/202617314-d9cef877-f37d-432d-b723-8c2be2f503ba.png)

and can't create entries.

**To Reproduce**

1. Go to languageforge.org
2. Share an empty project to another user, giving that user permission to edit.
3. Sign in as the other user. Go to the project that was just shared.
4. See that the information and buttons do not load.

**Expected behavior**
The same information should be given to editors as to managers in this situation, because editors are allowed to add entries.

**Screenshots**
Please see the screenshots in the description above.

**Desktop (please complete the following information):**

Experienced this so far in
- OS: Windows
- Browser: Chrome

**Comment by megahirt** [comment]
Wow, nice find @laineyhm :). Thanks for going after this one.

**Comment by longrunningprocess** [comment]
# Testing in staging

new project, empty: 
![image](https://user-images.githubusercontent.com/4412848/202775391-80716d01-7727-4c36-8ee5-2ff6cd516700.png)

user invitation:
![image](https://user-images.githubusercontent.com/4412848/202775644-b8634aa4-c626-4b9d-815b-b931b4fcdca2.png)

✅  new user sees buttons
![image](https://user-images.githubusercontent.com/4412848/202775888-aa3a2673-217a-479f-bd6a-a7c485143c27.png)
