### ISSUE TITLE
UI Language picker should not show semantic domain localizations

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1616]
The UI language picker shows a bunch of "semantic domain only" languages in the list, however this was never a requested feature and IMO only serves to clutter up the actual list of localized UI languages.  We should remove them from the list.  If we find out later that people are using the semantic domain localizations in LF, we can reinstate them, perhaps with better UI.

The PR to fix this should surgically remove the code that adds these semantic domain items to the list, and related plumbing.  If we decide to put the feature back, we can revert the commit.

**Screenshots**
The UI language picker occurs in two places:

The project properties tab under settings:
![image](https://user-images.githubusercontent.com/3444521/204225306-92f0852a-6c7f-4f33-9f12-095c8e77e726.png)

The menu bar UI language picker:
![image](https://user-images.githubusercontent.com/3444521/204225406-96b43eba-e149-44fd-b3fe-f08084b6c1a0.png)

**Comment by laineyhm** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/56163492/204463934-0b4d847e-0ec2-4b05-a39a-7cfb21364819.png)

Is this what you would want it to look like?

**Comment by megahirt** [comment]
Yes, that's right!  Only the languages which we have actual UI localizations should show up.  Thanks!
