### ISSUE TITLE
rearchitect Docker build to use --target

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1654]
Our current Dockerfile uses a build arg to create a fake-conditional in the Dockerfile to switch between production/development use cases.  This is a hack at best and results in both sides of the conditional being build, regardless of the use case.

We can switch to using the `--target` flag e.g. `docker build --target=production .` and, if our Dockerfile has a proper multi-stage dependency graph isolated to the right target, we should not have the problems associated with the build arg hack.

**Comment by rmunn** [comment]
Decided to fix this as part of PR #1818 so there's only a single PR to make all the build changes at once.
