### ISSUE TITLE
GHA add issue to project is broken (deprecated graphql api)

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1655]
![image](https://user-images.githubusercontent.com/3444521/207811038-a03a1751-0b5d-4c81-b0c5-3f82dcc7a289.png)

See https://github.com/sillsdev/web-languageforge/actions/runs/3702302426/jobs/6272428391 for an example

There is also a deprecation warning for set-output (not sure if this is us or not)
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by megahirt** [comment]
Fixed in https://github.com/sillsdev/web-languageforge/commit/edc6ab4bbfec5167a0509a1a369ef891a887c917

**Comment by longrunningprocess** [comment]
# Testing

seemed to work on [bug: misleading notification while deleting an account](https://github.com/sillsdev/web-languageforge/issues/1697#top)
