### ISSUE TITLE
bug: Start or Join a new project button missing in QA

### ISSUE THREAD

**Issue by myieye** [sillsdev/web-languageforge#1663]
**Describe the bug**
The "Start or Join a new project" button is missing in QA 😮.

**To Reproduce**

See for yourself: https://qa.languageforge.org/app/projects

**Screenshots**
![image](https://user-images.githubusercontent.com/12587509/209373573-3c58f6e2-9fbd-4a03-992d-5e3ebb813bb9.png)

**Comment by myieye** [comment]
I guess my previous 3 accounts just all lost their permissions in QA. When I create a new user, I can see the button.

**Comment by megahirt** [comment]
Good to hear this isn't an actual problem with our code. Fyi, GitHub now
has a "close as not planned" option instead of "close as completed".
