### ISSUE TITLE
Opening multiple projects in multiple tabs could corrupt indexdb (needs testing to reproduce)

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#167]
I'm seeing strange behavior in my Swedish project. There are 3 records at the top of my dictionary list that shouldn't be there. See the image below. None of this data is present in my FLEx project. There have been times when the data disappears, but I don't know when. Right now refreshing doesn't cause the records to disappear.

![image](https://user-images.githubusercontent.com/7088137/31560957-f7bf6a88-b01b-11e7-9afd-2f9ad9dfa264.png)

**Comment by irahopkinson** [comment]
I don't see those 3. I think you might have a corrupted **IndexedDB** in your browser from having 2 different projects open in 2 tabs. Please clear out **IndexedDB**:

1. Click *more* (vertical ellipsis top right) then **More tools**, then **Developer tools** (or simply type *Ctrl* + *Shift* + *I*).
2. Select the **Application** tab then select **Clear storage**.
3. Un-check all except **IndexedDB**, then click **Clear site data**
4. Refresh the browser to reload the project.

Let me know if this fixes it. If so we will need to trace down the bug.

**Comment by rmlockwood** [comment]
That fixed it. Thanks, Ron

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-15
