### ISSUE TITLE
Oh. RPC Error

### ISSUE THREAD

**Issue by emmahab** [sillsdev/web-languageforge#168]
Server Status Code 500

This happened when the LIFT file was almost uploaded into Language Forge. The system shows me that the data were uploaded successfully but the number of uploaded entries is smaller than expected one. What does it mean?
Emmanuel

**Comment by megahirt** [comment]
Can you send us the lift file?  Email to issues at language forge dot org.
Thanks.

**Comment by megahirt** [comment]
Closing as waiting on user.  If this is still an issue please email us at  issues at languageforge dot org
