### ISSUE TITLE
bug: misleading notification while deleting an account

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1697]
**Describe the bug**

When trying to delete my account, I received the "chicken page" but also noticed a notification inthe background that an update had happened already.  It did not but that should not be happening.

**To Reproduce**
1. Attempt to delete your account
2. notice the success notification in the background

**Expected behavior**
No notification should be present before the user has made a change

**Screenshots**
<img width="778" alt="image" src="https://user-images.githubusercontent.com/4412848/212980681-f6702dd4-fc39-45d6-81ec-46528bcca47e.png">

**Comment by myieye** [comment]
🧪 Looks good to me 👍 

- Created and deleted an account
- I didn't see the green info bar when the confirm dialog opened

I'm going to move this to waiting for PO signoff

I opened a tiny PR, for something that I figured was sort of missing: https://github.com/sillsdev/web-languageforge/pull/1703
