### ISSUE TITLE
bug: Allow all LanguageDepotProgrammers to join all Language Forge projects

### ISSUE THREAD

**Issue by laineyhm** [sillsdev/web-languageforge#1699]
**Describe the bug**
Right now, even though we've made a Language Depot role of "LanguageDepotProgrammer" (similar to "Tech Support"), we are requiring these users to make themselves managers of a project on Language Depot before they can join the project on Language Forge. 

**To Reproduce**

1. Add yourself as a LanguageDepotProgrammer to a project.
2. From Language Forge > Start or Join a New Project > Get Project From Language Depot, enter your credentials and try to select this project from the project dropdown.
3. Bug: If you are not also a manager on the project, you will not be able to join.

**Expected behavior**
The `LanguageDepotProgrammers` role on LD should be sufficient to clone/create a project on Language Forge.

**Screenshots**

I am a LanguageDepotProgrammer on the this project, TestLangProj-IH-FLEx:
![image](https://user-images.githubusercontent.com/56163492/213349735-0063ae40-d9f3-4ea8-a501-4678358f5251.png)

But I can't join the project in Language Forge:
![image](https://user-images.githubusercontent.com/56163492/213349890-7b3071f3-e616-4c8b-8a6e-6fa73ebafc7f.png)

**Comment by laineyhm** [comment]
**Language Depot code also needs to change:**
In LanguageDepot/src/api/models/UserController.php:
![image](https://user-images.githubusercontent.com/56163492/213368384-6679502b-a87b-4362-9488-b9993cb86c69.png)

**Comment by megahirt** [comment]
Now that we have retired redmine language depot, this is no longer an issue
