### ISSUE TITLE
bug: a user's `lastUsedProjectId:` might not exist anymore

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1708]
**Describe the bug**
I was having a problem logging into staging.  I'm not sure whether this was the underlying issue but after I changed my password I began noticing a new error.

**To Reproduce**
I presume these steps are what led to my issue:

1. Go to a project
2. delete that project
3. log out
4. try to log in again

**Expected behavior**
When a user comes into the app, the app should not fail to get him/her to a project

**Additional context**
Either the `lastUsedProjectId:` for a user needs to be updated when a project is deleted or the upfront algorithm needs to handle the possibility that the is might not exist anymore.

This might be related to #1600 , not totally sure.

**Comment by megahirt** [comment]
https://github.com/sillsdev/web-languageforge/blob/feature/userIsDeleted/src/Api/Model/Shared/Command/ProjectCommands.php#L95 is the only protection I can find to guard against `lastUsedProjectId` from being invalid, but I can think of a scenario where this isn't sufficient.  E.g. if there are two users (one being the owner) who both have `lastUsedProjectId` set to that project.  Then the owner deletes the project.  In this case, the owner's `lastUsedProjectId` is cleared, but the other user's `lastUsedProjectId` is likely set to a `projectId` that doesn't exist anymore.

**Comment by megahirt** [comment]
I would suggest that a one line change to clear `lastUsedProjectId` on this line https://github.com/sillsdev/web-languageforge/blob/develop/src/Api/Model/Shared/ProjectModel.php#L132 is the proper fix if the project being deleted matches the user's `lastUsedProjectId`
