### ISSUE TITLE
bug: Upload fails for 10MB mp3 file with PHP 400 error: no such file or directory

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#1712]
See documentation of bug here: https://github.com/sillsdev/web-languageforge/pull/1701#issuecomment-1401526743

**Comment by laineyhm** [comment]
Today I tested with larger files again and was successful with three files: a 10.2MB MP3 file, an 18MB WAV file, and a 21MB WAV file. All received the warning that they won't be synced with FLEx, as they are over 10 MB in size. All still uploaded and played as expected.
