### ISSUE TITLE
bug: The requested lazy property "paragraphsHtml" is not defined

### ISSUE THREAD

**Issue by myieye** [sillsdev/web-languageforge#1754]
Reported by a user:
![image](https://github.com/sillsdev/web-languageforge/assets/12587509/fe603180-12c3-474d-918b-a7fed0fbc816)

"paragraphsHtml" is a (not fully registered in language-forge) property of multi-paragraph custom fields.

I can sort of reproduce this, by (via source inspector) enabling a custom field of the appropriate type and making a change. The error is the same, but the stack trace is different:
```
The requested lazy property "paragraphsHtml" is not defined in "Api\Model\Languageforge\Lexicon\LexMultiParagraph#00000000048180c3000000006e2d6915" line 40 /var/www/html/vendor/ocramius/lazy-property/src/LazyProperty/Exception/InvalidLazyProperty.php 
DeepDiffDecoder.php line 133, DeepDiffDecoder::setValue(Api\Model\Languageforge\Lexicon\LexMultiParagraph, paragraphsHtml, Test)

DeepDiffDecoder.php line 67, DeepDiffDecoder::applySingleDiff(Api\Model\Languageforge\Lexicon\LexEntryModel, Api\Model\Shared\DeepDiff\EditedDiff)

LexEntryCommands.php line 144, DeepDiffDecoder::applyDeepDiff(Api\Model\Languageforge\Lexicon\LexEntryModel, Array)

Sf.php line 574, LexEntryCommands::updateEntry(646f41bbaae5f044cd0d5882, Array, 646f35ce9d2d21f4b9c0f514)
```

I assume the user has a "paragraphsHtml" in their database. I cannot reproduce that. I don't know where it comes from. I've tried quite a few things in FLEx and all I end up with is "paragraphs" which can contain HTML:
```
"customField_entry_Html_Notes": {
        "inputSystem": "en",
        "paragraphs": [
          {
            "guid": "8a8dde41-dfb7-4537-969b-99fe766e18a2",
            "styleName": "Heading 1",
            "content": "My no"
          },
          {
            "guid": "d3fb3d5b-162e-44d6-a754-25cae9a776cb",
            "styleName": "Normal",
            "content": "asd <span lang=\"seh\">new WS</span> "
          },
          {
            "guid": "343c317e-9605-4777-82c5-a571a8b37f6b",
            "styleName": "Normal",
            "content": null
          },
          {
            "guid": "ba5d5c79-d554-4dc8-82ca-b653cebb23ba",
            "styleName": "Normal",
            "content": null
          },
          {
            "guid": "61cbfeea-30eb-41b1-b127-e0ce5ec2cfc2",
            "styleName": "Normal",
            "content": "<span class=\"styleName_Hyperlink\">asd</span>"
          },
          {
            "guid": "c90a005e-cc46-4e80-9520-f961fa608be9",
            "styleName": "Normal",
            "content": null
          },
          {
            "guid": "86ebc385-9dec-4bb2-8558-df24fe370ab7",
            "styleName": "Normal",
            "content": "<span class=\"styleName_Added_SPACE_Text\">asdasd</span> "
          }
        ]
      },
```

**Comment by myieye** [comment]
We could just add the lazy property, but I'd like to know where it comes from first. Perhaps it's not supposed to be there and there's a bug somewhere further up.

**Comment by lambaradan** [comment]
Hello. The error report is mine. Yes, the project in question had a custom field of type Multiparagraph Text. It was meant to be a catch-all field for all sorts of supplementary information, and I though it would need to be longer than one line.

It's worth mentioning that this error somehow also "contaminated" another existing project of long standing that had been error free before.

The data for the project originated from a LibreOffice spreadsheet, saved in Excel .xls format and modified with Sheetsweeper to a .db file, which was imported into FLEx. I remember the import process complaining about the Multiparagraph field, but don't recall the details. Sorry.

The original uploads were deleted totally from Language Forge, and I did a new sync from FLEx, but the errors continued.

Now I have deleted the MultiParagraph field from the project in FLEx totally, and resync'ed to Language Depot. Initially I saw one error message, similar to the previous ones. But this morning, I have fiddles with the project in Language Forge and not had an error.

I will continue playing with it, and update this entry with the results...

Please let me know what else you need from me.

**Comment by rmunn** [comment]
Hi @lambaradan, I've been taking a look at your error. I was able to confirm that the custom multiparagraph field is still present in the Language Forge data, and I believe that's why you're seeing these errors from time to time: there seems to be a bug in the multiparagraph field handling in Language Forge, in some code that we added last year. You mentioned that you had deleted that custom field from FLEx and then did another sync from FLEx; after that sync, did you then do another Send/Receive from Language Forge? I would expect doing a Send/Receive in Language Forge to pick up on the deleted field from FLEx and remove it from the Language Forge project, so if you did a Send/Receive in Language Forge and it didn't delete the field, that's another bug we need to look at. If you haven't done a Send/Receive in Language Forge yet, then please do so, and let us know if it runs into any errors. If it completes successfully, then I believe that should solve your issue.

**Comment by lambaradan** [comment]
Hi @rmunn! Thanks for following up. I had already sync’ed after deleting the custom field with Multi Paragraphs, a few days ago, and got the error message in my previous posting in Language Forge anyway...
Just now I sync’ed from Language Forge to Language Depot, and then sync’ed then in FLEx. I checked FLEx before and after this latest sync, and the offending custom field was not there.
Then I waited a few minutes and sync’ed FLEx again.
In Language Forge Settings/Configuration/Fields, the offending custom field does not appear.
I am now getting a new error: RPC Error: Server Status Code 500.
And the “lazy property” error has also reared its ugly head.
What do you suggest we do next, please?

![Screen Shot 2023-06-01 at 9 28 00 AM](https://github.com/sillsdev/web-languageforge/assets/58031919/08ea834a-dceb-4369-9650-1eebe629f11b)

![Screen Shot 2023-06-01 at 9 35 59 AM](https://github.com/sillsdev/web-languageforge/assets/58031919/eacdc9f7-2c5b-4259-bce8-35afa4338801)

**Comment by rmunn** [comment]
@lambaradan I'll take a backup of your project data so that I can restore it in case I make a mistake, then I'll manually delete the custom Note field (the multiparagraph one) from your project data in the Language Forge database. That will be a "live" edit so you should see it take effect as soon as I make it, without needing to do a Send/Receive first. (I haven't done it yet; I'll make the backup first, then do the edit, and I'll let you know once I've made the edit).

That should take care of your issue right away. Long-term, I'll need to fix the bug with custom MultiParagraph fields in Language Forge so that you, and others who might want to use them, can use them again.

**Comment by lambaradan** [comment]
@rmunn Thank you. Please go ahead, and let me know when I can test my project on Language Forge. Once the change has been made on your side, how do I then proceed with sync'ing to FLEx? Would I just sync as usual from FLEx? Would this import the live changes you are making? Thanks again.

**Comment by rmunn** [comment]
@lambaradan I've made the backup and finished modifying your project data to remove the custom Note field. You should be able to use it as normal, and do Send/Receive from LF and from FLEx as normal. Please let me know if you run into any issues with Send/Receive, or if the `paragraphsHtml` error message occurs again.

**Comment by lambaradan** [comment]
@rmunn Thanks again. Sorry to report that I got the Server Status Code Error 500 after updating my configuration for which fields to hide if empty. And after adding data to a few fields at random, got the error I am attaching twice...

![Screen Shot 2023-06-02 at 10 29 20 AM](https://github.com/sillsdev/web-languageforge/assets/58031919/3568e372-a4e4-439f-8785-7eb54f70644d)

**Comment by myieye** [comment]
@lambaradan Hi there, very sorry for the delay!

I've dug into the problem a bit. In the process I took the liberty to make some small changes to your project (all of which I reverted again). I wasn't able to trigger the error, even though I made updates to the same lexical entries that you were also working on.

I'm guessing the error is unpredictable and happens somewhat at random? Or does it completely block you from getting anything done?

I have a suspicion as to what the issue might be, but as I can't reproduce it, it's hard to know for sure. At the very least, we'll add some additional logging that will give us more context when it happens again. Our logs indicate that a small handful of projects have had the same issue.

**Comment by lambaradan** [comment]
@myieye Hello. Thanks for looking into it. So, I should go back in and try to trigger the error messages, and you will be watching?

**Comment by myieye** [comment]
@lambaradan I'll let you know once we've made more progress on this. Right now, we likely wouldn't learn anything new if you were to trigger the error message again.

But, it would be helpful to know: does this occur predictably or unpredictably?

**Comment by lambaradan** [comment]
@myieye I can't say that when I input data into a specific field for a specific entry that it always triggers the error. I haven't been paying attention to such a detailed degree.

**Comment by myieye** [comment]
@lambaradan I believe I've found the problem. So, I'm going to close this issue and track progress in #1757.
