### ISSUE TITLE
bug: Multiple changes in quick succession on new entry cause exception

### ISSUE THREAD

**Issue by myieye** [sillsdev/web-languageforge#1757]
**Describe the bug**
Making multiple changes in quick succession on a new entry can lead to an exception.

When a new entry is created it doesn't have an ID. When making multiple changes quickly, the state of the ID is not managed well and as a result ends up geting included in the entry-diff. The differ doesn't know that the server doesn't like string IDs, but IDs should never be part of the diff anyway, because they should only get set by the server.

**To Reproduce**

1. Go to the Editor
2. Click on '+' (Create new entry). Note: an entry only actually gets created when some data is added to it.
3. Quickly click on "Add meaning" and then "Add example"

**Context**
Reported by user: https://github.com/sillsdev/web-languageforge/issues/1754#issuecomment-1573362411

**Comment by myieye** [comment]
I've also found some race conditions that come into play when a user makes a change and then navigates to a different entry before the save has round-tripped to the server. In my opinion it's actually more likely that that is what the user was experiencing. I've added fixes to the open PR.

Presumably I will merge, test and deploy this fix tomorrow.

**Comment by lambaradan** [comment]
My scenario involved updating one or two fields in a few different entries in fairly rapid succession. The error took a minute or two to show itself always. I hope your fix works, @myieye ! Thanks.

**Comment by myieye** [comment]
@lambaradan These fixes were just deployed. So, if anything is still going wrong, we'd love to know about it!
Thanks for reporting this!

**Comment by lambaradan** [comment]
@myeye I have been able to update multiple fields in entries, one after another. And nothing I have done has triggered an error message. It seems to be working just fine. Thank you.
