### ISSUE TITLE
Interupting loading the dictionary the first time leaves users in a state they can't recover from

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/web-languageforge#1774]
When you load a project for the first time it loads all the entries in chunks. If this process is interrupted then the number of entries will not match what's in the database. The only way for a user to recover from this state is to delete the cache for the language forge site. This is both difficult to explain and invalidates any other projects that have been cached successfully.

Potential solutions:

1. add a clear cache button which would clear the cache for the current project and reload the page.
2. allow resuming from an interrupted first load. It may be possible if the entries are loaded by a stable value like created date for the frontend to just resume by requesting values created after the last entree received when loading.

One way we could detect this state automatically is by comparing the total entry count locally with what's in mongo. If we implement solution 2 we also need solution 1 as a fallback.

**Comment by megahirt** [comment]
See also #1024
