### ISSUE TITLE
bug: PHP lex_stats call shouldn't return entire entries list

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#1775]
See https://github.com/sillsdev/web-languageforge/issues/1773#issuecomment-1725240972 for details. On a project with more than 30,000 entries, `lex_stats` is trying to return *all* the entries and running out of memory. It should only be returning an entry count, plus a count of how many entries have pictures and how many have audio, both of which would be easy to get with a simple Mongo query.

**Comment by rmunn** [comment]
It's rather hard to construct a Mongo query for "entries with audio", because:

1. We record audio writing systems with `-audio` at the end of the tag
2. Our Mongo structure uses writing systems as keys
3. You can't match a regex against a key in Mongo's query syntax, only against values

To construct a Mongo query for audio, we'll need to first build a list of audio writing systems in the project config, then construct a query that checks entry, senses, and examples for those writing systems. (Which could, in theory, appear in any field of the entry, sense, or example). That's not a simple Mongo query to construct.

**Comment by rmunn** [comment]
It is actually surprisingly difficult to construct a Mongo query for "entries containing audio", and I'm becoming persuaded that it's not worth the effort. I'd rather remove the "entries containing audio" part from the dashboard and replace it with something else, such as "entries with comments" or "entries with TODO status in a comment". The amount of programming effort of the audio feature seems to be outpacing its value to the users.

**Comment by megahirt** [comment]
You're right - I remember this coming up when Billy was working on developing the dashboard.  I think the proper way to implement this is through a "audio count" or "hasAudio" property on the entry for the purpose of querying, and this is maintained as a separate property from the writing system.  Of course, this would also require changes to the existing API and a data migration.

The cheap way forward, which avoids changes and fixes problems with projects that encounter the 500 error, is to just remove the "entries with audio" stat as you suggested.
