### ISSUE TITLE
RTL text in the search box gets obscurred

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#21]
See graphic below:

![image](https://cloud.githubusercontent.com/assets/7088137/7697042/0f7549bc-fe04-11e4-9d0f-8dfe60e94e99.png)

This on the opening page and x is on the right side where RTL text gets typed.

**Comment by darcywong00** [comment]
Duplicate of https://github.com/sillsdev/web-languageforge/issues/33
