### ISSUE TITLE
Newly-created custom field has "blank" input system

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#28]
This may be related to #27, as it shows similar symptoms.

I created a new, empty Dictionary project using French (fr) as the primary language. I then added an input system that's a variant of French using the Thai script (code fr-Thai, and I picked the abbreviation thfr for display in LanguageForge). I then clicked Apply, refreshed the configuration page so the new input systems would be picked up, and clicked on the Fields tab. I then created a new custom field at the Entry level, with the type Multi-input-system Text. The result was:

![Screenshot of buggy custom field setup with blank input system](https://cloud.githubusercontent.com/assets/90762/11418186/3fc93eb0-9450-11e5-9757-7b785348d1e9.png)

Note the checked, but blank, input system.

I suspect that creating a new variant input system (as I did) has nothing to do with the bug and that it would have happened even if I'd just had French and English in the project, but I haven't yet tested that scenario.

**Comment by rmunn** [comment]
If I uncheck the "blank" input system and check some others (like `fr` and `thfr`), then refresh the page, the "blank" input system is no longer visible and everything looks normal.

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-39
