### ISSUE TITLE
Fieldworks crashed on LIFT export

### ISSUE THREAD

**Issue by indiamcq** [sillsdev/web-languageforge#30]
![flex-error](https://cloud.githubusercontent.com/assets/1505640/14411090/d3fb3bbe-ff68-11e5-8cc3-9c6f14def447.GIF)

Click for details
hasRight method cannot be called directly from ProjectModel line 157 /var/www/languageforge.org/htdocs/models/ProjectModel.php 
sf.php line 713, RightsHelper->userCanAccessMethod(lex_configuration_update, Array)

JsonRpcServer.php line 67, f->checkPermissions(lex_configuration_update, Array)

api.php line 18, JsonRpcServer::handle(sf, CI_Output)

Happened when exporting Lift file. After I created folder to export to.

Ian

**Comment by megahirt** [comment]
Hi Ian,

Thanks for reporting this bug.  It appears that the import is failing for your particular data and we'd like to fix that.  Can you email me the zip file you were trying to upload?  Email chris_hirt at sil dot org

Thanks,

Chris

**Comment by indiamcq** [comment]
Chris,

I was exporting not importing. As it crashed it did not give a LIFT file.

Are you back in Chiang Mai? I was in CM last two weeks for EMDC and now 
in Bangkok with Tim for Publishing CoP.

Ian

**Comment by megahirt** [comment]
Hi Ian,

I am back in CM.  Sorry I missed you.  Group conference was the same time
as EMDC.  I will close this issue as this should be reported as a bug in
FLEx.  Have you tried the latest version of FLEx?

Chris
