### ISSUE TITLE
Right to left word obscured by the 'X' in the search box

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#33]
![image](https://cloud.githubusercontent.com/assets/7088137/15495029/eceddc98-218d-11e6-8519-cdfee8b8949e.png)

**Comment by rmlockwood** [comment]
This also happens in the search box on the left side when an entry is showing.

**Comment by darcywong00** [comment]
This fix will be visible on languageforge.org when the send/receive functionality is released.
