### ISSUE TITLE
S/R: Deleting picture in FLEx, Edit caption in LF, Send/Receive, yields broken link in LF

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#39]
In this test of a conflict scenario:
1. FLEx user deletes a picture, does Send/Receive
2. LF user edits the caption to the same picture, does Send/Receive
3. The file deletion of the FLEx picture wins, and the LF caption edit wins.

This yields a broken picture link on LF (blank non-existent fiilename), with an edited caption.

When FLEx to FLEx does this scenario, no picture is displayed, but the caption remains

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-35
