### ISSUE TITLE
Large gap in the list of entries

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#41]
in the Test-Farsi project, search for fire (آتش) click on that entry in the search results.
In the list next to the entry there is a large gap in the entries. The entry above 'fire' is 'spittle' when actually in my FLEx project there are about 2 pages of entries between these two. See image attached.
![image](https://cloud.githubusercontent.com/assets/7088137/18028143/7774a120-6c2b-11e6-8f23-6b9ee9064d48.png)

**Comment by megahirt** [comment]
I wonder if this is a sorting issue.  I haven't seen a case yet where the
number of entries is mis matched but I have seen in my experience that the
entries are sorting differently between LF and Flex.

**Comment by megahirt** [comment]
Closing as this issue has likely been resolved with improved sorting.  Please re-open if this is still an issue.
