### ISSUE TITLE
Delete vs Edit S/R : The entry failed to retain and it get deleted

### ISSUE THREAD

**Issue by santhosh20** [sillsdev/web-languageforge#43]
From the test plan scenario as below 

Edit conflicts: FLEx edits entry, LF deletes entry
1. Record the FLEx project identifier that is used for this test scenario:
2. In one browser, login to Language Forge (LF) as the first user (Owner).
3. Browse to the LF project that corresponds to the FLEx project identifier.
"4. If the Send/Receive status (next to the ""Send/Receive"" button) says ""Un-synced"", click the ""Send/Receive"" button.
Wait until the status reports ""Synced""."
5. In FLEx, edit an entry, and do Send/Receive.
6. Verify the edits are retained.
7. In LF, find the same entry that FLEx edited above, and delete the entry. Click "Save Entry" (or wait for autosave).
8. Click "Send/Receive" from the Owner. Wait for S/R to complete.
9. Verify the edited entry remains (is not deleted).

**After step number 9, the edited entry get deleted instead of retain.

From the test plan "https://docs.google.com/spreadsheets/d/1aKKigd8FT-ak8VSfONzVgelxogcyVy9LB50ZpFgj6Eg/edit#gid=876420129" - row number 124.

**Comment by bbryson** [comment]
Just for reference, some related issues for FLEx-FLEx S/R:

https://jira.sil.org/browse/LT-14099
https://jira.sil.org/browse/LT-14681
https://jira.sil.org/browse/LT-13524

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-34
