### ISSUE TITLE
New S/R projects start with "Example" showing ana languages instead of vern

### ISSUE THREAD

**Issue by bbryson** [sillsdev/web-languageforge#45]
Over in FLEx I entered an example sentence, but after I did S/R, in LF it looked like the Example was empty.  In fact, on LF it was showing my two analysis languages for the Example, not the Vernacular language.  Once I went to Fields and adjusted it, what I entered in FLEx appeared fine.

Then I tried with another brand new project (again with two ana languages).  When I sent the project from FLEx to LD for the first time, there was only one entry, and no example entered.  On LF, I got the project from LD.  Then I clicked the orange "Add Example Sentence" in LF.  Now it shows me the Example field, but only in the Ana languages, not the Vern language.  It should default to showing the Vern language(s) for Example.

When I create a brand new LF project (not a S/R project), it comes up fine:  the default for Example is the vern language.

Projects used for this test:
Indonesian Test
Test Chinese
Test French (LF only, not a S/R project)

![newsrproject](https://cloud.githubusercontent.com/assets/4039852/18188832/ec992ef0-707a-11e6-84d5-cb09bfe8070c.png)

**Comment by darcywong00** [comment]
This will be tracked in https://github.com/sillsdev/LfMerge/issues/27
