### ISSUE TITLE
LSA: custom field disappears after sync

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#58]
From LSA 2017 user Elliot:

I had thought some custom fields were working, but really just they were some default fields that Fieldworks calls custom.  In fact, I had a custom field made in Languageforge disappear after a sync.  I plan to just hold extra metadata in the existing notes fields.

**Comment by rmunn** [comment]
I've been able to reproduce this issue in my `test-rmunn-03` repository, and I've begun working on identifying the cause of the problem so that it can be fixed.

**Comment by EThornton** [comment]
Thanks,

I've noticed my FLEx created fields are working, but not languageforge created ones.

**Comment by rmunn** [comment]
Unfortunately, we do not yet support creating custom fields in Language Forge and having them synced to FLEx. It's on our list of future features, but we do not yet have it scheduled to implement. As a workaround, you can make sure that any custom fields are created in FLEx and then use Send/Receive to transfer them to Language Forge, and that should work. (Well, once the bugfix has been deployed to the Language Forge site -- we were having some trouble with our testing servers yesterday, so it hasn't yet been tested enough to deploy).

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-33
