### ISSUE TITLE
LSA: request for more detailed activity log

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#60]
From LSA 2017 user Elliot:

Most desired features from talk are a list of active comments and more detailed activity log.

**Comment by EThornton** [comment]
Thanks for submitting this.

What I have discussed with a few linguists is the desire for the log to show fields and changes:

 5 minutes ago
eddersko updated the word for “áabaci” in test-hid-flex: “ábaci”->"“áabaci”"
eddersko updated the note for “áabaci” in test-hid-flex: ""->"recording 1345 suggests long a"

**Comment by ThomasBlok** [comment]
Issue moved to https://jira.sil.org/browse/LF-32
