### ISSUE TITLE
LSA: LF lagging for some users

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#61]
From LSA 2017 user Elliot

There seems to be some lagging for some users.  Anything you can think of to optimize their experience a bit?

**Comment by EThornton** [comment]
Thanks for submitting this.

The main issue here lies in the entry view.  It will sometimes take as many as 5 seconds for a field to become active for editing once clicked.  Typing changes can also sometimes take a few seconds to show up.

Thanks,
Elliot

**Comment by megahirt** [comment]
Elliot, can give us a sample entry in an existing project where you see
this lagging?  Thanks, Chris

**Comment by makerling** [comment]
I received feedback from a language project that is experiencing lagging during normal use. The project has 5023 entries. While editing entries or creating new ones every few seconds the site experiences a several seconds of freezing: 

> the system needs so much energy to display everything that the system breaks down as soon as we navigated a bit. We tried to search for an entry – it didn’t bring a result. We tried to delete the Abaze, Abazin entries just at the beginning of the dictionary, the same. It had said, the “script is to long”, so we re-load the dictionary several times. So after 40 minutes trying to work, we gave up. [Language helper] uses internet explorer. I use Firefox and tried in in Chrome as well, it is a bit better in Chrome, but still for every navigation I do have to wait 6 seconds untill I see my cursor working. It don’t break down so often, but it reacts still very slowly. I believe it is because we have 5000+ entries. 

The project is deu-zazaki-flex if you want to look at it. 

Thanks.

**Comment by megahirt** [comment]
Our performance has improved with the optimization of the sorting code.  I suspect this was the main complaint.  Closing.
