### ISSUE TITLE
LFMerge container functioning with rest of application

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#818]

**Comment by megahirt** [comment]
Tasks for LFMerge container:

- share /var/lib/languageforge directory between api and lfmerge container
- crontab for lfmerge container to run lfmerge every minute
- research inotify hook as replacement for crontab
- future work: remove php code that assumes it can start lfmerge directly
- test actual send/receive using local dev environment (need existing credentials)

**Comment by megahirt** [comment]
There are three directories that lfmerge cares about:
/var/lib/languageforge/lexicon/sendreceive/syncqueue
/var/lib/languageforge/lexicon/sendreceive/state
/var/lib/languageforge/lexicon/sendreceive/webwork

only /var/lib/languageforge/lexicon/sendreceive/syncqueue needs to be watched for changes

When a file appears in syncqueue, we need to start lfmerge via the follow path:
/usr/bin/lfmergeqm

**Comment by longrunningprocess** [comment]
This is really helpful info, thank you for not making me figure all this stuff out on my own :-D

**Comment by longrunningprocess** [comment]
based upon some findings, extracting lfmerge from lf is going to be more involved than anticipated (https://github.com/sillsdev/web-languageforge/pull/857#issuecomment-792453491) therefore this is going to go back on to the back burner.

**Comment by megahirt** [comment]
We should be able to integrate LFMerge deb package directly into the api container.  So basically install the debian package and go from there inside the api container.
