### ISSUE TITLE
move PHP test fixtures (USX files) located in /docs folder over to the /test folder

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#822]
To run the php tests:
run `make tests` from the docker folder

The output should look like this:
![image](https://user-images.githubusercontent.com/3444521/107766831-a9ee7180-6d66-11eb-9f95-4319bf8b6895.png)

Once you confirm that tests are passing for you (except for the 2 failing tests having to do with LFMerge), then you can refactor the USX test fixture location.

The simplest way to I know to do this is the simply rename the /docs folder to something else (e.g. /docs2) and then run the tests.  You will see several tests fail, and the error message will say something about not being able to find a certain file.  Simply move the file into the `/test/common` folder and then change the test code to suit.  It seems like /test/common is where all the other test fixtures are located.

**Comment by longrunningprocess** [comment]
@megahirt does this need to be tested again or something?  Trying to understand why you moved it from done back to reviewer approved, thanks.

**Comment by megahirt** [comment]
@longrunningprocess good question.  I was going to move them across the board manually during standup for Rick and other's benefit but then it was just us.  I'll move it back to done.

**Comment by longrunningprocess** [comment]
ah yes, ok, that makes sense.
