### ISSUE TITLE
deploy master branch to qa.languageforge.org

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#882]
TODO:

- [x] test email
- [x] non-send/receive project
- [x] oauth authentication

**Comment by longrunningprocess** [comment]
>  test send/receive with languagedepot

Seems there is a credential check that is functioning, maybe that's enough to smoke test the LF->LD integration? @megahirt @rmunn

**Comment by longrunningprocess** [comment]
looks like we've got things to where we wanted for the most part.  Any additional findings will be handled normally via issues, bug reports, etc.
