### ISSUE TITLE
QA-docker deployment:  Need to begin to understand any tokens the API needs and how to get those in place in a Docker environment.

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#896]
ref: https://github.com/sillsdev/web-languageforge/blob/master/gulpfile.js#L207

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `ENVIRONMENT` | being used to establish a default | 
| src/index.php: `ENVIRONMENT` | being used to establish bugsnag/twig config | 
| src/Api/Service/Ldapi.php: `ENVIRONMENT` | being used in errorhandling | 
| src/Site/Controller/Auth.php: `ENVIRONMENT` | being used to fail fast over script access... | 
| test/php/TestConfig.php: `ENVIRONMENT` | being used to establish default |

**Comment by longrunningprocess** [comment]
`src/config.php`: userConfig.php, I'm guessing this is meant for custom overrides but I'm not sure, I'd suggest we get rid of this if possible.

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `SF_DATABASE` | being used to establish a default | 
| scripts/scriptsConfig.php: `SF_DATABASE` | being used to establish a default | 
| scripts/tools/FactoryReset.php: `SF_DATABASE` | being used in a mongo call | 
| src/Api/Library/Shared/CLI/RunClass.php: `SF_DATABASE` | being used to establish a default (note: diff database in this case) | 
| src/Api/Library/Shared/Script/Utility/EnsureDBIndexes.php: `SF_DATABASE` | being used in a mongo call | 
| src/Api/Model/Shared/ProjectModelMongoMapper.php: `SF_DATABASE` | being used in a mongo call | 
| src/Api/Model/Shared/UserModelMongoMapper.php: `SF_DATABASE` | being used in a mongo call | 
| src/Api/Model/Shared/UserRelationModel.php: `SF_DATABASE` | being used in a mongo call | 
| src/Api/Model/Shared/UserRelationModelMongoMapper.php: `SF_DATABASE` | being used in a mongo call | 
| test/app/setupTestEnvironment.php: `SF_DATABASE` | being used in fail-fast error handling and  a mongo call | 
| test/common/MongoTestEnvironment.php: `SF_DATABASE` | being used in a mongo call | 
| test/php/TestConfig.php: `SF_DATABASE` | being used in a mongo call | 

I'd propose renaming this named constant to `DATABASE` and following the similar approach stated above if this cannot be hardcoded due to testing and an overlap of database names...not sure about that.

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| scripts/scriptsConfig.php: `MONGODB_CONN` | being used to establish a default | 
| scripts/tools/FactoryReset.php: `MONGODB_CONN` | being used for a config | 
| src/config.php: `MONGODB_CONN` | being used to establish a default | 
| src/Api/Model/Shared/Mapper/MongoStore.php: `MONGODB_CONN` | being used in a mongo call | 
| test/php/TestConfig.php: `MONGODB_CONN` | being used to establish a default | 

I'd propose same approach as above, establishing an env var that is guaranteed to be populated.

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `USE_MINIFIED_JS` | being used to establish a default | 
| src/Site/Controller/Base.php: `USE_MINIFIED_JS` | being used for config | 

I'd propose we get rid of this altogether and simply set the config to `true` in `Base.php`

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `REMEMBER_ME_SECRET` | being used to establish a default | 
| src/index.php: `REMEMBER_ME_SECRET` | being used for config | 

I'd propose we simply hardcode this...it doesn't seem to be parameterized on TC.

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `LANGUAGE_DEPOT_API_TOKEN` | being used to establish a default | 
| src/Api/Model/Languageforge/Lexicon/Command/SendReceiveCommands.php: `LANGUAGE_DEPOT_API_TOKEN` | being used for config | 
| src/Api/Service/Ldapi.php: `LANGUAGE_DEPOT_API_TOKEN` | being used for config | 
| test/php/TestConfig.php: `LANGUAGE_DEPOT_API_TOKEN` | being used to establish a default | 

I'd propose the same aforementioned approach

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `GATHERWORDS_CLIENT_ID` | being used to establish a default | 

I don't see any usages of this upon a simple search, maybe this is not being used anymore and should be removed?

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `NG_BASE_FOLDER` | being used to establish a default | 
| src/Site/Controller/App.php: `NG_BASE_FOLDER` | being used for config | 
| src/Site/Controller/Base.php: `NG_BASE_FOLDER` | being used for config | 

I'd propose we simply hardcode this in `Base.php` which will make it available to `App.php` by inheritance.

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| webpack.config.js: `BUGSNAG_API_KEY` | being used to establish a default **(build-time only)** | 
| src/config.php: `BUGSNAG_API_KEY` | being used to establish a default | 
| src/index.php: `BUGSNAG_API_KEY` | being used for config | 
| src/angular-app/bellows/core/exception-handling.service.ts: `BUGSNAG_API_KEY` | being used for config **(build-time only I believe)** | 

As for the backed needs, I'd propose the same approach as above.  This is a little more unique in the sense that the UI also needs it but I believe the key is built into the `dist/bundle.js` so this value would only be needed during build time...need to look at the right approach to make that happen as part of the image build step.

**Comment by longrunningprocess** [comment]
| variable | usage |
| - | - |
| src/config.php: `BUGSNAG_NOTIFY_RELEASE_STAGES` | being used to establish a default | 
| src/Api/Library/Shared/Palaso/Exception/BugsnagExceptionHandler.php: `BUGSNAG_NOTIFY_RELEASE_STAGES` | being used for config | 

Same approach as above.

**Comment by longrunningprocess** [comment]
Can't find any use of `JWT_KEY` in the codebase, need to determine if this is still needed.

**Comment by longrunningprocess** [comment]
gulp usage:

build-and-upload --buildNumber %build.number% --applicationName %system.application.name% --mongodbConnection %system.mongodb.connection% --createRestartFile %system.restart-file% --languageDepotApiToken %system.languagedepot.api.token% --secret %system.build.secret% --dest %system.upload.destination%

**Comment by megahirt** [comment]
I think we can move a lot of these through really fast if each of the variables/areas you've called out as separate PRs.  This is great investigative work.

**Comment by megahirt** [comment]
> REMEMBER_ME_SECRET

Let's make this into a real environment variable...looks like we never got around to making this work with TC.

**Comment by megahirt** [comment]
> variable	usage
> src/config.php: `GOOGLE_CLIENT_ID`	being used to establish a default
> src/Site/OAuth/GoogleOAuth.php: `GOOGLE_CLIENT_ID`	being used for config
> src/config.php: `GOOGLE_CLIENT_SECRET`	being used to establish a default
> src/Site/OAuth/GoogleOAuth.php: `GOOGLE_CLIENT_SECRET`	being used for config
> src/config.php: `FACEBOOK_CLIENT_ID`	being used to establish a default
> src/Site/OAuth/FacebookOAuth.php: `FACEBOOK_CLIENT_ID`	being used for config
> src/config.php: `FACEBOOK_CLIENT_SECRET`	being used to establish a default
> src/Site/OAuth/FacebookOAuth.php: `FACEBOOK_CLIENT_SECRET`	being used for config
> I'd propose the same approach as mentioned above but additionally would remove references from `config.php` altogether.

Yes, remove from config.php and just pull it from the environment.

**Comment by megahirt** [comment]
> variable	usage
> src/config.php: `GATHERWORDS_CLIENT_ID`	being used to establish a default
> I don't see any usages of this upon a simple search, maybe this is not being used anymore and should be removed?

delete - not used anymore

**Comment by megahirt** [comment]
> variable	usage
> src/config.php: `NG_BASE_FOLDER`	being used to establish a default
> src/Site/Controller/App.php: `NG_BASE_FOLDER`	being used for config
> src/Site/Controller/Base.php: `NG_BASE_FOLDER`	being used for config
> I'd propose we simply hardcode this in `Base.php` which will make it available to `App.php` by inheritance.

remove redundancy

**Comment by megahirt** [comment]
> variable	usage
> src/config.php: `NG_BASE_FOLDER`	being used to establish a default
> src/Site/Controller/App.php: `NG_BASE_FOLDER`	being used for config
> src/Site/Controller/Base.php: `NG_BASE_FOLDER`	being used for config
> I'd propose we simply hardcode this in `Base.php` which will make it available to `App.php` by inheritance.

remove variable - hardcode in base and app (and wherever it is)

**Comment by megahirt** [comment]
> variable	usage
> webpack.config.js: `BUGSNAG_API_KEY`	being used to establish a default **(build-time only)**
> src/config.php: `BUGSNAG_API_KEY`	being used to establish a default
> src/index.php: `BUGSNAG_API_KEY`	being used for config
> src/angular-app/bellows/core/exception-handling.service.ts: `BUGSNAG_API_KEY`	being used for config **(build-time only I believe)**
> As for the backend needs, I'd propose the same approach as above. This is a little more unique in the sense that the UI also needs it but I believe the key is built into the `dist/bundle.js` so this value would only be needed during build time...need to look at the right approach to make that happen as part of the image build step.

Sounds good - go ahead and figure out how to incorporate this variable at build time.

**Comment by megahirt** [comment]
> gulp usage:
> 
> build-and-upload --buildNumber %build.number% --applicationName %system.application.name% --mongodbConnection %system.mongodb.connection% --createRestartFile %system.restart-file% --languageDepotApiToken %system.languagedepot.api.token% --secret %system.build.secret% --dest %system.upload.destination%
> 
> TODO: account for these in the migration strategy

Here's what I know (or don't know):

- **buildNumber** - used to stamp the HTML file showing the application version (bottom right in the footer)
- **applicationName** - not used anymore
- **mongodbConnection** - um yeah
- **createRestartFile** - I honestly have no idea what this is for
- **languageDepotApiToken** - yes we need this.  I don't know how this is used differently from the environment variable
- **build.secret** - sounds important, yet I cannot recall what this does, if anything
- **upload.destination** - not used anymore

**Comment by megahirt** [comment]
> ref from TC: can't find any use of `JWT_KEY` in the codebase, need to determine if this is still needed.

if you cannot find any code references, then assume it is dead wood and can be safely ignored.

**Comment by megahirt** [comment]
> ref: https://github.com/sillsdev/web-languageforge/blob/master/gulpfile.js#L207

Here's a new ref for you: https://gist.github.com/megahirt/a395156dbc3c014c57e6c44a9f2ab3c0#file-gulpfile-js-L82

**Comment by longrunningprocess** [comment]
aspects of this issue still outstanding:

> buildNumber - used to stamp the HTML file showing the application version (bottom right in the footer)
This needs to be done in a new way

`src/Api/Library/Shared/CLI/RunClass.php`'s use of a `DATABASE` may be broken for some special use case for LFMerge testing...

OAuth issues outstanding in QA runtime:
1. Google console needs to have oauth info updated
2. Facebook oauth setup needs to be configured to allow qa requests (whitelisting update)

Not sure how you're prefer to handle these @megahirt , we could create new issues/cards for them or continue working off this issue.
