### ISSUE TITLE
Clear a dictionary

### ISSUE THREAD

**Issue by kentschroeder** [sillsdev/web-languageforge#9]
I added the wrong word list to my Borana project (i.e. a word list from a another language) by mistake.  I would like to delete all the entries and start from scratch.  How can I do that?

**Comment by irahopkinson** [comment]
Hi Kent

Simply deleting all the entries won't be enough because the project
settings contain lots of configuration information as well. To resolve this
issue:

   1. Click *My Projects*.
   2. Check (select) your project with the wrong data in it, then
click *Archive
   Selected Projects*.
   3. Create a new project with the correct data.

Blessings, Ira

On Wed, Feb 11, 2015 at 8:28 PM, Kent Schroeder <notifications@github.com>
wrote:

> I added the wrong word list to my Borana project (i.e. a word list from a
> another language) by mistake. I would like to delete all the entries and
> start from scratch. How can I do that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sillsdev/web-languageforge/issues/9>.
>



-- 
Ira Hopkinson

SIL International Language Software Development, PaLaSo <http://palaso.org/>

**Comment by kentschroeder** [comment]
Ira,

 

I do not an archive option. I do not see any way to select the project, as there is no checkbox.  Attached is a screen shot of the My Projects web page.  When I click on the project, I get the Browse and Edit page.

 

Kent

 

Kent Schroeder 
Software Developer/Language Technology Consultant 
SIL – Africa-Focused Shared Services

Nairobi, Kenya

**Comment by darcywong00** [comment]
Hi Kent,
We've made some recent updates to languageforge.org, and you should be able to Archive your project with these steps:

From your project page, select the "Settings" gear icon on the top right of the page -> Manage Project
That will take you to the Project Management page
Select the "Archive" tab -> "Archive this project" button

Alternatively, with your permission, we can have a site admin go delete the Borana project for you.

-Darcy

**Comment by kentschroeder** [comment]
Darcy,

 

Please go ahead and delete the Borana project.

 

Kent

 

Kent Schroeder 
Domain Team Leader - Publishing & Language Technology 

SIL Anglo-Lusophone Africa

Nairobi, Kenya

**Comment by darcywong00** [comment]
OK, I've archived and deleted the Borana project. 

Before you re-create the Borana project, I just wanted to let you know we're rolling out the capability to Send/Receive a Language Forge project with a FLEx project.  Let us know if you'd be interested in trying this out, and @megahirt will send you the invitation with instructions.

-Darcy

**Comment by kentschroeder** [comment]
Darcy,

 

Yes, I would be interested, but I will not be able to do anything with until October.

 

Kent

 

Kent Schroeder 
Domain Team Leader - Language Technology 

SIL Anglo-Lusophone Africa

Nairobi, Kenya

**Comment by darcywong00** [comment]
Fixed with commit ab06acaa5934a8623124b6f620569b7194ef74cb
Allow project owners to delete their project

**Comment by megahirt** [comment]
closed as fixed
