### ISSUE TITLE
implement cache-busting

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#947]
The quickest way to implement this is to have our deployment script stamp the src/version.php script with an actual version number.

For reference: version.php - defines a PHP variable `version` which is used in container.html.twig 

If our continuous deployment process has a build version number, this could be stamped into the file in a manner similar to:

```
sed -i 's/9.9.9/BUILD_VERSION/g' input
```

- [x] confirm that cache busting is actually working

**Comment by longrunningprocess** [comment]
we discussed refactoring the approach to utilize epoch at build time.
