### ISSUE TITLE
get qxh-flex going again

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#949]
- [x] remove offending custom field in FLEX (Alex)
- [x] FLEx send/receive
- [x] take project off of HOLD (Chris)
- [x] LF send/receive
- [x] verify that data is ask expected
- [x] send Alex link to up-vote request for change in FLEx behavior regarding new entries being auto-added to publication list.

**Comment by alex-larkin** [comment]
I deleted the project in LF and re-added it. I am now able to realize changes and synchronize between FLEx and LF! What great news!
