### ISSUE TITLE
implement send-receive lfmerge persistent volume and test that it functions on QA

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#966]
app container persistent volume mount: 
`/var/lib/languageforge`

- [x] determine volume size: 8GB for QA, possibly 40GB for prod.
- [x] ensure `www-data` ownership (not `fieldworks` anymore – contingent upon PR's in LFmerge)
- [x] implement locally
- [x] update app deployment yml
- [ ] test that it works on QA

**Comment by longrunningprocess** [comment]
from some external team discussions:
> /var/lib/languageforge has just one subdirectory, lexicon, and lexicon has just one subdirectory, sendreceive. But that's the current state. It used to be that there was a second subdirectory under languageforge, called semdomtrans (for "Semantic Domain Translator"), and we might bring that back, or create another app in the languageforge site, at some point. So putting the mount point at /var/lib/languageforge is the simplest setup that allows for flexibility down the road.

In the interest of giving the persistent volume a more specific name as well as building toward what we know today, I'm going to map the volume to `/var/lib/languageforge/lexicon/sendreceive`.  I do this fully recognizing there may be a day when the semdomtrans might come into play and if/when it does, we'll see if moving the volume up a couple of directories is still appropriate.

**Comment by longrunningprocess** [comment]
testing locally:

1. "join" a project
2. enter prod creds for LD
3. pick project (must a mgr of the project)
4. choose the project from dropdown
5. wait
6. upon success, contents will be loaded into `/var/lib/languageforge/lexicon/sendreceive/webwork` under the project name
7. restart app container, i.e., `make clean` then `make`
8. project should still be listed
9. head into settings cog next to project name and "Synchronize"
10. notice if the syncing process is faster than the initial s/r

**Comment by longrunningprocess** [comment]
# test in QA

1. joined project
2. sync to LD currently failing, need to troubleshoot

**Comment by rmunn** [comment]
@longrunningprocess -

>     2. sync to LD currently failing, need to troubleshoot

I recently discovered that the sync to Language Depot needs `ping` installed or it will fail quietly without a log message. (When the sync process was built it was assumed that `ping` would always be available since it's part of the `minimal` set on Debian). Try adding `apt-get install iputils-ping` to the Dockerfile and see if that helps.

**Comment by longrunningprocess** [comment]
@rmunn 
as suspected in our talks, I've installed ping in our base image, published it to Docker Hub and redeployed our staging environment with it.  I did confirm it was in our app container for LF but I'm still seeing a broken comm issue in the LD db container.

**Comment by longrunningprocess** [comment]
the current failures look like they might've been there all along, unrelated to the volume work so I opened https://github.com/sillsdev/web-languageforge/issues/981 to address it but as far as the persistent volume goes, it is working just fine.
