### ISSUE TITLE
Add `iputils-ping` package to `app` container

### ISSUE THREAD

**Issue by rmunn** [sillsdev/web-languageforge#975]
The `lfmerge` package turns out to need `iputils-ping` to be present in order to work right. That package is present on any Debian/Ubuntu install, even a minimal server install, so we've never added it to the dependencies list for `lfmerge` because there wasn't any need before now. But a Docker container apparently contains even less than a minimal server install normally contains, and in particular the `ping` command isn't present. The Send/Receive process expects `ping` to be there, and doesn't deal well with its absence. (The bit of code that doesn't deal well with its absence is in either Chorus or LibPalaso, both of which will take longer to fix than simply adding `iputils-ping` to our Docker container). Without `ping` present, the Send/Receive process becomes simply a Receive process and doesn't actually Send anything to Language Depot. :-)

**Comment by megahirt** [comment]
> Without ping present, the Send/Receive process becomes simply a Receive process and doesn't actually Send anything to Language Depot. :-)

Well done - I had a good laugh when I read this.

**Comment by longrunningprocess** [comment]
closing since it was fixed in https://github.com/sillsdev/web-languageforge/pull/979/commits/301e6e98afcf531f50a0b306a35b264f4d922e43
