### ISSUE TITLE
Send/Receive functionality broken in staging environment

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#981]
I noticed during work on https://github.com/sillsdev/web-languageforge/pull/979 that "receive" seemed to work just fine locally but not in staging.  @rmunn is already in the midst of some LFMerge work that might or might not have something to do with this but it seems this use case may have been broken all along, if not in the "receive" portion, definitely in the "send" portion due to missing `ping` in the app container.  I've added `ping` to our base image though so hopefully that will help this functionality along.

**Comment by longrunningprocess** [comment]
team discussion on the matter so far:

> The reason why Send/Receive is failing on QA right now is because the /var/lib/languageforge/lexicon/sendreceive/state directory doesn't exist. LfMerge expects that directory to exist, and doesn't have any code to create the directory if it doesn't exist. Perhaps it should have such code, but that's the issue right now: that directory needs to be created (and owned by www-data like the others) during the app setup process.

error from `/var/log/syslog`: `Exception:#012System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/languageforge/lexicon/sendreceive/state'`

seems like a difference between volumes in docker/k8s...will confirm this today.

**Comment by longrunningprocess** [comment]
# local testing

## without the volume configs
I temporarily commented out the sendreceive volume: `lfmerge-sendreceive-data:/var/lib/languageforge/lexicon/sendreceive`

and see the following (as expected):
```
dc exec app ls -l /var/lib/languageforge/lexicon/sendreceive
total 36
drwxrwsr-x 1 www-data www-data 4096 Jun 21 14:47 ReleaseData
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 Templates
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 commitqueue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 mergequeue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 receivequeue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 sendqueue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 state
drwxrwsr-x 1 www-data www-data 4096 Jun 21 14:47 syncqueue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 webwork
```

## with the volume configs
after uncommenting the volume, here's what I see (as expected):
```
dc exec app ls -l /var/lib/languageforge/lexicon/sendreceive
total 36
drwxrwsr-x 2 www-data www-data 4096 Jun 21 14:47 ReleaseData
drwxrwsr-x 2 www-data www-data 4096 Jun 10 13:58 Templates
drwxrwsr-x 2 www-data www-data 4096 Jun 10 13:58 commitqueue
drwxrwsr-x 2 www-data www-data 4096 Jun 10 13:58 mergequeue
drwxrwsr-x 2 www-data www-data 4096 Jun 10 13:58 receivequeue
drwxrwsr-x 2 www-data www-data 4096 Jun 10 13:58 sendqueue
drwxrwsr-x 2 www-data www-data 4096 Jun 10 13:58 state
drwxrwsr-x 2 www-data www-data 4096 Jun 21 14:47 syncqueue
drwxrwsr-x 2 www-data www-data 4096 Jun 10 13:58 webwork

```

# staging test

## without the volume configs
I deleted the current k8s infrastructure as well as the sendreceive pvc.  I then updated the `app-deployment.yaml` to exclude the pvc request and all configs for the volume mapping.  I then redeployed staging and this is what I saw (again, as expected):
```
kubectl exec -it deploy/app -- ls -l /var/lib/languageforge/lexicon/sendreceive
total 36
drwxrwsr-x 1 www-data www-data 4096 Jun 21 14:47 ReleaseData
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 Templates
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 commitqueue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 mergequeue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 receivequeue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 sendqueue
drwxrwsr-x 1 www-data www-data 4096 Jun 22 14:17 state
drwxrwsr-x 1 www-data www-data 4096 Jun 21 14:47 syncqueue
drwxrwsr-x 1 www-data www-data 4096 Jun 10 13:58 webwork
```

## with the volume configs
I deleted the staging infrastructure again and restored the pvc as well as the volume configs and redeployed.  This is what I saw:
```
kubectl exec -it deploy/app -- ls -l /var/lib/languageforge/lexicon/sendreceive
total 16
drwx------ 2 root root 16384 Jun 22 14:23 lost+found

```

**Comment by longrunningprocess** [comment]
upon project creation in staging I see the following:
```
kubectl exec -it deploy/app -- ls -l /var/lib/languageforge/lexicon/sendreceive
total 28
drwxr-xr-x 2 www-data www-data  4096 Jun 22 15:03 editqueue
drwx------ 2 root     root     16384 Jun 22 14:23 lost+found
drwxr-xr-x 2 www-data www-data  4096 Jun 22 15:03 syncqueue
drwxr-xr-x 3 www-data www-data  4096 Jun 22 15:03 webwork
```

**Comment by longrunningprocess** [comment]
I then added a word and removed a word before "Synchronize -> Send/Receive".  That process worked just fine and I checked language depot and it reflected the changes properly.

**Comment by longrunningprocess** [comment]
so this leaves the following:

`editqueue`, `syncqueue` and `webwork` get created properly at run time.

`state` must be present before and S/R attempts.

`mergequeue`, `commitqueue`, `receivequeue`, `sendqueue`, `ReleaseData` and `Templates` are undetermined at this point, they should've been there from the lfmerge postinst but I'm not sure whether the lfmerge logic will create those on the fly as with the others.

The question in my mind is, do we tweak lfmerge to have consistent dir creation logic (when not present) or run some post-volume map logic to restore those dirs?  I personally like the idea of consistent dir creation logic but wonder what your thoughts are @rmunn @megahirt ?  In the meantime, I'll be looking at a technique to get hose dirs in place after the volume map.

**Comment by rmunn** [comment]
The `lfmerge` package is designed to create those directories when it's installed, and I think it's perfectly reasonable for code to assume that the directories created by its Debian package exist when it runs, so I think it doesn't really make sense to tweak the lfmerge code to create missing directories. It's preferable, IMHO, to use an init container to pre-populate the directories in the /var/lib/languageforge/etc volume. As far as I can tell from a brief Google search, when Kubernetes users need to pre-populate a volume that's just been created, an init container seems to be the most common way to do it.

**Comment by longrunningprocess** [comment]
yep, I hear you on the assumption, it just turns into "state" management and maintenance, e.g., if there were ever another dir added, it'd have been done in multiple places under this containerized arch...I'm not suggesting we don't go for the duplication of the postinstall work in an `initContainer` though, I've already got it in place for the ownership issue anyway, it should be easy enough to add the `mkdir`.
